WIP: Feature/realspace
project-asgard/asgard pull request #205
Opened 2019-12-10 22:24 UTC by stonecoldhughes

2019-12-17 16:10 UTC, bmcdanie commented
is this WIP or not? change title if ready for review.

2019-12-19 15:14 UTC, bmcdanie requested changes
aside from specific concerns, we need to see where we have functionality duplicated (e.g. execute batch job vs. batched gemm in batch component) and flatten our object structure here (batch sets + batch job is probably unnecessary). 

of course, the scalable routine will need to understand distribution, chunking, and the use of allocated workspaces already present. we may need to inform the allocation routines about our realspace transformation requirements.

are the existing realspace transform tests what you're using to test the top level method?

in CASL today if you want to discuss.

2019-12-19 15:14 UTC, bmcdanie commented on src/kron.cpp
> +#include "kron.hpp"
need to define public functions in the header and implementations in the cpp as in the other components.

2019-12-19 15:14 UTC, bmcdanie commented on src/kron.hpp
> +  for (iter = matrix.rbegin(); iter != matrix.rend(); ++iter)
make this more expressive/readable if possible and/or add comments within function about the process you're going through here.

additionally, add comments before function signature describing the routine's purpose, the meaning of its arguments, etc.

finally, add asserts detailing preconditions for your arguments.

2019-12-19 15:14 UTC, bmcdanie commented on src/kron.hpp
> +  batch_set(batch<P, resrc> &&bs)
if you're using the default move constructor, use `= default`

do we want a copy constructor?

this probably belongs in the batch component.

2019-12-19 15:14 UTC, bmcdanie commented on src/kron.hpp
> +  batch_set(batch<P, resrc> &&bs)
may be something we can use for the other batches rather than the `using` we have there now

2019-12-19 15:14 UTC, bmcdanie commented on src/kron.hpp
> +  batch<P, resrc> left;
if this is a public container for three `batches`, why not just use a container class?

is the entire purpose of this class to name the three `batch`es? not immediately opposed, just trying to figure out your reasoning.

2019-12-19 15:14 UTC, bmcdanie commented on src/kron.hpp
> +  batch_job(batch_job<P, resrc> &&bj)
default?

2019-12-19 15:14 UTC, bmcdanie commented on src/kron.hpp
> +class batch_job
can this be amalgamated into the above class?

2019-12-19 15:14 UTC, bmcdanie commented on src/kron.hpp
> +  void add_batch_set(batch_set<P, resrc> &&bs)
why are we passing this by rvalue reference?

2019-12-19 15:14 UTC, bmcdanie commented on src/kron.hpp
> +  std::vector<batch_set<P, resrc>> batches;
do all these need to be public/non-const?

2019-12-19 15:14 UTC, bmcdanie commented on src/kron.hpp
> +fk::vector<P, mem_type::owner, resrc> execute_batch_job(batch_job<P, resrc> &bj)
is this a copy of the `batched_gemm` in the `batch` component, except with your batch job api?

we don't need two such similar things - probably need to use the `batch job` stuff in both places or reuse the stuff there.

2019-12-19 15:14 UTC, bmcdanie commented on src/kron.hpp
> +  fk::vector<P, mem_type::owner, resrc> const &get_input_workspace()
what is the benefit of this vs. two vector members named in and out?

2019-12-19 15:14 UTC, bmcdanie commented on src/kron.hpp
> +    init_w0 = x;
what is this variable?

2019-12-19 15:14 UTC, bmcdanie commented on src/kron.hpp
> +kron_batch(std::vector<fk::matrix<P, mem_type::view, resrc>> const &matrix,
describe in comments above routine: arguments, overall purpose of routine, relevant details

2019-12-19 15:14 UTC, bmcdanie commented on src/kron.hpp
> +  for (; iter != matrix.rend(); ++iter)
let's improve readability and add comments throughout this routine

2019-12-19 15:14 UTC, bmcdanie commented on src/kron.hpp
> +    batch<P, resrc> left(n_gemms, stride, iter->ncols(), stride, false);
rather than creating these and then moving them into the batch set, why doesn't the batch set handle construction here, and then simply initialize the objects there in place?

2019-12-19 15:14 UTC, bmcdanie commented on src/kron_tests.cpp
> +TEMPLATE_TEST_CASE("kron", "[kron]", double, float)
even in tests, let's use const correctness

2019-12-19 15:14 UTC, bmcdanie commented on src/kron_tests.cpp
> +    const std::vector<fk::matrix<TestType, mem_type::view, resource::device>>
east const

2019-12-19 15:14 UTC, bmcdanie commented on src/kron_tests.cpp
> +    auto m0 = matrix_all_twos(3, 4);
const correctness throughout

2019-12-19 15:14 UTC, bmcdanie commented on src/kron_tests.cpp
> +      for (int i = 0; i < rows; ++i)
or: for (auto & elem : matrix) { elem = 2 };

2019-12-19 15:14 UTC, bmcdanie commented on src/kron_tests.cpp
> +  SECTION("kron_2")
for testability let's make a kron test function that accepts matrices/vector to kron and performs the common operations. in these test cases, just init the matrices.

2019-12-19 15:14 UTC, bmcdanie commented on src/kron_tests.cpp
> +TEMPLATE_TEST_CASE("kron", "[kron]", double, float)
if these functions work on device or host, need to cross product template these tests.

2019-12-19 15:14 UTC, bmcdanie commented on src/transformations.cpp
> +  std::vector<batch_job<P, resource::host>> bjs;
no problem with this routine overall. of course, our final (scalable) version needs to overlap much better with the workspace allocations we are already making. additionally, we don't want to perform these allocations every time step.

2019-12-19 15:14 UTC, bmcdanie commented on src/transformations.cpp
>    return real_space;
tests?

2019-12-19 15:43 UTC, bmcdanie commented on src/transformations.cpp
>    return real_space;
probably reusing the old tests?

2019-12-30 16:34 UTC, stonecoldhughes commented on src/transformations.cpp
>    return real_space;
Yes, I'm using the old tests for these.

2019-12-30 17:26 UTC, stonecoldhughes commented on src/kron.hpp
> +    batch<P, resrc> left(n_gemms, stride, iter->ncols(), stride, false);
I did this to maintain a flattened design while still getting the data-organizational benefit of a class. The batch_set object's purpose is simply to bundle together 3 batches. Inserting them into the class and then reaching down into the class later to initialize them makes it more hierarchical and I was trying to avoid that at all costs in this file.

2019-12-30 17:39 UTC, stonecoldhughes commented on src/kron.hpp
> +    init_w0 = x;
I am making a copy here. The source is fk::vector view "x" and the destination is fk::vector owner workspace[ 0 ]. The destination vector may be longer than the source, so to copy I use this correctly sized intermediate view variable.

2019-12-30 17:49 UTC, stonecoldhughes commented on src/kron.hpp
> +  fk::vector<P, mem_type::owner, resrc> const &get_input_workspace()
Because a physical vector labeled "in" would not always the input vector and the other physical one labeled "out" would not always be the output vector. They switch roles many times. This function frees the programmer to deal with logical "input" and "output" without worrying about which physical object "input" or "output" refers to on any given iteration.

2019-12-30 17:53 UTC, stonecoldhughes commented on src/kron.hpp
> +fk::vector<P, mem_type::owner, resrc> execute_batch_job(batch_job<P, resrc> &bj)
this should disappear in the final scalable version.

2019-12-30 17:59 UTC, bmcdanie commented on src/kron.hpp
> +  fk::vector<P, mem_type::owner, resrc> const &get_input_workspace()
but you aren't actually doing the work for the progammer - the progammer is still determining which is in and which is out, just through publicly accessible ints with no bounds checking.

if we want to provide this abstraction so the programmer doesn't have to worry about it, you could have these functions ingest the current dimension number and return the appropriate workspace.

2019-12-30 18:36 UTC, stonecoldhughes commented on src/kron.hpp
> +  batch<P, resrc> left;
yes, the entire purpose is to name the three batches

2019-12-30 18:51 UTC, stonecoldhughes commented on src/transformations.cpp
>    return real_space;
yes, I am using the old tests. They just tested correct input/output of kron products so nothing needed to be changed.

2019-12-30 18:53 UTC, stonecoldhughes commented on src/transformations.cpp
> +  std::vector<batch_job<P, resource::host>> bjs;
the final scalable version will not have allocations like this and will overlap better

2019-12-31 15:40 UTC, bmcdanie commented on src/kron.hpp
> +  {
members should have a single responsibility - this function adds a batch set, but also swaps the input and output spaces. this makes the function less flexible, tying which storage areas I'm using for in/out with the order I am placing batches. 

also, if you intend for in/out to be managed exclusively within the class, they should be private members.

2020-01-02 20:44 UTC, stonecoldhughes commented on src/kron.cpp
> +#include "kron.hpp"
done

2020-01-02 20:48 UTC, stonecoldhughes commented on src/kron.hpp
> +  batch_job(batch_job<P, resrc> &&bj)
I do not think it's possible to use the default move constructor here.

2020-01-02 20:50 UTC, stonecoldhughes commented on src/kron.hpp
> +  batch_set(batch<P, resrc> &&bs)
the compiler claims that this function can't be defaulted

2020-01-02 21:13 UTC, bmcdanie commented on src/kron.hpp
> +  batch_set(batch<P, resrc> &&bs)
that's because this isn't a move constructor - the argument isn't of same type.

I thought this was a move constructor - despite the rhs being named `bs`. is this intended to be a move constructor?

2020-01-02 21:14 UTC, bmcdanie commented on src/kron.hpp
> +  batch_job(batch_job<P, resrc> &&bj)
why?

2020-01-02 21:15 UTC, bmcdanie commented on src/kron.hpp
> +  batch_set(batch<P, resrc> &&bs)
is this ever invoked?

2020-01-02 21:16 UTC, bmcdanie commented on src/kron.hpp
> +  batch_job(batch_job<P, resrc> &&bj)
```
batch_job(batch_job<P, resrc> const &) = default;
batch_job(batch_job<P, resrc> &&bj) = default;
```

2020-01-02 21:27 UTC, bmcdanie commented on src/kron.hpp
> +    batch<P, resrc> left(n_gemms, stride, iter->ncols(), stride, false);
this pattern seems inconsistent with RAII?

it isn't a problem for a class to manage its members.

2020-01-02 23:49 UTC, stonecoldhughes commented on src/kron.hpp
> +  for (iter = matrix.rbegin(); iter != matrix.rend(); ++iter)
asserts and extensive comments added

2020-01-02 23:52 UTC, stonecoldhughes commented on src/kron.hpp
> +class batch_job
I think it could be, but there is a clear separation of tasks between the two and keeping them separate aligns with their separate purposes.

2020-01-02 23:56 UTC, stonecoldhughes commented on src/kron.hpp
> +  void add_batch_set(batch_set<P, resrc> &&bs)
The final destination for a batch_set object is a container within batch_job. It is not used or needed anywhere else, and any reference to it is only useful for getting it there. This being the case, I wanted to minimize copies. Move semantics does those things.

2020-01-03 00:09 UTC, bmcdanie commented on src/kron.hpp
> +  void add_batch_set(batch_set<P, resrc> &&bs)
That to me says that batch_set should be a member of batch_job, rather than constructed externally and moved into place. The batch_job should be in a valid state when constructed unless we've knowingly decided to violate RAII for solid reasons. In that case, we'd want to document that we know we are and why because it's a red flag to anyone reading the code.

At any rate, functions with rvalue ref arguments outside of move constructors are potential bug sources - we need to clearly indicate in the name that we are taking ownership.

2020-01-03 00:13 UTC, stonecoldhughes commented on src/kron.hpp
> +  std::vector<batch_set<P, resrc>> batches;
They either have to be public or I need to add getter functions for each one. Making them public seemed less bloated. I was able to make some of them const.

2020-01-03 00:16 UTC, stonecoldhughes commented on src/kron.hpp
> +fk::vector<P, mem_type::owner, resrc> execute_batch_job(batch_job<P, resrc> &bj)
No, it actually calls batched_gemm underneath

2020-01-03 00:22 UTC, stonecoldhughes commented on src/kron.hpp
> +kron_batch(std::vector<fk::matrix<P, mem_type::view, resrc>> const &matrix,
done

2020-01-03 00:22 UTC, stonecoldhughes commented on src/kron.hpp
> +  for (; iter != matrix.rend(); ++iter)
done

2020-01-03 00:24 UTC, bmcdanie commented on src/kron.hpp
> +  std::vector<batch_set<P, resrc>> batches;
Needing a one line getter isn't bloat - least privilege is worth it

2020-01-03 00:40 UTC, stonecoldhughes commented on src/kron.hpp
> +  fk::vector<P, mem_type::owner, resrc> const &get_input_workspace()
The programmer never accesses "in" or "out" directly anywhere, so I went ahead and made them private. I don't understand your statement 

> the progammer is still determining which is in and which is out, just through publicly accessible ints with no bounds checking

The member variables "in" and "out" are not accessed anywhere outside of the class.

2020-01-03 01:27 UTC, stonecoldhughes commented on src/kron.hpp
> +  {
I made in/out private members and moved the functionality to swap the spaces into a different member function called after each batch_set is added to the batch_job

2020-01-03 02:05 UTC, stonecoldhughes commented on src/kron.hpp
> +    batch<P, resrc> left(n_gemms, stride, iter->ncols(), stride, false);
done

2020-01-03 03:16 UTC, stonecoldhughes commented on src/kron_tests.cpp
> +TEMPLATE_TEST_CASE("kron", "[kron]", double, float)
done

2020-01-03 03:16 UTC, stonecoldhughes commented on src/kron_tests.cpp
> +TEMPLATE_TEST_CASE("kron", "[kron]", double, float)
done

2020-01-03 03:16 UTC, stonecoldhughes commented on src/kron_tests.cpp
> +    const std::vector<fk::matrix<TestType, mem_type::view, resource::device>>
done

2020-01-03 03:16 UTC, stonecoldhughes commented on src/kron_tests.cpp
> +    auto m0 = matrix_all_twos(3, 4);
done

2020-01-03 03:18 UTC, stonecoldhughes commented on src/kron_tests.cpp
> +      for (int i = 0; i < rows; ++i)
done

2020-01-03 03:22 UTC, stonecoldhughes commented on src/kron_tests.cpp
> +  SECTION("kron_2")
The bulk of all these test cases is initializing the matrices, vector, and correct result. The only common operations across the test cases are the two function calls `kron_batch()` and `execute_batch_job()` which by itself doesn't seem worth it. I'm not sure what else I could really offload to a function here.

2020-01-03 04:11 UTC, stonecoldhughes commented on src/transformations.cpp
> +  std::vector<batch_job<P, resource::host>> bjs;
Removed the allocation at every timestep. Full integration with existing infrastructure is not possible until a scalable algorithm for the realspace transform is implemented.

2020-01-03 06:56 UTC, bmcdanie commented on src/kron_tests.cpp
> +  SECTION("kron_2")
Well obviously you'd have to increase the share of common code. But, these are still edge cases, and if you prefer them this way I'd say it's fine. Trimming 5k+ lines of test code a couple weeks ago has me a little paranoid about test bloat.

But, on second look, definitely take out the bit shifting and add a comment about why this is the correct answer. Let's be as clear and straightforward as possible about what we are doing unless we have a really good reason not to be.

2020-01-03 16:40 UTC, stonecoldhughes commented on src/kron.hpp
> +  batch_job(batch_job<P, resrc> &&bj)
done

2020-01-03 16:43 UTC, stonecoldhughes commented on src/kron.hpp
> +  batch_set(batch<P, resrc> &&bs)
well when I deleted it, everything still compiled and ran so I supposed not...

2020-01-16 15:27 UTC, bmcdanie requested changes
fix these minor notes and let's get this merged in please

2020-01-16 15:27 UTC, bmcdanie commented on CMakeLists.txt
> +  quadrature tensors batch)
minor note - place in alpha order

2020-01-16 15:27 UTC, bmcdanie commented on src/batch.cpp
> +    int const tmp = in;
in future consider `std::swap`

2020-01-16 15:27 UTC, bmcdanie commented on src/batch.cpp
>  // object to store lists of operands for batched gemm/gemv.
what is this comment related to?

2020-01-16 15:27 UTC, bmcdanie commented on src/main.cpp
> +  int prod = real_solution_size(*pde);
const and/or roll into below function call

2020-01-16 15:27 UTC, bmcdanie commented on src/transformations.cpp
> +    prod *= (dims[i].get_degree() * std::pow(2, dims[i].get_level()));
in future consider std::accumulate

2020-01-16 15:27 UTC, bmcdanie commented on src/batch.hpp
> +/* external explicit instantiations */
these are not instantiations - in fact, they prevent instantiations.

https://isocpp.org/wiki/faq/cpp11-language-templates#extern-templates

2020-01-16 15:27 UTC, bmcdanie commented on src/batch.cpp
> +  int in  = 0;
put a comment about what these are here at the declaration site

2020-01-16 15:27 UTC, bmcdanie commented on src/batch.cpp
> +  assert(workspace[0].size() >= workspace_len);
should probably assert `workspace.size() == 2`

2020-01-16 21:26 UTC, stonecoldhughes commented on src/batch.cpp
> +    int const tmp = in;
I like that

2020-01-16 21:30 UTC, stonecoldhughes commented on src/batch.hpp
> +/* external explicit instantiations */
They do prevent implicit instantiations. Since I define the class template's functions outside of the .hpp where it's declared, I already would not be getting implicit instantiations right?

2020-01-17 03:00 UTC, bmcdanie commented on src/batch.hpp
> +/* external explicit instantiations */
Yes, that's my theory. The compiler doesn't have the information necessary to instantiate them in other translation units. I believe we could strip the externs out, although we would still need the explicit instantiations in the cpp. At some point I am going to look into that.

2020-01-21 15:24 UTC, bmcdanie commented on CMakeLists.txt
> +  quadrature tensors batch)
@stonecoldhughes place to in alpha order

2020-01-21 15:57 UTC, stonecoldhughes commented on CMakeLists.txt
> +  quadrature tensors batch)
done

2020-01-21 15:58 UTC, stonecoldhughes commented on src/batch.cpp
>  // object to store lists of operands for batched gemm/gemv.
vestigial comment removed

2020-01-21 15:59 UTC, stonecoldhughes commented on src/main.cpp
> +  int prod = real_solution_size(*pde);
done

2020-01-21 16:06 UTC, stonecoldhughes commented on src/batch.cpp
> +  assert(workspace[0].size() >= workspace_len);
done up above as the 2nd check

2020-01-21 16:08 UTC, stonecoldhughes commented on src/batch.cpp
> +  int in  = 0;
done

2020-01-21 16:59 UTC, stonecoldhughes commented on src/kron_tests.cpp
> +  SECTION("kron_2")
done

2020-01-28 15:52 UTC, grahamlopez commented on src/batch.cpp
> +int calculate_workspace_len(
it's a long name already (I approve); let's just take `_len`-->`_length`

2020-01-28 15:52 UTC, grahamlopez commented on src/batch.cpp
> +/*
very nice comment; thank you!

2020-01-28 15:52 UTC, grahamlopez commented on src/batch.cpp
> +    std::vector<fk::matrix<P, mem_type::view, resrc>> const &matrix,
`matrix` --> `matrices`?
(a `std::vector<>` is not a matrix in this case)

2020-01-28 15:52 UTC, grahamlopez commented on src/batch.cpp
> +/* explicit instantions of function above */
previous convention has been to group these at the bottom of the file

2020-01-28 15:52 UTC, grahamlopez commented on src/main.cpp
> +    /* transform from wave space to real space */
s/wave/wavelet

2020-01-28 17:27 UTC, stonecoldhughes commented on src/batch.cpp
> +int calculate_workspace_len(
name extended

2020-01-28 17:28 UTC, stonecoldhughes commented on src/batch.cpp
> +/*
gone

2020-01-28 17:30 UTC, bmcdanie commented
test this please

2020-01-28 18:03 UTC, stonecoldhughes commented on src/batch.cpp
> +/* explicit instantions of function above */
done

2020-01-28 18:06 UTC, stonecoldhughes commented on src/main.cpp
> +    /* transform from wave space to real space */
changed

2020-01-28 18:06 UTC, stonecoldhughes commented on src/batch.cpp
> +    std::vector<fk::matrix<P, mem_type::view, resrc>> const &matrix,
done

2020-01-30 18:19 UTC, bmcdanie approved these changes

2020-03-10 16:34 UTC, merged