fix issue #126
project-asgard/asgard pull request #229
Opened 2020-01-15 23:42 UTC by stonecoldhughes

2020-01-16 14:21 UTC, grahamlopez commented
Please make the title of pull requests say what they do, and if they are fixing an issue, include that in the description (which should also expand on the PR title).

2020-01-16 15:07 UTC, bmcdanie reviewed
+67/-18 is not a great net for a DRY'ing out PR. hmm...

may need to rethink changing this, or have the pass in the function arrays (`source.source_funcs[i]`, for instance) so that we can extract more of the shared code. I'm in CASL today if you want to discuss.

2020-01-16 16:41 UTC, bmcdanie commented
actually, it looks like the PDE holds these functions in vectors already - is it redundant to repackage them? they can probably be passed straight in.

2020-01-16 16:46 UTC, bmcdanie commented
example:

```  
  121   // -- generate source vectors.
  122   // these will be scaled later according to the simulation time applied
  123   // with their own time-scaling functions
  124   node_out() << "  generating: source vectors..." << '\n';
  125   std::vector<fk::vector<prec>> const initial_sources = [&pde, &table, &subgrid,
  126                                                          degree]() {
  127     std::vector<fk::vector<prec>> initial_sources;
  128     for (source<prec> const &source : pde->sources)
  129     {
  130       initial_sources.push_back(transform_and_combine_dimensions(
  131           *pde, source.source_funcs, table, subgrid.row_start, subgrid.row_stop,
  132           degree));
  133     }
  134     return initial_sources;
  135   }();
```

2020-01-16 16:50 UTC, bmcdanie requested changes
add these few items and let's get a simple test for this in transformations tests since it's a public function.

2020-01-16 16:50 UTC, bmcdanie commented on src/transformations.hpp
> +transform_and_combine_dimensions(PDE<P> const &pde,
let's accept the functions by const ref and const the int args here

2020-01-16 16:50 UTC, bmcdanie commented on src/main.cpp
> +    std::vector<vector_func<prec>> v_functions;
trim this unnecessary step if possible, see my example

2020-01-16 16:50 UTC, bmcdanie commented on src/transformations.cpp
> +  std::vector<fk::vector<P>> dimension_components;
assert stop and start >= 0, stop >= start, degree  > 0, etc.

2020-01-16 16:50 UTC, bmcdanie commented on src/transformations.cpp
> +  std::vector<fk::vector<P>> dimension_components;
also that the v_functions match num pde dims

2020-01-28 18:16 UTC, stonecoldhughes commented on src/transformations.hpp
> +transform_and_combine_dimensions(PDE<P> const &pde,
done

2020-01-28 18:21 UTC, stonecoldhughes commented on src/transformations.cpp
> +  std::vector<fk::vector<P>> dimension_components;
done

2020-01-30 18:23 UTC, bmcdanie commented on src/main.cpp
> +    std::vector<vector_func<prec>> v_functions;
can't, because no vector of functions directly available here as in the source case. need to consider in pde spec rewrite.

2020-01-30 18:23 UTC, bmcdanie approved these changes
thanks.

2020-03-05 14:25 UTC, merged