WIP: Feature/distributed gmres
project-asgard/asgard pull request #246
Opened 2020-02-21 17:41 UTC by bmcdanie

Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

1) add simple iterative solver that works locally with constructed matrix.
2) add distributed iterative solver that works across nodes with matrix shell (GEMV)

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [ ] Bugfix
- [X ] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [X ] No

## What systems has this change been tested on?

None yet

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [ ] this PR is up to date with current the current state of 'develop'
- [X] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

2020-03-19 21:53 UTC, stonecoldhughes approved these changes
send it

2020-03-20 00:10 UTC, stonecoldhughes submitted a review, later dismissed
disapproved

2020-03-20 22:26 UTC, stonecoldhughes requested changes

2020-03-20 22:26 UTC, stonecoldhughes commented on src/solver.cpp
> +        krylov_proj.print("krylov");
don't forget to take out the debug prints in the final version

2020-03-20 22:31 UTC, bmcdanie commented on src/solver.cpp
> +        krylov_proj.print("krylov");
good catch, done

2020-03-20 22:50 UTC, merged