WIP: Feature/boundary conditions
project-asgard/asgard pull request #259
Opened 2020-03-10 23:31 UTC by stonecoldhughes

Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

Describe what this PR changes and why.  If it closes an issue, link to it here
with [a supported keyword](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [ ] Bugfix
- [ ] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## What systems has this change been tested on?

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [ ] this PR is up to date with current the current state of 'develop'
- [ ] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

2020-03-12 15:13 UTC, bmcdanie commented
test this please

2020-03-21 16:40 UTC, bmcdanie requested changes
good work.

major point - let's not have another class here that must be passed into time advance. these functions require no shared state (beyond the vectors) and we can place those in the `host_workspace`.

so, please refactor to two free functions in a namespace - something like `generate` and `scale`/`scale_at_time`. advance is a little vague.

core of functions look pretty good, made some syntax nitpicks/suggestions here and there, but the above is the main point.

2020-03-21 16:40 UTC, bmcdanie commented on CMakeLists.txt
> +add_compile_options ("-Wall" "-Wextra" "-Wpedantic" "-O3")
give my flag back

2020-03-21 16:40 UTC, bmcdanie commented on src/boundary_conditions.hpp
> +class bc_timestepper
no state between functions - can we restructure to free functions in a component namespace?

2020-03-21 16:40 UTC, bmcdanie commented on src/boundary_conditions.cpp
> +bc_timestepper<P>::bc_timestepper(PDE<P> const &pde, element_table const &table,
please leave brief comment on the two major functions re: input/outputs and general purpose

2020-03-21 16:40 UTC, bmcdanie commented on src/boundary_conditions.cpp
> +              p_num, std::move(trace_bc));
why move here?

2020-03-21 16:40 UTC, bmcdanie commented on src/boundary_conditions.cpp
> +
lets add some asserts, e.g. on stop/start element

2020-03-21 16:40 UTC, bmcdanie commented on src/boundary_conditions_tests.cpp
> +  /* Open the file and feed params to compute_boundary_conditions */
open what file?

2020-03-21 16:40 UTC, bmcdanie commented on src/boundary_conditions_tests.cpp
> +                                    std::string gold_filename_prefix,
std::string const

2020-03-21 16:40 UTC, bmcdanie commented on src/boundary_conditions_tests.cpp
> +TEMPLATE_TEST_CASE("problem separability", "", double, float)
for all these, the second string here should be component name in brackets `[boundary_condition]`

2020-03-21 16:40 UTC, bmcdanie commented on src/boundary_conditions_tests.cpp
> +    if constexpr (std::is_same<TestType, float>::value == true)
don't do `boolean==true`, just `if constexpr(std::is_same<TestType,float>::value)`

also, let's call these `eps_scale` or `tol_factor` - not epsilon. epsilon means something else.

2020-03-21 16:40 UTC, bmcdanie commented on src/boundary_conditions_tests.cpp
> +    if constexpr (std::is_same<TestType, float>::value == true)
also, pull them out to the `TEMPLATE_TEST_CASE` level if they're consistent across sections.

small nitpick, just trying to keep tests concise

2020-03-21 16:40 UTC, bmcdanie commented on src/pde/pde_base.hpp
> +   whether to use later */
what do you mean here?

2020-03-21 16:40 UTC, bmcdanie commented on src/time_advance.cpp
> +  /* the call below calculates "source1" from matlab - line 32 time_advance.m */
good to tie these together, but this comment is unlikely to age well - when referencing the other codebase, drop a permalink

2020-03-21 16:40 UTC, bmcdanie commented on src/time_advance.cpp
> +  /* end new code */
remove

2020-03-21 16:40 UTC, bmcdanie commented on src/time_advance.cpp
> +  /* result_1 is k1, result_2 is k2 */
flesh out these comments or remove them

2020-03-21 16:40 UTC, bmcdanie commented on src/time_advance.cpp
> +  fk::vector<P> bc0 = bc_generator.advance(time);
const?

2020-03-21 16:40 UTC, bmcdanie commented on src/pde/pde_base.hpp
> +  homogeneity const left_homo;
are there conditions on these, e.g. should we always have bc functions if we have inhomog boundary conditions? if we can check these for correctness with asserts in pde base class constructor, we should

2020-03-21 16:40 UTC, bmcdanie commented on src/pde.hpp
> +    {"diffusion_1", PDE_opts::diffusion_1},
no mapping for diffusion_2?

2020-03-21 16:40 UTC, bmcdanie commented on src/coefficients_tests.cpp
> +  TestType const eps_multiplier = 1e2;
why?

2020-03-21 16:40 UTC, bmcdanie commented on src/coefficients_tests.cpp
> +    if constexpr (std::is_same<TestType, float>::value == true)
see other comment about not calling these epsilon.

also, can we compress? trying to keep test code concise.

`TestType epsilon = std::is_same<TestType, float>::value ? 1e3 : 1e3;`

2020-03-21 16:40 UTC, bmcdanie commented on src/time_advance_tests.cpp
> +                       double const eps_multiplier                     = 3e6)
this should probably be changed back - you adjusted the default tolerance other tests are using, but it looks like you're passing a tolerance for your new pdes?

2020-03-21 16:40 UTC, bmcdanie commented on src/transformations.cpp
> +
well ok I suppose

2020-03-21 16:40 UTC, bmcdanie commented on src/boundary_conditions.cpp
> +fk::vector<P> bc_timestepper<P>::compute_right_boundary_condition(
can we merge this function with the one beneath? 

at quick glance, they only differ in one or two lines.

2020-03-21 16:40 UTC, bmcdanie commented on src/boundary_conditions.hpp
> +  void print_left() const;
do we still need these?

2020-03-21 17:47 UTC, stonecoldhughes commented on CMakeLists.txt
> +add_compile_options ("-Wall" "-Wextra" "-Wpedantic" "-O3")
*red team has acquired the flag*

2020-03-21 17:48 UTC, stonecoldhughes commented on src/boundary_conditions.hpp
> +class bc_timestepper
aye aye

2020-03-21 18:10 UTC, stonecoldhughes commented on src/boundary_conditions.cpp
> +bc_timestepper<P>::bc_timestepper(PDE<P> const &pde, element_table const &table,
commented

2020-03-21 18:19 UTC, stonecoldhughes commented on src/boundary_conditions.cpp
> +              p_num, std::move(trace_bc));
That function returns a container of `fk::vector` and `trace_bc` will be somewhere in that container - where depends on loop iteration variables.

2020-03-21 18:23 UTC, stonecoldhughes commented on src/boundary_conditions.cpp
> +
done

2020-03-21 18:26 UTC, stonecoldhughes commented on src/boundary_conditions_tests.cpp
> +  /* Open the file and feed params to compute_boundary_conditions */
extraneous comment removed

2020-03-21 18:27 UTC, stonecoldhughes commented on src/boundary_conditions_tests.cpp
> +                                    std::string gold_filename_prefix,
std::string const &

2020-03-21 18:28 UTC, stonecoldhughes commented on src/boundary_conditions_tests.cpp
> +TEMPLATE_TEST_CASE("problem separability", "", double, float)
done

2020-03-21 18:29 UTC, bmcdanie commented on src/boundary_conditions_tests.cpp
> +                                    std::string gold_filename_prefix,
even better

2020-03-21 18:35 UTC, stonecoldhughes commented on src/boundary_conditions_tests.cpp
> +    if constexpr (std::is_same<TestType, float>::value == true)
done

2020-03-21 18:42 UTC, bmcdanie commented on src/boundary_conditions.cpp
> +    g_func_type const g_func, P const time, int level, int degree,
int const level, int const degree

2020-03-21 18:57 UTC, bmcdanie commented on src/boundary_conditions.cpp
> +              p_term.g_func, t_init, d.get_level(), d.get_degree(),
passing four `dimension` fields here - just pass the dimension as a ref

2020-03-21 18:58 UTC, bmcdanie commented on src/boundary_conditions.cpp
> +  assert(destination_slice.size() == legendre_polys_at_value.size());
this assert is extraneous - the copy below won't work if the sizes don't match

2020-03-21 19:36 UTC, stonecoldhughes commented on src/pde/pde_base.hpp
> +   whether to use later */
extraneous comment removed

2020-03-21 19:37 UTC, stonecoldhughes commented on src/time_advance.cpp
> +  /* the call below calculates "source1" from matlab - line 32 time_advance.m */
done

2020-03-21 19:37 UTC, stonecoldhughes commented on src/time_advance.cpp
> +  /* end new code */
done

2020-03-21 19:38 UTC, stonecoldhughes commented on src/time_advance.cpp
> +  /* result_1 is k1, result_2 is k2 */
done

2020-03-21 19:40 UTC, stonecoldhughes commented on src/time_advance.cpp
> +  fk::vector<P> bc0 = bc_generator.advance(time);
done

2020-03-21 19:42 UTC, stonecoldhughes commented on src/boundary_conditions.cpp
> +  assert(destination_slice.size() == legendre_polys_at_value.size());
removed

2020-03-21 19:42 UTC, stonecoldhughes commented on src/boundary_conditions.cpp
> +              p_term.g_func, t_init, d.get_level(), d.get_degree(),
done

2020-03-21 19:43 UTC, stonecoldhughes commented on src/boundary_conditions.cpp
> +    g_func_type const g_func, P const time, int level, int degree,
done

2020-03-21 19:43 UTC, stonecoldhughes commented on src/boundary_conditions.hpp
> +  void print_left() const;
removed

2020-03-21 19:45 UTC, stonecoldhughes commented on src/boundary_conditions.cpp
> +fk::vector<P> bc_timestepper<P>::compute_right_boundary_condition(
Not really - there are several small differences. To parameterize them, I would have to pull so much out of the function that it wouldn't even make sense for it to be a standalone function anymore

2020-03-21 19:47 UTC, stonecoldhughes commented on src/time_advance_tests.cpp
> +                       double const eps_multiplier                     = 3e6)
reverted

2020-03-21 20:00 UTC, stonecoldhughes commented on src/coefficients_tests.cpp
> +  TestType const eps_multiplier = 1e2;
these should all be `double` because they are passed down to `relaxed_comparison` which expects a double

2020-03-21 20:01 UTC, stonecoldhughes commented on src/coefficients_tests.cpp
> +  TestType const eps_multiplier = 1e2;
fixed

2020-03-21 20:03 UTC, stonecoldhughes commented on src/pde.hpp
> +    {"diffusion_1", PDE_opts::diffusion_1},
added

2020-03-21 20:09 UTC, stonecoldhughes commented on src/coefficients_tests.cpp
> +    if constexpr (std::is_same<TestType, float>::value == true)
done

2020-03-21 20:29 UTC, stonecoldhughes commented on src/pde/pde_base.hpp
> +  homogeneity const left_homo;
done

2020-03-23 23:32 UTC, bmcdanie commented on src/boundary_conditions.cpp
> +
can we have 

`assert(start_element > 0)`, `assert(stop_element < table.size()`, `assert(stop_element >= start_element)` ?

2020-03-23 23:38 UTC, bmcdanie requested changes

2020-03-23 23:38 UTC, bmcdanie commented on CMakeLists.txt
> +add_compile_options ("-Wall" "-Wextra" "-Wpedantic" "-O3" "-g")
ok I guess

2020-03-23 23:38 UTC, bmcdanie commented on src/boundary_conditions.cpp
> +void boundary_conditions::init_bc_parts(
for these names:

init_bc_parts ->make_unscaled_bc , generate_bc -> get_scaled_bc . or something like this. we're making these at one point and scaling them for time in another. don't have to match my words exactly but try to name them in ways that show how they interact.

2020-03-23 23:38 UTC, bmcdanie commented on src/boundary_conditions.cpp
> +    std::vector<std::vector<std::vector<fk::vector<P>>>> &left_bc_parts,
final note: instead of in/out parameters, can we create these in the function and return them by value?

first, name them something like `using unscaled_bc_parts = std::vector..std::vector...std::vector..fk::vector;`

then use an array literal/structured binding like: https://github.com/project-asgard/asgard/blob/7dca6e78fbcbb66aebebc1b940f7245fef2de36b/src/quadrature.cpp#L134. to return them both.

2020-03-23 23:38 UTC, bmcdanie commented on src/boundary_conditions.cpp
> +    std::vector<std::vector<std::vector<fk::vector<P>>>> &left_bc_parts,
I'm going to change these in the batch refactor to map pterms directly to fk::vectors because this nested structure is confusing, but just put in the using for now.

2020-03-23 23:43 UTC, stonecoldhughes commented on src/boundary_conditions.cpp
> +
done

2020-03-24 00:01 UTC, stonecoldhughes commented on src/boundary_conditions.cpp
> +void boundary_conditions::init_bc_parts(
done

2020-03-24 01:08 UTC, stonecoldhughes commented on src/boundary_conditions.cpp
> +    std::vector<std::vector<std::vector<fk::vector<P>>>> &left_bc_parts,
done

2020-03-24 13:56 UTC, bmcdanie approved these changes

2020-03-24 13:56 UTC, merged