WIP: Implemented normalized norm of difference for tensors.
project-asgard/asgard pull request #262
Opened 2020-03-20 05:32 UTC by stonecoldhughes

Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

Describe what this PR changes and why.  If it closes an issue, link to it here
with [a supported keyword](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [ ] Bugfix
- [ ] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## What systems has this change been tested on?

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [ ] this PR is up to date with current the current state of 'develop'
- [ ] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

2020-03-21 16:49 UTC, bmcdanie commented on contrib/contrib.cmake
> +    ${CMAKE_SOURCE_DIR}
what happened here?

2020-03-24 15:27 UTC, stonecoldhughes commented on contrib/contrib.cmake
> +    ${CMAKE_SOURCE_DIR}
there were 3 `#include`s in tests_general.hpp that were using relative file paths to include things in asgard/src. That really bothered me so I added this so we didn't have to `#include <../src/blah.hpp>`

2020-03-26 18:26 UTC, bmcdanie requested changes
just need to trim up a bit and track down what's going on with the very large tolerance problems. thanks for getting this in @stonecoldhughes .

2020-03-26 18:26 UTC, bmcdanie commented on src/basis_tests.cpp
> +  P tol_factor = -1;
please rework these as in prior PR. this is five lines repeatedly in every test file where one will work.

2020-03-26 18:26 UTC, bmcdanie commented on testing/generated-inputs/coefficients/continuity1/coefficients_l2_d2_1_1.dat
> +# Created from matlab git hash a944232bfb84b40fdc4f51b96924944d4152bba2
? why are we updating this one?

2020-03-26 18:26 UTC, bmcdanie commented on src/time_advance_tests.cpp
> +                       P const tol_factor                              = 1e4)
this is likely no longer a useful default

2020-03-26 18:26 UTC, bmcdanie commented on src/time_advance_tests.cpp
> +      tol_factor = 1;
ouch, as we discussed need to look into this

2020-03-26 18:26 UTC, bmcdanie commented on src/time_advance_tests.cpp
> +      tol_factor = 1;
we should replace these as we do all the other five-liners with the one line version.

but, for the record, if(boolean == true) is an antipattern, there is no reason for ==true to exist here.

2020-04-01 05:35 UTC, stonecoldhughes commented on testing/generated-inputs/coefficients/continuity1/coefficients_l2_d2_1_1.dat
> +# Created from matlab git hash a944232bfb84b40fdc4f51b96924944d4152bba2
In gold_coefficients.m, I was adding code to generate gold data for coefficients for the new diffusion PDEs. I needed to generate some coefficients for the continuity1 PDE for testing purposes. The existing code in gold_coefficients.m didn't work because check_pde() crashes and that's what the original code relied on. So I moved it into my function. In the end, it should be the same data but with a new hash.

2020-04-01 05:36 UTC, stonecoldhughes commented on src/time_advance_tests.cpp
> +                       P const tol_factor                              = 1e4)
I should hope so...

2020-04-01 05:36 UTC, stonecoldhughes commented on src/time_advance_tests.cpp
> +      tol_factor = 1;
done

2020-04-01 19:47 UTC, stonecoldhughes commented on src/time_advance_tests.cpp
> +      tol_factor = 1;
done

2020-04-01 19:48 UTC, stonecoldhughes commented on src/time_advance_tests.cpp
> +      tol_factor = 1;
done

2020-04-01 19:48 UTC, stonecoldhughes commented on src/time_advance_tests.cpp
> +                       P const tol_factor                              = 1e4)
changed

2020-04-01 19:48 UTC, stonecoldhughes commented on src/basis_tests.cpp
> +  P tol_factor = -1;
done

2020-04-01 19:50 UTC, stonecoldhughes commented on testing/generated-inputs/coefficients/continuity1/coefficients_l2_d2_1_1.dat
> +# Created from matlab git hash a944232bfb84b40fdc4f51b96924944d4152bba2
I needed to run that test with some different arguments to get a bearing on what rational results looked like. The only thing different should be the commit hash.

2020-04-02 16:44 UTC, bmcdanie commented
@stonecoldhughes please review CI failures

2020-04-06 21:17 UTC, bmcdanie requested changes
I'm good with this overall. Two quick fixes:

1) put the openmp pragma/include back into batched gemm.

2) rename `norm_diff_normalized` since that isn't what we're doing. we can go either with something very general, e.g. `relaxed_compare` or something more descriptive, e.g. `rmse_test`

2020-04-06 21:17 UTC, bmcdanie commented on src/lib_dispatch.cpp
please put this back

2020-04-06 21:17 UTC, bmcdanie commented on src/lib_dispatch.cpp
> -  int end = *num_batch;
also put this back

2020-04-06 21:17 UTC, bmcdanie commented on src/time_advance_tests.cpp
> +  /* FIXME - these tolerances are way too high. Different parameters are likely
great thanks

2020-04-09 22:04 UTC, bmcdanie commented
replaced by #274

2020-04-09 22:04 UTC, closed without merging