Address PR #223
project-asgard/asgard pull request #268
Opened 2020-04-01 21:55 UTC by stonecoldhughes

Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

Describe what this PR changes and why.  If it closes an issue, link to it here
with [a supported keyword](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [ ] Bugfix
- [ ] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## What systems has this change been tested on?

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [ ] this PR is up to date with current the current state of 'develop'
- [ ] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

2020-04-02 16:44 UTC, bmcdanie commented
@stonecoldhughes please review CI failures.

also, name PRs for what they're doing (e.g. extend multiwavelet testing) with a little more detail in the description. finally, put closes #[issue_num] in the description so that the issue will be linked and automatically closed.

2020-04-14 13:43 UTC, bmcdanie approved these changes
ready to go - be sure to rebase on RMSE/develop so that we can get the extern template declarations out of lib dispatch.

2020-04-14 13:43 UTC, bmcdanie commented on src/basis_tests.cpp
> +  /* Captain! Add new tests here. How high should we go? */
remove comment

2020-04-14 13:43 UTC, bmcdanie commented on src/batch_tests.cpp
>      // we use random vals for tests - multiply eps by this amount
pls remove this old comment

2020-04-14 13:43 UTC, bmcdanie commented on src/boundary_conditions_tests.cpp
>  void test_boundary_condition_vector(PDE<P> &pde,
is this meant to be in this one?

2020-04-14 13:43 UTC, bmcdanie commented on src/boundary_conditions_tests.cpp
>  void test_boundary_condition_vector(PDE<P> &pde,
ah I see this PR depends on your prior.

please include this in the PR description

2020-04-14 13:43 UTC, bmcdanie commented on src/lib_dispatch.hpp
> +extern template void
we took all the extern template declarations out of all the headers - I re-removed them from the RMSE branch, so will need to re-remove these/rebase on that.

2020-04-14 13:45 UTC, bmcdanie requested changes
please trim comment on line 84 basis tests. also rebase on RMSE or remove extern declarations from lib_dispatch that were re-introduced.

2020-04-14 15:52 UTC, stonecoldhughes commented on src/basis_tests.cpp
> +  /* Captain! Add new tests here. How high should we go? */
done

2020-04-14 15:52 UTC, stonecoldhughes commented on src/batch_tests.cpp
>      // we use random vals for tests - multiply eps by this amount
removed

2020-04-14 15:55 UTC, stonecoldhughes commented on src/boundary_conditions_tests.cpp
>  void test_boundary_condition_vector(PDE<P> &pde,
done

2020-04-14 15:55 UTC, stonecoldhughes commented on src/lib_dispatch.hpp
> +extern template void
done

2020-04-14 16:17 UTC, bmcdanie approved these changes
looks good

2020-04-14 16:17 UTC, merged