New feature: Rename pde to fit with Matlab DG-SparseGrid
project-asgard/asgard pull request #368
Opened 2021-01-18 15:40 UTC by hbrunie

## Proposed changes

This PR is here to solve [the rename pde issue#344](https://github.com/project-asgard/asgard/issues/344).
It involves adding a parameter to asgard binary.

```
  -c, --case_selection <e.g. 1 (or 2)>      PDE case to solve; default is 1,
                                            sometimes there is a second case
                                            possible.
```

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [ ] Bugfix
- [x] New feature
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

## What systems has this change been tested on?

## Checklist

- [x] this PR is up to date with current the current state of 'develop'
- [ ] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

2021-01-22 11:01 UTC, hbrunie commented
I have rebased this PR above the branch of @bmcdanie fixing the time in analytic solution generation.
Once @bmcdanie PR would have been merged to asgard/develop I will have to rebase on develop and force push again.

2021-01-25 10:02 UTC, hbrunie commented
To pass the tests `coefficients` and `time_advance`, we need the gold generated corresponding files for `fokkerplanck1_pitch_E_case2` (gaussian) from the Matlab `DG-SparseGrid` repository.

This is not implemented yet. This is the corresponding [PR] (https://github.com/project-asgard/DG-SparseGrid/pull/65) from this other repo.

2021-01-29 13:11 UTC, bmcdanie requested changes
thanks for this PR! couple of minor notes, looks great overall.

2021-01-29 13:11 UTC, bmcdanie commented on src/program_options.hpp
> +  // pde selected case (f0)
what does this comment refer to?

2021-01-29 13:11 UTC, bmcdanie commented on src/program_options.hpp
> +  static auto constexpr DEFAULT_PDE_SELECTED_CASE = 0;
can you init this with the enum value instead of an integer?

2021-01-29 13:11 UTC, bmcdanie commented on src/tensors.hpp
> +  // as with copy assignment, static expect added
I believe this is my mistake originally - should say "static assert" but my sed changes to "tools::expect", then your sed changed that to "static expect".

2021-01-29 13:11 UTC, bmcdanie commented on src/tensors.hpp
> +  // static expect added to definition
"static expect" -> "static assert"

2021-01-29 13:11 UTC, bmcdanie commented on src/pde/pde_fokkerplanck1_pitch_E.hpp
> +      if constexpr (user_case == PDE_case_opts::mod1)
we have a convention that we always use curlies around conditionals, even single line ones

2021-02-01 07:07 UTC, hbrunie commented on src/program_options.hpp
> +  // pde selected case (f0)
I forgot to remove ..

2021-02-01 07:07 UTC, hbrunie commented on src/program_options.hpp
> +  static auto constexpr DEFAULT_PDE_SELECTED_CASE = 0;
Yes.

2021-02-01 07:08 UTC, hbrunie commented on src/tensors.hpp
> +  // as with copy assignment, static expect added
OK.

2021-02-01 07:09 UTC, hbrunie commented on src/tensors.hpp
> +  // as with copy assignment, static expect added
I also changed the one line 153.

2021-02-01 07:09 UTC, hbrunie commented on src/tensors.hpp
> +  // static expect added to definition
Yes

2021-02-01 07:10 UTC, hbrunie commented on src/pde/pde_fokkerplanck1_pitch_E.hpp
> +      if constexpr (user_case == PDE_case_opts::mod1)
yes

2021-02-01 15:28 UTC, merged