Matlab interface for visualization
project-asgard/asgard pull request #375
Opened 2021-01-21 22:30 UTC by ckendrick

## Proposed changes

This PR adds the ability to use Matlab to plot simulation results when Asgard is compiled with the `ASGARD_USE_MATLAB` option.

The same plotting function (plot_fval.m) from the DG-SparseGrid repo is used, and is located in the `scripts/matlab` folder. This folder is automatically added to the Matlab session path, so any matlab source files in this directory can be executed with the `call` function.

**Note:** the matlab figure window will close immediately when asgard returns unless connected to a shared Matlab session, which can be done with the added `--matlab_name` command line argument to asgard.

WIP / things to discuss:
- [ ] finishing test cases: generate gold data from matlab to verify element coordinates, node locations.
- [ ] finding workaround/fix when shared sessions are not found due to firewall
- [ ] asynchronous plotting: will work, but should there be an option for forcing a sync every x timesteps? Is asynchronous plotting always desired, or should there be an option to switch between sync and async?
- [ ] should a plotting frequency option be added to avoid a plot for every timestep?

Closes #348

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [ ] Bugfix
- [x] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

## What systems has this change been tested on?

Ubuntu 20.04

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [x] this PR is up to date with current the current state of 'develop'
- [x] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed [WIP]
- [ ] documentation has been added (if appropriate)

2021-01-28 15:14 UTC, bmcdanie commented
@ckendrick is this WIP or ready for review?

2021-02-12 15:28 UTC, bmcdanie commented
Hi @ckendrick , can you rebase and see if these tests pass? thanks.

2021-02-16 18:59 UTC, bmcdanie requested changes, later dismissed
looks great, looks like a lot of work!

just had two or three implementation suggestions/concerns. let me know what you think!

2021-02-16 18:59 UTC, bmcdanie commented on CMakeLists.txt
> +if (ASGARD_USE_MATLAB)
I like that we isolated this specific feature in its own optional component, since it has a unique dependency.

2021-02-16 18:59 UTC, bmcdanie commented on src/matlab_plot_tests.cpp
> +  REQUIRE_NOTHROW(ml->close());
did not know about `REQUIRE_NOTHROW`, nice

2021-02-16 18:59 UTC, bmcdanie commented on src/matlab_plot_tests.cpp
> +}
minor nitpick - add newline to end of file

2021-02-16 18:59 UTC, bmcdanie commented on src/main.cpp
> +#ifdef ASGARD_USE_MATLAB
can we collapse/minimize the `_USE_MATLAB` and `_IO` sections here? I see that we want to provide the ability to turn on either one or both or none, but I'd prefer not to perform the realspace transform, etc. twice.

2021-02-16 18:59 UTC, bmcdanie commented on src/main.cpp
> +#include "boundary_conditions.hpp"
do we need this include?

2021-02-16 18:59 UTC, bmcdanie commented on src/main.cpp
> +  ml_plot.close();
can this object's destructor handle closing?

2021-02-16 18:59 UTC, bmcdanie commented on src/matlab_plot.hpp
> +      this->close();
does this make the close in main unnecessary?

2021-02-16 18:59 UTC, bmcdanie commented on src/matlab_plot.hpp
> +    // TODO: process doesn't seem to return properly when this is called
did this get resolved?

2021-02-16 18:59 UTC, bmcdanie commented on src/matlab_plot.hpp
> +
can we add a brief description of the class's API in comments here, "this class does x, the major functions are y, this is what each does"

2021-02-16 18:59 UTC, bmcdanie commented on src/main.cpp
> +  ml_plot.init_plotting(*pde, adaptive_grid.get_table());
does `init_plotting` need to be called again after adapting the grid? i.e. is the `init` different for different element tables?

2021-02-16 18:59 UTC, bmcdanie commented on src/matlab_plot.hpp
> +  fk::vector<T> generate_nodes(int const degree, int level, T min, T max)
can we add `const` correctness to these funcs where possible?

2021-02-16 18:59 UTC, bmcdanie commented on src/program_options.cpp
> +#ifdef ASGARD_USE_MATLAB
we like to restrict the conditional compilation as much as possible. instead of wrapping these functions, arguments, and options, can we instead always build with them, and print something to cerr when the functions are invoked without `USE_MATLAB` defined? this will allow us to inform the user they need to build with `USE_MATLAB` to get the functionality.

2021-02-23 15:33 UTC, ckendrick commented on src/matlab_plot.hpp
> +
I added a brief high level explanation of the class and some of the major functions. Let me know if I should expand in any areas, or if I should also make a component overview on the wiki for this.

2021-02-23 15:38 UTC, ckendrick commented on src/main.cpp
> +  ml_plot.init_plotting(*pde, adaptive_grid.get_table());
This is a good point - I'm not entirely sure.. the element coordinates probably need to be updated. Is there a good PDE test case that I can use to compare against the matlab version to check?

2021-02-23 15:39 UTC, ckendrick commented on src/matlab_plot.hpp
> +  fk::vector<T> generate_nodes(int const degree, int level, T min, T max)
Sorry about that, I added this in places it was missing, let me know if I missed a spot

2021-02-23 15:42 UTC, ckendrick commented on src/main.cpp
> +#ifdef ASGARD_USE_MATLAB
This is a good point! I tried my best to combine similar parts (like the realspace transform), but there are still some bits I wasn't able to combine. Hopefully it is a bit better now

2021-02-23 15:44 UTC, bmcdanie commented on src/matlab_plot.hpp
> +
looks good. please do add a component overview section for this, I want to finish that this week to get the JOSS submission ready

2021-02-23 15:54 UTC, bmcdanie commented on src/main.cpp
> +  ml_plot.init_plotting(*pde, adaptive_grid.get_table());
I looked, and it is likely that the coordinates will need to be updated. in this case, there is a function that is called whenever the table is adapted, to update objects dependent on it: https://github.com/ckendrick/asgard/blob/6c0fb18dd50d83535879bdda8c4b630319c25f20/src/adapt.cpp#L93. this mostly just updates the coefficients (stored in PDE class) right now.  

I suggest we update the plotting object here. that way we can be sure it is updated when the table is updated, without tracking down callsites where adaptivity is invoked.

2021-02-23 15:58 UTC, bmcdanie commented on src/main.cpp
> +  ml_plot.init_plotting(*pde, adaptive_grid.get_table());
re: how to check, you might try building with MATLAB plotting and turning that on, and then running a problem where adaptivity occurs, like `./asgard -p fokkerplanck_1d_pitch_E_case1 -l 4 -d 4 --adapt --thresh 1e-4`. 

to find the problem you'd need a PDE that adapts with plotting turned in. adaptivity alters which elements are included in the element table, so I suspect this will cause a problem.

2021-02-23 16:00 UTC, bmcdanie commented
I'm all good with this one once we get the adaptivity edge figured out

2021-02-25 13:47 UTC, bmcdanie commented
@ckendrick can we add an `ml::` or `ml_plot::` (whatever you think will work) namespace for this component? I've been putting the newer components in namespaces to try to help organize the code/show where functions/objects are defined/implemented. I can do the sed if you'd prefer, sorry I should've mentioned that earlier.

2021-03-02 18:10 UTC, dlg0 commented
I just tried to build this and hit the following build system error ...

```
(base) dlg-macbookpro3:build dg6$ cmake -DCMAKE_CXX_COMPILER=g++-10 -DASGARD_USE_MATLAB=ON ../
-- The CXX compiler identification is GNU 10.2.0
-- Checking whether CXX compiler has -isysroot
-- Checking whether CXX compiler has -isysroot - yes
-- Checking whether CXX compiler supports OSX deployment target flag
-- Checking whether CXX compiler supports OSX deployment target flag - yes
-- Check for working CXX compiler: /usr/local/bin/g++-10
-- Check for working CXX compiler: /usr/local/bin/g++-10 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'Debug' as none was specified.
-- Looking for sgemm_
-- Looking for sgemm_ - not found
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Looking for dgemm_
-- Looking for dgemm_ - found
-- Found BLAS: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Accelerate.framework
-- LINALG libraries found: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Accelerate.framework;/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Accelerate.framework
Unable to find kronmult submodule
fatal: destination path '/Users/dg6/code/asgard/contrib/kronmult' already exists and is not an empty directory.
fatal: clone of 'https://github.com/project-asgard/kronmult.git' into submodule path '/Users/dg6/code/asgard/contrib/kronmult' failed
Failed to clone 'contrib/kronmult'. Retry scheduled
fatal: destination path '/Users/dg6/code/asgard/contrib/kronmult' already exists and is not an empty directory.
fatal: clone of 'https://github.com/project-asgard/kronmult.git' into submodule path '/Users/dg6/code/asgard/contrib/kronmult' failed
Failed to clone 'contrib/kronmult' a second time, aborting
CMake Error at contrib/contrib.cmake:209 (add_subdirectory):
  The source directory

    /Users/dg6/code/asgard/contrib/kronmult

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:80 (include)


-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Found Matlab: /Applications/MATLAB_R2019a.app/extern/include (found version "9.6")
-- Configuring incomplete, errors occurred!
See also "/Users/dg6/code/asgard/build/CMakeFiles/CMakeOutput.log".
See also "/Users/dg6/code/asgard/build/CMakeFiles/CMakeError.log".
```

I'm unsure why this is showing up on this particular fork/branch? It seems to be related to building the kronmult dependency? IS this not a git submodule?

2021-03-02 18:23 UTC, ckendrick commented
I believe the way kronmult was getting built with asgard was changed. I remember running into this same problem after this branch was rebased on the latest develop branch. I think deleting (or moving/renaming) the `contrib/kronmult/` and re-compiling from scratch in a new `build/` directory should hopefully fix it.

2021-03-02 20:28 UTC, dlg0 commented
Yep, that fixed it. Building now.

2021-03-02 20:30 UTC, dlg0 commented
seems to have hit an error in the `matlab_plot_tests.cpp` ...

```
[ 49%] Built target matlab_plot
Scanning dependencies of target matlab_plot-tests
[ 49%] Building CXX object CMakeFiles/matlab_plot-tests.dir/src/matlab_plot_tests.cpp.o
In file included from /Users/dg6/code/asgard/testing/tests_general.hpp:9,
                 from /Users/dg6/code/asgard/src/matlab_plot_tests.cpp:3:
/Users/dg6/code/asgard/src/matlab_plot_tests.cpp: In instantiation of 'void ____C_A_T_C_H____T_E_M_P_L_A_T_E____T_E_S_T____F_U_N_C____8() [with TestType = float]':
/Users/dg6/code/asgard/src/matlab_plot_tests.cpp:55:1:   required from 'void {anonymous}::ns_____C_A_T_C_H____T_E_M_P_L_A_T_E____T_E_S_T____9::reg_test({anonymous}::ns_____C_A_T_C_H____T_E_M_P_L_A_T_E____T_E_S_T____9::TypeList<Type>, Catch::NameAndTags) [with Type = float]'
/Users/dg6/code/asgard/src/matlab_plot_tests.cpp:55:1:   required from '{anonymous}::ns_____C_A_T_C_H____T_E_M_P_L_A_T_E____T_E_S_T____9::____C_A_T_C_H____T_E_M_P_L_A_T_E____T_E_S_T____9<Types>::____C_A_T_C_H____T_E_M_P_L_A_T_E____T_E_S_T____9() [with Types = {{anonymous}::ns_____C_A_T_C_H____T_E_M_P_L_A_T_E____T_E_S_T____9::TypeList<float>, {anonymous}::ns_____C_A_T_C_H____T_E_M_P_L_A_T_E____T_E_S_T____9::TypeList<double>}]'
/Users/dg6/code/asgard/src/matlab_plot_tests.cpp:55:1:   required from here
/Users/dg6/code/asgard/src/matlab_plot_tests.cpp:64:51: warning: narrowing conversion of 'testvec.fk::vector<float, mem_type::owner, resource::host>::size()' from 'int' to 'long unsigned int' [-Wnarrowing]
   64 |     REQUIRE_NOTHROW(ml->add_param({1, testvec.size()}, testvec));
      |                                       ~~~~~~~~~~~~^~
/Users/dg6/code/asgard/src/matlab_plot_tests.cpp:64:51: warning: narrowing conversion of 'testvec.fk::vector<float, mem_type::owner, resource::host>::size()' from 'int' to 'long unsigned int' [-Wnarrowing]
/Users/dg6/code/asgard/src/matlab_plot_tests.cpp: In instantiation of 'void ____C_A_T_C_H____T_E_M_P_L_A_T_E____T_E_S_T____F_U_N_C____8() [with TestType = double]':
/Users/dg6/code/asgard/src/matlab_plot_tests.cpp:55:1:   required from 'void {anonymous}::ns_____C_A_T_C_H____T_E_M_P_L_A_T_E____T_E_S_T____9::reg_test({anonymous}::ns_____C_A_T_C_H____T_E_M_P_L_A_T_E____T_E_S_T____9::TypeList<Type>, Catch::NameAndTags) [with Type = double]'
/Users/dg6/code/asgard/src/matlab_plot_tests.cpp:55:1:   required from '{anonymous}::ns_____C_A_T_C_H____T_E_M_P_L_A_T_E____T_E_S_T____9::____C_A_T_C_H____T_E_M_P_L_A_T_E____T_E_S_T____9<Types>::____C_A_T_C_H____T_E_M_P_L_A_T_E____T_E_S_T____9() [with Types = {{anonymous}::ns_____C_A_T_C_H____T_E_M_P_L_A_T_E____T_E_S_T____9::TypeList<float>, {anonymous}::ns_____C_A_T_C_H____T_E_M_P_L_A_T_E____T_E_S_T____9::TypeList<double>}]'
/Users/dg6/code/asgard/src/matlab_plot_tests.cpp:55:1:   required from here
/Users/dg6/code/asgard/src/matlab_plot_tests.cpp:64:51: warning: narrowing conversion of 'testvec.fk::vector<double>::size()' from 'int' to 'long unsigned int' [-Wnarrowing]
/Users/dg6/code/asgard/src/matlab_plot_tests.cpp:64:51: warning: narrowing conversion of 'testvec.fk::vector<double>::size()' from 'int' to 'long unsigned int' [-Wnarrowing]
[ 50%] Linking CXX executable matlab_plot-tests
Undefined symbols for architecture x86_64:
  "___emutls_v._ZSt11__once_call", referenced from:
      __ZSt9call_onceIMNSt13__future_base13_State_baseV2EFvPSt8functionIFSt10unique_ptrINS0_12_Result_baseENS4_8_DeleterEEvEEPbEJPS1_S9_SA_EEvRSt9once_flagOT_DpOT0_ in matlab_plot_tests.cpp.o
      __ZSt9call_onceIMSt6threadFvvEJPS0_EEvRSt9once_flagOT_DpOT0_ in matlab_plot_tests.cpp.o
  "___emutls_v._ZSt15__once_callable", referenced from:
      __ZZSt9call_onceIMNSt13__future_base13_State_baseV2EFvPSt8functionIFSt10unique_ptrINS0_12_Result_baseENS4_8_DeleterEEvEEPbEJPS1_S9_SA_EEvRSt9once_flagOT_DpOT0_ENKUlvE0_clEv in matlab_plot_tests.cpp.o
      __ZSt9call_onceIMNSt13__future_base13_State_baseV2EFvPSt8functionIFSt10unique_ptrINS0_12_Result_baseENS4_8_DeleterEEvEEPbEJPS1_S9_SA_EEvRSt9once_flagOT_DpOT0_ in matlab_plot_tests.cpp.o
      __ZZSt9call_onceIMSt6threadFvvEJPS0_EEvRSt9once_flagOT_DpOT0_ENKUlvE0_clEv in matlab_plot_tests.cpp.o
      __ZSt9call_onceIMSt6threadFvvEJPS0_EEvRSt9once_flagOT_DpOT0_ in matlab_plot_tests.cpp.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [matlab_plot-tests] Error 1
make[1]: *** [CMakeFiles/matlab_plot-tests.dir/all] Error 2
make: *** [all] Error 2
```

2021-03-04 19:49 UTC, quantumsteve commented
ASGarD successfully connected to my shared matlab session and created a figure on my macbook 🎉 

I got the shared library error below when building against the Intel MKL. Is this worth addressing?
```
% ./asgard --matlab_name MATLAB_38142    
Branch: ckendrick-feature/cppmatlabplot
Commit Summary: f8935bc01633a8c03672e1ea2655bdac0363e80c
  Date: Thu Mar 4 10:36:09 2021 -0500
      Add namespace to matlab_plot component
This executable was built on Thursday, March 04 2021 at  2:36 P
generating: pde...
ASGarD problem configuration:
  selected PDE: continuity_2
  degree: 2
  N steps: 10
  write freq: 0
  realspace freq: 0
  implicit: 0
  full grid: 0
  CFL number: 0.01
  Poisson solve: 0
  starting levels: 2 2 
  max adaptivity levels: 8
--- begin setup ---
  generating: adaptive grid...
  degrees of freedom: 32
  generating: basis operator...
  basis operator allocation (MB): 0.03264
  generating: initial conditions...
  degrees of freedom (post initial adapt): 32
  generating: coefficient matrices...
--- begin time loop staging ---
  connecting with MATLAB session 'MATLAB_38142'
dlopen(/Applications/MATLAB_R2020b.app/bin/maci64/libmwengine_api.dylib, 10): Symbol not found: __ZNSt12length_errorD1Ev
  Referenced from: /Applications/MATLAB_R2020b.app/bin/maci64/libmwms.dylib
  Expected in: /opt/intel/oneapi/tbb/latest/env/../lib/libtbb.dylib
 in /Applications/MATLAB_R2020b.app/bin/maci64/libmwms.dylib
zsh: segmentation fault  ./asgard --matlab_name MATLAB_38142
```

2021-03-04 20:04 UTC, dlg0 commented
What the craaaaappppppp!!!!

Can you post your OSX version, matlab version, laptop year / version, etc? which compiler did you use?

2021-03-04 20:24 UTC, quantumsteve commented
macOS Catalina Version 10.15.7
matlab R2020b
MacBook Pro (Retina, 15-inch, Mid 2015)
gcc-10 and g++-10 from homebrew

2021-03-05 02:18 UTC, dlg0 commented
My only difference is that I’m using GCC 10 from spack. I’ll grab the home brew variants and see if that makes a difference - not that I expect any, but I’m at my wits end on this one.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Steven Hahn <notifications@github.com>
Sent: Thursday, March 4, 2021 3:24:43 PM
To: project-asgard/asgard <asgard@noreply.github.com>
Cc: Green, David <greendl1@ornl.gov>; Comment <comment@noreply.github.com>
Subject: [EXTERNAL] Re: [project-asgard/asgard] Matlab interface for visualization (#375)


macOS Catalina Version 10.15.7
matlab R2020b
MacBook Pro (Retina, 15-inch, Mid 2015)
gcc-10 and g++-10 from homebrew

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://github.com/project-asgard/asgard/pull/375#issuecomment-790915405>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAA2MKOU74OU5KMQBTC565LTB7UAXANCNFSM4WNTHGSA>.

2021-04-05 19:42 UTC, quantumsteve requested changes
ASGARD failed to find the running matlab session. Activity monitor shows the PID=21460

```
% ./asgard --matlab_name MATLAB_21460
Branch: ckendrick-feature/cppmatlabplot
Commit Summary: 16ef30013a58ca8d31b41439550ff5ea82610bb9
  Date: Wed Mar 31 14:47:19 2021 -0400
      Fix workspace size issue for transform with 2d adaptivity
This executable was built on Monday, April 05 2021 at  3:29 P
generating: pde...
ASGarD problem configuration:
  selected PDE: continuity_2
  degree: 2
  N steps: 10
  write freq: 0
  realspace freq: 0
  implicit: 0
  full grid: 0
  CFL number: 0.01
  Poisson solve: 0
  starting levels: 2 2 
  max adaptivity levels: 8
--- begin setup ---
  generating: adaptive grid...
  degrees of freedom: 32
  generating: basis operator...
  basis operator allocation (MB): 0.03264
  generating: initial conditions...
  degrees of freedom (post initial adapt): 32
  generating: coefficient matrices...
--- begin time loop staging ---
  connecting with MATLAB session 'MATLAB_21460'
Found no running matlab sessions..
  Specified MATLAB session 'MATLAB_21460' does not exist
Found no running matlab sessions..
  Could not find another running MATLAB session.. creating a new one
  connected to MATLAB
Warning: Contour not rendered for constant ZData
> In contourf (line 60)
In plot_fval (line 88)
--- begin time loop w/ dt 0.005 ---
--- kron workspace size ---
  coefficient size (MB): 8.38861
  solution vector allocation (MB): 0.000256
  element table allocation (MB): 0.000128
  workspace allocation (MB): 0.008192

Errors for local rank: 0
RMSE (numeric-analytic) [wavelet]: 0.00096881
Relative difference (numeric-analytic) [wavelet]: 10.2202 %
timestep: 0 complete
Errors for local rank: 0
RMSE (numeric-analytic) [wavelet]: 0.000971747
Relative difference (numeric-analytic) [wavelet]: 6.83471 %
timestep: 1 complete
Errors for local rank: 0
RMSE (numeric-analytic) [wavelet]: 0.000980399
Relative difference (numeric-analytic) [wavelet]: 5.17227 %
timestep: 2 complete
Errors for local rank: 0
RMSE (numeric-analytic) [wavelet]: 0.000999145
Relative difference (numeric-analytic) [wavelet]: 4.21757 %
timestep: 3 complete
Errors for local rank: 0
RMSE (numeric-analytic) [wavelet]: 0.00103309
Relative difference (numeric-analytic) [wavelet]: 3.63471 %
timestep: 4 complete
Errors for local rank: 0
RMSE (numeric-analytic) [wavelet]: 0.00108737
Relative difference (numeric-analytic) [wavelet]: 3.27988 %
timestep: 5 complete
Errors for local rank: 0
RMSE (numeric-analytic) [wavelet]: 0.0011664
Relative difference (numeric-analytic) [wavelet]: 3.07925 %
timestep: 6 complete
Errors for local rank: 0
RMSE (numeric-analytic) [wavelet]: 0.00127321
Relative difference (numeric-analytic) [wavelet]: 2.98859 %
timestep: 7 complete
Errors for local rank: 0
RMSE (numeric-analytic) [wavelet]: 0.0014093
Relative difference (numeric-analytic) [wavelet]: 2.97817 %
timestep: 8 complete
Errors for local rank: 0
RMSE (numeric-analytic) [wavelet]: 0.00157488
Relative difference (numeric-analytic) [wavelet]: 3.02659 %
timestep: 9 complete
--- simulation complete ---

performance report, all times in ms...

explicit_time_advance - avg: 26.1221 min: 24.921 max: 28.322 med: 25.8075 calls: 10
kronmult - avg: 0.0715333 min: 0.051 max: 0.094 med: 0.071 avg gflops: 0.058261 calls: 30
kronmult_build - avg: 0.0752 min: 0.058 max: 0.105 med: 0.0735 calls: 30
kronmult_setup - avg: 5.61473 min: 5.195 max: 6.916 med: 5.4445 calls: 30
kronmult_stage - avg: 0.0667 min: 0.046 max: 0.09 med: 0.0655 calls: 30
```

2021-04-05 19:42 UTC, quantumsteve commented on CMakeLists.txt
> +    include_directories(matlab_plot SYSTEM ${Matlab_INCLUDE_DIRS})
Can you do the same with [target_include_directories](https://cmake.org/cmake/help/latest/command/target_include_directories.html)?

2021-04-05 19:42 UTC, quantumsteve commented on CMakeLists.txt
>  endforeach ()
I realize this wasn't added in your PR, but is a for loop necessary here? I think `target_link_libraries` accepts a list.

2021-04-05 19:42 UTC, quantumsteve commented on scripts/matlab/plot_fval.m
> +%     contour(p_par,p_pen,f_nD,10,'LineWidth',2)
why is there commented out code?

2021-04-05 19:42 UTC, quantumsteve commented on scripts/matlab/plot_fval.m
> +%
more commented out code?

2021-04-05 19:42 UTC, quantumsteve commented on scripts/matlab/plot_fval.m
> +%pause (0.01)
more commented out code?

2021-04-05 19:42 UTC, quantumsteve commented on src/matlab_plot.hpp
> +    expect(!std::is_scalar<T>::value);
I think the same check could be done with `static_assert`

2021-04-05 19:42 UTC, quantumsteve commented on src/matlab_plot.hpp
> +  matlab_plot() {}
```suggestion
  matlab_plot() = default;
```

2021-04-05 19:42 UTC, quantumsteve commented on src/matlab_plot.hpp
> +    // Connects to a shared MATLAB session with given name, or first available
Can we move implemention to `matlab_plot.cpp`?

2021-04-07 14:42 UTC, dlg0 commented
@ckendrick Can you add a small section to the README.md to show how to utilize this capability? Also, something to note in that section is that if you choose to take the shareEngine approach, you have to make sure that the shared instance of matlab is NOT open in the DG-SparseGrid repo where there is another instance of `plot_fval.m` since it defaults to the first one it finds (and hence crashes - which happened to me). Somewhat an obscure bug, and will go away once we have the matlab use the C++ plot_fval, but for now just mention it in the instructions.

2021-04-07 16:41 UTC, cianciosa commented on src/matlab_plot.cpp
> +    for (unsigned int j = 0; j < xi.size(); j++)
On 64 bit architectures, `size()` method returns the size as a 64 bit integer. This would cause an infinite loop when `xi.size() > std:: numeric_limits <unsigned int>::max`. It would be better to use 

```
for (std::size_t j = 0, je = xi.size(); j < je; j++)
{
  ...
}

2021-04-07 16:41 UTC, cianciosa commented on src/matlab_plot.cpp
> +    Iu.push_back(dof * (i + 1));
The final size of Iu is known before the vector is created. This could avoid other overhead of push_back allocating enough space for Iu at the beginning.

```
std::vector<int> Iu(degree);
for (int j = 0, je = degree - 1; j < je; j++)
{
  Iu[j] = dof*i + j + 1;
}
Iu[degree - 1] = dof*(i + 1);

2021-04-07 16:41 UTC, cianciosa commented on src/matlab_plot.cpp
> +    }
The final size of xi is known so we could avoid push_back overhead 

```
std::vector<T> xi(roots.size());
for (std::size_t j = 0, je = roots.size(); j < je; j++) 
{
  xi[j] = (0.5 * (root + 1.0) + i) * h + min;
}

```

2021-04-07 16:41 UTC, cianciosa commented on src/matlab_plot.cpp
> +  push_param(elem_coords_);
This is more a stylist thing and the code as written is fine as it is, but you could make use of variadic templates here.

```
   template<typename T, typename... Args>
   void add_param(T const &t, Args&&... args)
   {
     m_args_.push_back(factory_.createScalar(t));
     add_param(args...);
   }

   template<typename T>
   void add_param(T const &t)
   {
     m_args_.push_back(factory_.createScalar(t));
   }

   template<typename T, typename... Args>
   void add_param(matlab::data::ArrayDimensions const dims, T const &t, Args&&... args)
   {
     static_assert(!std::is_scalar<T>::value);
     m_args_.push_back(factory_.createArray(dims, t.begin(), t.end()));
     add_param(args...);
   }

   template<typename T>
   void add_param(matlab::data::ArrayDimensions const dims, T const &t)
   {
     static_assert(!std::is_scalar<T>::value);
     m_args_.push_back(factory_.createArray(dims, t.begin(), t.end()));
   }
```

Using this when you need to add multiple parameters you could just write
```
   add_param(ndims,
             {1, static_cast<size_t>(analytic_soln.size())}, analytic_soln,
             {1, ndims}, nodes_,
             sol_sizes_, f_val,
             sol_sizes_, analytic_soln);
```

2021-05-11 16:32 UTC, quantumsteve approved these changes

2021-05-11 16:33 UTC, cianciosa approved these changes

2021-05-11 16:36 UTC, merged