Replace git submodule with cmake fetch
project-asgard/asgard pull request #396
Opened 2021-06-08 20:24 UTC by cianciosa

NOTE: This cannot be merged until the kronmult https://github.com/project-asgard/kronmult/pull/9 is merged since it requires changes from that pull request.

## Proposed changes

This change defines a macro function for registering external cmake based projects. Once an external project is registered, a developer may configure their build to point to other forks or other branches using the new  build setting

- `BUILD_REPO_<NAME>`
- `BUILD_TAG_<NAME>`

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [ ] Bugfix
- [ ] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [x] Yes
- [ ] No

## What systems has this change been tested on?
This has been tested with CUDA support on an ubuntu 18.04 install. Tests for

- kronmult-test
- time_advance-test-mpi
- time_advance-test
- kronmult_cuda-test

currently fail.

MacOS build still fail due to issues referenced in https://github.com/project-asgard/asgard/issues/387 in the adapt library.

## Checklist

- [x] this PR is up to date with current the current state of 'develop'
- [x] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

2021-06-08 20:30 UTC, cianciosa commented
AWS tests fail at compile time due to

```
[ 29%] Building CXX object _deps/kronmult-build/CMakeFiles/kgemm_nn_test.dir/test_kgemm_nn_batched.cpp.o
--
801 | /codebuild/output/src458844159/src/github.com/project-asgard/asgard/src/device/kronmult_cuda.cpp:21:10: fatal error: kronmult1_xbatched.hpp: No such file or directory
802 | 21 \| #include "kronmult1_xbatched.hpp"
803 | \|          ^~~~~~~~~~~~~~~~~~~~~~~~
804 | compilation terminated.
```

The changes in https://github.com/project-asgard/kronmult/pull/9 are expected to resolve this.

2021-06-09 16:26 UTC, quantumsteve requested changes
How do we remove the current git submodule from ASGarD?

Additional review comments attached

2021-06-09 16:26 UTC, quantumsteve commented on CMakeLists.txt
> +macro (register_project name dir url default_tag)
Can (should?) this be written as a function with better control of scope?

2021-06-09 16:26 UTC, quantumsteve commented on CMakeLists.txt
> +                  master
Let's follow a specific sha instead of master. We don't want a change to kronmult to break asgard.

2021-06-09 16:26 UTC, quantumsteve commented on CMakeLists.txt
> +        execute_process(
Why would a user (or a developer not modifying kronmult) want this?

2021-06-09 16:26 UTC, quantumsteve commented on CMakeLists.txt
> +            pull_${name}
Changing the version of kronmult should require a PR.

2021-06-09 16:26 UTC, quantumsteve commented on contrib/contrib.cmake
> +#    set(USE_GPU 1)
Where is `USE_GPU` being set?

2021-06-09 16:26 UTC, quantumsteve commented on CMakeLists.txt
> +#target_include_directories (kronmult_cuda PRIVATE ${CMAKE_SOURCE_DIR}/contrib/kronmult/ ${CMAKE_BINARY_DIR})
please remove commented out code

2021-06-09 16:26 UTC, quantumsteve commented on contrib/contrib.cmake
> +#set(KRON_INCLUDE_DIR "${CMAKE_SOURCE_DIR}/contrib/kronmult/")
please remove commented out code

2021-06-09 16:26 UTC, quantumsteve commented on CMakeLists.txt
> +        SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/${dir}
I'd prefer the the SOURCE_DIR be inside `CMAKE_BUILD_DIR` so it doesn't pollute the source directory.

2021-06-17 20:31 UTC, cianciosa commented on CMakeLists.txt
> +macro (register_project name dir url default_tag)
I changed this to a function.

2021-06-17 20:33 UTC, cianciosa commented on CMakeLists.txt
> +                  master
Master has not been replaced with a specific git hash. I have also added a comment that changes to this hash should go through a pull request.

2021-06-17 20:33 UTC, cianciosa commented on CMakeLists.txt
> +        execute_process(
This has been removed.

2021-06-17 20:33 UTC, cianciosa commented on CMakeLists.txt
> +            pull_${name}
Also removed.

2021-06-17 20:36 UTC, cianciosa commented on contrib/contrib.cmake
> +#    set(USE_GPU 1)
This is not set at https://github.com/cianciosa/asgard/blob/6becc11bcc1beed48c746da2a980bf70ee60eb5d/CMakeLists.txt#L154

2021-06-17 20:36 UTC, cianciosa commented on CMakeLists.txt
> +#target_include_directories (kronmult_cuda PRIVATE ${CMAKE_SOURCE_DIR}/contrib/kronmult/ ${CMAKE_BINARY_DIR})
Removed

2021-06-17 20:36 UTC, cianciosa commented on contrib/contrib.cmake
> +#set(KRON_INCLUDE_DIR "${CMAKE_SOURCE_DIR}/contrib/kronmult/")
Removed

2021-06-17 20:38 UTC, cianciosa commented on CMakeLists.txt
> +        SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/${dir}
I have changed this to `${CMAKE_CURRENT_SOURCE_DIR}/contrib/${dir}` to match the location where the original git submodule was cloned to.

2021-06-17 21:00 UTC, quantumsteve commented on CMakeLists.txt
> +        SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/${dir}
Delete the existing submodule inside https://github.com/project-asgard/asgard/tree/develop/contrib

2021-07-07 16:32 UTC, quantumsteve approved these changes

2021-07-07 16:35 UTC, merged