Fix const error when compiling in clang.
project-asgard/asgard pull request #398
Opened 2021-07-13 16:31 UTC by cianciosa

## Proposed changes

This fixes the second bug in https://github.com/project-asgard/asgard/issues/387. The bug arrises because `plan_` contains elements that are marked `const` and the line `plan_ = new_plan` tries to overwrite them which would violate the `const` property. This pr works around that by deleting the old elements of `plan_` first then inserting the elements of `new_plan`

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [x] Bugfix
- [ ] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

## What systems has this change been tested on?
Mac OS and Linux. Running the unit tests locally result in several test failures of unknown origin.

## Checklist

- [x] this PR is up to date with current the current state of 'develop'
- [ ] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

2021-07-15 15:10 UTC, quantumsteve requested changes
Please add a code comment and squash your commits.

2021-07-15 15:10 UTC, quantumsteve commented on src/adapt.cpp
> -  plan_               = new_plan;
Please add a comment about why we're doing this.

2021-07-15 15:10 UTC, quantumsteve commented on src/adapt.cpp
> +
Please add a comment about why we're doing this.

2021-07-19 20:39 UTC, cianciosa commented
🤬🤬🤬 Every time I try to squash the commits, it just keeps adding more.

2021-07-20 16:34 UTC, quantumsteve approved these changes

2021-07-20 16:34 UTC, merged