HIP version of asgard
project-asgard/asgard pull request #400
Opened 2021-07-23 04:23 UTC by ckendrick

## Proposed changes

This replaces CUDA calls in Asgard with HIP equivalents and adjusts CMake for building with HIP.

The HIP version of the underlying Kronmult library needs to be used to fully utilize HIP for AMD platforms. CMake 3.21 should allow for a lot of CMake simplifications.

Building on `fusionmi50`:
```
spack load --first hip@4.2.0
spack load hipblas@4.2.0

cmake -DCMAKE_CXX_COMPILER=clang++ -DASGARD_USE_HIP=ON ../
```

Building on `fusiont5`:
```
spack load cuda@10.2.89%gcc@7.4.0
export CUDA_PATH=${CUDA_HOME}
export HIP_PATH=/opt/rocm-4.2.0/hip/
export HIP_PLATFORM=nvidia
export HIP_COMPILER=nvcc
export HIP_RUNTIME=cuda

cmake -DCMAKE_CUDA_COMPILER=${CUDA_PATH}/bin/nvcc -DASGARD_USE_HIP=ON ../
```

Building on `fusiont6`:
```
spack load cuda@11.3.0
export CUDA_PATH=${CUDA_HOME}

cmake -DASGARD_USE_HIP=ON ../
```

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [ ] Bugfix
- [x] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## What systems has this change been tested on?

fusiont5
fusiont6
fusionmi50
Ubuntu20.04 with Nvidia GPUs (CUDA 10.2 - 11.4)

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [x] this PR is up to date with current the current state of 'develop'
- [x] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

2021-08-31 21:25 UTC, quantumsteve commented
@ckendrick What changes do you need to the build so they it'll run with `-DASGARD_USE_HIP=ON`?

2021-08-31 21:50 UTC, quantumsteve commented
I tried following your directions on fusionmi50, but go the following error. Do I need to load a compiler first?
```
[svh@fusionmi50 ~]$ source /opt/spack/share/spack/setup-env.sh
[svh@fusionmi50 ~]$ spack load --first hip@4.2.0
==> Error: No compilers for operating system centos7 satisfy spec gcc@7.3.1
```

2021-08-31 22:18 UTC, ckendrick commented
> I tried following your directions on fusionmi50, but go the following error. Do I need to load a compiler first?
> 
> ```
> [svh@fusionmi50 ~]$ source /opt/spack/share/spack/setup-env.sh
> [svh@fusionmi50 ~]$ spack load --first hip@4.2.0
> ==> Error: No compilers for operating system centos7 satisfy spec gcc@7.3.1
> ```

Try running `spack compiler find` which should automatically find the compilers installed. Usually you just have to do this once with a new spack setup. If it works, then you should have the following after running `spack compiler list`:
```
==> Available compilers
-- clang centos7-x86_64 -----------------------------------------
clang@12.0.0

-- gcc centos7-x86_64 -------------------------------------------
gcc@7.3.1  gcc@4.8.5
```
If not, then I can share the configuration I am using to put in `~/.spack/linux/compilers.yaml`

2021-09-01 14:08 UTC, quantumsteve commented
Looks like packages aren't being shared within our common spack setup :confused:
```
[svh@fusionmi50 ~]$ source /opt/spack/share/spack/setup-env.sh 
[svh@fusionmi50 ~]$  spack compiler list
==> Available compilers
-- gcc centos7-x86_64 -------------------------------------------
gcc@4.8.5
```

2021-09-01 14:23 UTC, ckendrick commented
I think running `source /opt/rh/devtoolset-7/enable` before setting up the spack environment should get the newer version of gcc

2021-09-01 14:33 UTC, quantumsteve commented
```
[svh@fusionmi50 ~]$ source /opt/rh/devtoolset-7/enable
[svh@fusionmi50 ~]$ source /opt/spack/share/spack/setup-env.sh 
[svh@fusionmi50 ~]$ spack compiler list
==> Available compilers
-- gcc centos7-x86_64 -------------------------------------------
gcc@4.8.5
```

2021-09-01 14:36 UTC, ckendrick commented
Sorry, I forgot to mention that `spack compiler find` should be re-run as well.

2021-09-01 14:52 UTC, quantumsteve commented
I also needed to run `spack load cmake@3.21.0`

2021-09-01 15:07 UTC, quantumsteve commented
```
[svh@fusionmi50 build]$ make
[  0%] Building CXX object CMakeFiles/lib_dispatch.dir/src/lib_dispatch.cpp.o
clang-12: error: cannot find ROCm device library. Provide its path via --rocm-path or --rocm-device-lib-path, or pass -nogpulib to build without ROCm device library.
make[2]: *** [CMakeFiles/lib_dispatch.dir/build.make:76: CMakeFiles/lib_dispatch.dir/src/lib_dispatch.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:340: CMakeFiles/lib_dispatch.dir/all] Error 2
make: *** [Makefile:101: all] Error 2
```
I tried loading `rocm-device-libs`, but am getting the following error:

```
[svh@fusionmi50 build]$ spack load rocm-device-libs@4.2.0%gcc@7.3.1
==> Error: rocm-device-libs@4.2.0%gcc@7.3.1 matches multiple packages.
  Matching packages:
    bvogsld rocm-device-libs@4.2.0%gcc@7.3.1 arch=linux-centos7-zen
    elwhgty rocm-device-libs@4.2.0%gcc@7.3.1 arch=linux-centos7-zen
    mpkqzkj rocm-device-libs@4.2.0%gcc@7.3.1 arch=linux-centos7-zen
  Use a more specific spec.
  ```

2021-09-01 15:20 UTC, quantumsteve commented
```
The following tests FAILED:
	  1 - adapt-test (Subprocess aborted)
	  2 - basis-test (Subprocess aborted)
	  3 - batch-test (Subprocess aborted)
	  4 - boundary_conditions-test (Subprocess aborted)
	  5 - coefficients-test (Subprocess aborted)
	  6 - distribution-test (Subprocess aborted)
	  7 - elements-test (Subprocess aborted)
	  8 - fast_math-test (Subprocess aborted)
	  9 - kronmult-test (Subprocess aborted)
	 10 - lib_dispatch-test (Subprocess aborted)
	 11 - matlab_utilities-test (Subprocess aborted)
	 12 - pde-test (Subprocess aborted)
	 13 - permutations-test (Subprocess aborted)
	 15 - quadrature-test (Subprocess aborted)
	 16 - solver-test (Subprocess aborted)
	 17 - tensors-test (Subprocess aborted)
	 18 - time_advance-test (Subprocess aborted)
	 20 - transformations-test (Subprocess aborted)
	 21 - kronmult_cuda-test (Subprocess aborted)
```
```
[svh@fusionmi50 build]$ ctest -R adapt-test --verbose
UpdateCTestConfiguration  from :/home/svh/asgard/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/svh/asgard/build/DartConfiguration.tcl
Test project /home/svh/asgard/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
    Start 1: adapt-test

1: Test command: /home/svh/asgard/build/adapt-tests
1: Test timeout computed to be: 10000000
1: adapt-tests: /home/svh/asgard/src/lib_dispatch.cpp:39: device_handler::device_handler(): Assertion `success == HIPBLAS_STATUS_SUCCESS' failed.
1/1 Test #1: adapt-test .......................Subprocess aborted***Exception:   0.17 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.17 sec

The following tests FAILED:
	  1 - adapt-test (Subprocess aborted)
Errors while running CTest
Output from these tests are in: /home/svh/asgard/build/Testing/Temporary/LastTest.log
```

2021-09-01 15:31 UTC, ckendrick commented
`rocm-device-libs` should get loaded automatically when loading hip, you can use `spack find --loaded` to verify it is listed.

This seems to be a path issue, probably due to the abnormal directory structure from splitting rocm/hip into spack packages (instead of having everything installed to /opt/rocm). Setting the following environment variables should fix the rocm device lib path message. You might have to also purge the build directory and re-run cmake.
```
export HIP_DEVICE_LIB_PATH=/opt/spack/opt/spack/linux-centos7-zen/gcc-7.3.1/rocm-device-libs-4.2.0-elwhgtyne5wgof6m6mwrlconzda6epvi/amdgcn/bitcode
export DEVICE_LIB_PATH=${HIP_DEVICE_LIB_PATH}
```

2021-09-01 15:48 UTC, ckendrick commented
Can you run `rocminfo` and `hipconfig` without any error? You may need to be added to the `video` group.

2021-11-18 18:00 UTC, quantumsteve requested changes
Couple thoughts while reviewing these changes

2021-11-18 18:00 UTC, quantumsteve commented on CMakeLists.txt
> +    find_package(CUDA 9.0 REQUIRED)
Can we eliminate the old `find_package(CUDA)`?

2021-11-18 18:00 UTC, quantumsteve commented on CMakeLists.txt
> +  include_directories(${HIPBLAS_INCLUDE_DIRS})
Can we use `target_include_directories`?

2021-11-18 18:00 UTC, quantumsteve commented on CMakeLists.txt
> +    #set_source_files_properties( src/device/kronmult_cuda.cpp PROPERTIES LANGUAGE HIP ) # should work after cmake 3.21 release?
Can we use this now that we require CMake 3.21?

2021-11-18 18:00 UTC, quantumsteve commented on src/batch_tests.cpp
> +    tol_factor = 1e-7;
😮

2021-11-18 18:00 UTC, quantumsteve commented on CMakeLists.txt
> +    target_link_libraries(tensors PRIVATE ${CUDA_LIBRARIES})
Does HIP not take care of linking against CUDA?

2021-11-18 18:00 UTC, quantumsteve commented on CMakeLists.txt
> +    target_link_libraries(lib_dispatch PRIVATE ${CUDA_LIBRARIES})
Does HIP not take care of linking against CUDA?

2021-11-23 16:03 UTC, ckendrick commented on CMakeLists.txt
> +    #set_source_files_properties( src/device/kronmult_cuda.cpp PROPERTIES LANGUAGE HIP ) # should work after cmake 3.21 release?
Yes, I believe this should work now but I am not able to test it at the moment since the AMD machine is still down.

2021-11-23 16:08 UTC, ckendrick commented on CMakeLists.txt
> +    target_link_libraries(tensors PRIVATE ${CUDA_LIBRARIES})
I haven't been able to get it to work automatically, but I might be missing something. `enable_language(HIP)` seems to cause issues on Nvidia. The closest I've gotten is on the kronmult PR, but that was setting the language to CUDA for each target which may not be the best solution.
The new changes I made is using `hip_add_library` and `hip_add_executable` (which may be worse than before?) but those still seem to be missing linking in the CUDA libraries.

2022-09-27 16:57 UTC, mkstoyanov commented on CMakeLists.txt
> +option (ASGARD_USE_HIP "Optional HIP support for asgard" OFF)
Using CUDA through the HIP API is not a great idea at the moment. The biggest issue comes from the use of math-libraries such as cuBlas and rocBlas, where they don't fully mirror or port the capabilities (especially true for sparse calls). Lesser problems (but problems never the less) come from availability and support across platforms, Nvidia based systems do not have universal support for HIP, also optimizations and performance.

HIP and CUDA can sit side by side in the code and have only one flipped on/off. All we need (usually) is to change the abstraction of memory allocation and data movement, as well as the kernels which seldom require any change, i.e., we can use the same kernels, just compile them differently.

2023-04-19 13:48 UTC, quantumsteve commented
@ckendrick @mkstoyanov I recommend closing this as we're unlikely to continue using the earlier kronmult implementation.

2023-04-19 14:07 UTC, closed without merging