Fix macOS Errors by using the cblas interface and clapack headers. <WIP>
project-asgard/asgard pull request #401
Opened 2021-07-23 16:47 UTC by cianciosa

## Proposed changes
This fixes the test failures reported in https://github.com/project-asgard/asgard/issues/399 by switching to use the cblas interface.

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [x] Bugfix
- [ ] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [x] Yes
- [ ] No

The builds fails on GitHub actions linux. It looks like it fails to find the clapack header. This may need to revery the non __APPLE__ branch to manual export for lapack libraries. 

## What systems has this change been tested on?
macOS

## Checklist

- [x] this PR is up to date with current the current state of 'develop'
- [ ] code added or changed in the PR has been clang-formatted
- [x] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

2021-07-23 16:57 UTC, cianciosa commented
This PR add a GitHub action. But that won't automatically run until after the is merged. There results of the test can be seen here

https://github.com/cianciosa/asgard/actions/runs/1060276930

2021-07-23 17:16 UTC, quantumsteve commented
I don't think there is a standard C interface to the Fortran LAPACK
http://nicolas.limare.net/pro/notes/2014/10/31_cblas_clapack_lapacke/
http://math-atlas.sourceforge.net/faq.html#clapackStand

2021-07-23 17:42 UTC, cianciosa commented
I looked in openblas source and saw it had a clapack and assumed it was standard with every lapack instance. It should be simple to revert that for non-apple builds.

On Jul 23, 2021, at 1:16 PM, Steven Hahn ***@***.******@***.***>> wrote:



I don't think there is a standard C interface to the Fortran LAPACK
http://nicolas.limare.net/pro/notes/2014/10/31_cblas_clapack_lapacke/
http://math-atlas.sourceforge.net/faq.html#clapackStand

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub<https://github.com/project-asgard/asgard/pull/401#issuecomment-885783039>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ADAPYD3YMA6J6VHFZ6P4IGDTZGPV3ANCNFSM5A4KVEIQ>.

2021-07-23 18:23 UTC, cianciosa commented
The linux GitHub actions now builds and passes tests. https://github.com/cianciosa/asgard/runs/3145995499?check_suite_focus=true

2021-07-23 18:26 UTC, quantumsteve commented on src/lib_dispatch.hpp
> +#ifdef __APPLE__
Apple + Other BLAS libraries (OpenBLAS, MKL, etc.) should be acceptable combinations.

2021-07-23 18:34 UTC, quantumsteve commented
Our AWS builds still have header issues.
```
/codebuild/output/src118884115/src/github.com/project-asgard/asgard/src/lib_dispatch.hpp:9:10: fatal error: cblas.h: No such file or directory
```
 May we use the same Docker container on AWS Codebuild and GitHub actions?

2021-07-23 18:51 UTC, cianciosa commented
I think the asgard-unit-cuda-gxx test is failing because the lib_dispatch is compiled before OpenBlas is installed so it never picks up the cblas header.

2021-08-31 21:19 UTC, quantumsteve requested changes
Overall this looks good. See comments for recommended changes.

2021-08-31 21:19 UTC, quantumsteve commented on .github/workflows/ci_tests.yaml
> +                os: [macos-latest, ubuntu-latest]
Adding a MacOS build here make sense (not available in AWS Codebuild), but the Linux tests duplicate what we already have on AWS.

2021-08-31 21:19 UTC, quantumsteve commented on CMakeLists.txt
> +set (CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH};${CMAKE_CURRENT_SOURCE_DIR}/contrib)
I think the modern suggest is to use [`list(APPEND <list> [<element>...])`](https://cmake.org/cmake/help/latest/command/list.html#append)

```suggestion
list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/contrib)
```

2021-08-31 21:19 UTC, quantumsteve commented on CMakeLists.txt
> +  target_link_libraries (lib_dispatch PUBLIC LINALG::LINALG)
Why is this change necessary? It seems to build fine when I set this to private 😕

2021-08-31 21:19 UTC, quantumsteve commented on CMakeLists.txt
> +  target_link_libraries (kronmult_cuda-tests PRIVATE coefficients kronmult_cuda tests_general LINALG::LINALG)
Why do we need to start linking against `LINALG::LINALG` here?

2021-08-31 21:19 UTC, quantumsteve commented on contrib/FindLINALG.cmake
> +    find_package (LAPACK)
Should we pass the `BLA_VENDOR` property to these two finders?

2021-08-31 21:19 UTC, quantumsteve commented on contrib/FindLINALG.cmake
> +              SunPerf
Can we prune this list to better match what's currently being tested and likely to be used with ASGarD?

2021-08-31 21:19 UTC, quantumsteve commented on src/lib_dispatch.cpp
> +  CBLAS_TRANSPOSE transpose;
Since this pattern repeats 3 times, make it function.

2021-09-03 14:36 UTC, cianciosa commented on contrib/FindLINALG.cmake
> +              SunPerf
I've pruned out the ones that were obviously deprecated or obsolete platforms (mips, alpha, sparc, obscure Russian processor). I left in all the cases for current architectures (arm, x86, POWER9). However there are some that aren't clear what their status is.

- ATLAS (Not sure if this is still actively developed.)
- FLAME (Is under active develop at the UT-Austin supercomputer center)
- Fujitsu ones are for the current fastest super computer (Fugaku).
- SCSL Not sure but I think this is cray version.

2021-09-03 14:41 UTC, cianciosa commented on src/lib_dispatch.cpp
> +  CBLAS_TRANSPOSE transpose;
I have refactored it into a function. Right now the function checks for n,N,t,T and assumes anything else is a conjugate transpose. Should I explicitly check or c,C and assert on anything else instead?

2021-09-03 14:44 UTC, cianciosa commented on CMakeLists.txt
> +set (CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH};${CMAKE_CURRENT_SOURCE_DIR}/contrib)
Fixed

2021-09-03 14:44 UTC, cianciosa commented on CMakeLists.txt
> +  target_link_libraries (lib_dispatch PUBLIC LINALG::LINALG)
This was reverted back.

2021-09-03 14:45 UTC, cianciosa commented on CMakeLists.txt
> +  target_link_libraries (kronmult_cuda-tests PRIVATE coefficients kronmult_cuda tests_general LINALG::LINALG)
This was reverted back also.

2021-09-07 13:51 UTC, quantumsteve approved these changes

2021-09-07 14:14 UTC, quantumsteve commented on src/lib_dispatch.cpp
> +  CBLAS_TRANSPOSE transpose;
I think fast-math creates the string so user input won't create an issue here.

2021-09-07 14:14 UTC, merged