Add mpi-tests to test different rank sizes.
project-asgard/asgard pull request #405
Opened 2021-09-28 18:52 UTC by cianciosa

Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes
This adds tests to test mpi runs with different total rank sizes. Tests show failures in some cases when the number of processors does not equal 4.

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [ ] Bugfix
- [ ] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [x] Yes
- [ ] No

## What systems has this change been tested on?
Github actions macos-latested
Mark's laptop.
Mark Unbuntu machine.

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [x] this PR is up to date with current the current state of 'develop'
- [ ] code added or changed in the PR has been clang-formatted
- [x] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

2021-09-28 18:54 UTC, cianciosa commented
This test adds tests related to Issue https://github.com/project-asgard/asgard/issues/404

2021-11-24 18:38 UTC, cianciosa commented
Looking at this more I pin pointed where the dead lock is happening when running with 3 MPI processes. In the line

https://github.com/project-asgard/asgard/blob/d616a8fc33cf1e790a1d5a70c21e67177b642c1e/src/distribution_tests.cpp#L378

Global ranks 0 and 1 evaluate to true while rank global rank 2 evaluates to false. Then on the line

https://github.com/project-asgard/asgard/blob/d616a8fc33cf1e790a1d5a70c21e67177b642c1e/src/distribution_tests.cpp#L412

the results are gathered. A dead lock then happens on line

https://github.com/project-asgard/asgard/blob/d616a8fc33cf1e790a1d5a70c21e67177b642c1e/src/distribution.cpp#L284

since the `MPI_Comm_split` is not being called on every process.

2021-11-24 19:15 UTC, cianciosa commented
Putting in some debug messages shows what's happening.

```
initialize_distribution rank 0 global_comm 0x7f8f51c56ae0 world_comm 0x10faea590
set global comm on world rank 0 comm rank 0
initialize_distribution rank 1 global_comm 0x7ff0cb44dc90 world_comm 0x106b4f590
set global comm on world rank 1 comm rank 1
initialize_distribution rank 2 global_comm 0x103961990 world_comm 0x103961590
Constructing new distribution_handler on rank 2 global_comm 0x103961590 world_comm 0x103961590
Constructing new distribution_handler on rank 0 global_comm 0x10faea590 world_comm 0x10faea590
Constructing new distribution_handler on rank 1 global_comm 0x106b4f590 world_comm 0x106b4f590
```

It looks like `initialize_distribution` is splitting world comm then setting the global comm of the `distribution_handler`. But the default constructor is getting called after this which resets this to `MPI_COMM_WORLD`.

2022-02-03 20:00 UTC, quantumsteve commented
I'm getting linking errors.
```
[119/156] Linking CXX executable solver-tests
FAILED: solver-tests 
: && /usr/bin/c++ -Wall -Wextra -Wpedantic -O2 -g -DNDEBUG -pthread CMakeFiles/solver-tests.dir/src/solver_tests.cpp.o -o solver-tests  -Wl,-rpath,/usr/lib/x86_64-linux-gnu/openmpi/lib  libsolver.a  libtests_general.a  libsolver.a  libtests_general_main.a  libfast_math.a  libpde.a  libbasis.a  libquadrature.a  libdistribution.a  libprogram_options.a  libelements.a  libdistribution.a  libprogram_options.a  libelements.a  /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so  /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so  libpermutations.a  libmatlab_utilities.a  libtensors.a  liblib_dispatch.a  /usr/lib/x86_64-linux-gnu/libopenblas.so  -lpthread  -lm  -ldl  /usr/lib/gcc/x86_64-linux-gnu/9/libgomp.so  /usr/lib/x86_64-linux-gnu/libpthread.so  _deps/catch2-build/src/libCatch2Main.a  _deps/catch2-build/src/libCatch2.a && :
/usr/bin/ld: liblib_dispatch.a(lib_dispatch.cpp.o): in function `MPI::Win::Set_name(char const*)':
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h:293: undefined reference to `MPI_Win_set_name'
/usr/bin/ld: liblib_dispatch.a(lib_dispatch.cpp.o): in function `MPI::Win::Set_attr(int, void const*)':
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h:286: undefined reference to `MPI_Win_set_attr'
/usr/bin/ld: liblib_dispatch.a(lib_dispatch.cpp.o): in function `MPI::Win::Get_name(char*, int&) const':
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h:279: undefined reference to `MPI_Win_get_name'
/usr/bin/ld: liblib_dispatch.a(lib_dispatch.cpp.o): in function `MPI::Win::Delete_attr(int)':
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h:244: undefined reference to `MPI_Win_delete_attr'
/usr/bin/ld: liblib_dispatch.a(lib_dispatch.cpp.o): in function `MPI::Win::Call_errhandler(int) const':
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h:178: undefined reference to `MPI_Win_call_errhandler'
/usr/bin/ld: liblib_dispatch.a(lib_dispatch.cpp.o): in function `MPI::Win::Wait() const':
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h:167: undefined reference to `MPI_Win_wait'
/usr/bin/ld: liblib_dispatch.a(lib_dispatch.cpp.o): in function `MPI::Win::Unlock(int) const':
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h:160: undefined reference to `MPI_Win_unlock'
/usr/bin/ld: liblib_dispatch.a(lib_dispatch.cpp.o): in function `MPI::Win::Test() const':
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h:151: undefined reference to `MPI_Win_test'
/usr/bin/ld: liblib_dispatch.a(lib_dispatch.cpp.o): in function `MPI::Win::Start(MPI::Group const&, int) const':
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h:143: undefined reference to `MPI_Win_start'
/usr/bin/ld: liblib_dispatch.a(lib_dispatch.cpp.o): in function `MPI::Win::Put(void const*, int, MPI::Datatype const&, int, long, int, MPI::Datatype const&) const':
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h:133: undefined reference to `MPI_Put'
/usr/bin/ld: liblib_dispatch.a(lib_dispatch.cpp.o): in function `MPI::Win::Post(MPI::Group const&, int) const':
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h:122: undefined reference to `MPI_Win_post'
/usr/bin/ld: liblib_dispatch.a(lib_dispatch.cpp.o): in function `MPI::Win::Lock(int, int, int) const':
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h:115: undefined reference to `MPI_Win_lock'
/usr/bin/ld: liblib_dispatch.a(lib_dispatch.cpp.o): in function `MPI::Win::Get_group() const':
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h:107: undefined reference to `MPI_Win_get_group'
/usr/bin/ld: liblib_dispatch.a(lib_dispatch.cpp.o): in function `MPI::Win::Get(void const*, int, MPI::Datatype const&, int, long, int, MPI::Datatype const&) const':
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h:96: undefined reference to `MPI_Get'
/usr/bin/ld: liblib_dispatch.a(lib_dispatch.cpp.o): in function `MPI::Win::Fence(int) const':
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h:85: undefined reference to `MPI_Win_fence'
/usr/bin/ld: liblib_dispatch.a(lib_dispatch.cpp.o): in function `MPI::Win::Complete() const':
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h:67: undefined reference to `MPI_Win_complete'
/usr/bin/ld: liblib_dispatch.a(lib_dispatch.cpp.o): in function `MPI::Win::Accumulate(void const*, int, MPI::Datatype const&, int, long, int, MPI::Datatype const&, MPI::Op const&) const':
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h:57: undefined reference to `MPI_Accumulate'
/usr/bin/ld: liblib_dispatch.a(lib_dispatch.cpp.o): in function `MPI::Win::Get_errhandler() const':
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h:33: undefined reference to `MPI_Win_get_errhandler'
/usr/bin/ld: liblib_dispatch.a(lib_dispatch.cpp.o): in function `MPI::Win::Set_errhandler(MPI::Errhandler const&) const':
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/win_inln.h:41: undefined reference to `MPI_Win_set_errhandler'
/usr/bin/ld: liblib_dispatch.a(lib_dispatch.cpp.o): in function `MPI::Info::Set(char const*, char const*)':
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/info_inln.h:82: undefined reference to `MPI_Info_set'
/usr/bin/ld: liblib_dispatch.a(lib_dispatch.cpp.o): in function `MPI::Info::Get_valuelen(char const*, int&) const':
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/info_inln.h:75: undefined reference to `MPI_Info_get_valuelen'
/usr/bin/ld: liblib_dispatch.a(lib_dispatch.cpp.o): in function `MPI::Info::Get_nthkey(int, char*) const':
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/info_inln.h:68: undefined reference to `MPI_Info_get_nthkey'
/usr/bin/ld: liblib_dispatch.a(lib_dispatch.cpp.o): in function `MPI::Info::Get_nkeys() const':
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/info_inln.h:61: undefined reference to `MPI_Info_get_nkeys'
/usr/bin/ld: liblib_dispatch.a(lib_dispatch.cpp.o): in function `MPI::Info::Get(char const*, int, char*) const':
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/info_inln.h:53: undefined reference to `MPI_Info_get'
/usr/bin/ld: liblib_dispatch.a(lib_dispatch.cpp.o): in function `MPI::Info::Free()':
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/info_inln.h:46: undefined reference to `MPI_Info_free'
/usr/bin/ld: liblib_dispatch.a(lib_dispatch.cpp.o): in function `MPI::Info::Dup() const':
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/info_inln.h:39: undefined reference to `MPI_Info_dup'
/usr/bin/ld: liblib_dispatch.a(lib_dispatch.cpp.o): in function `MPI::Info::Delete(char const*)':
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/info_inln.h:32: undefined reference to `MPI_Info_delete'
/usr/bin/ld: liblib_dispatch.a(lib_dispatch.cpp.o): in function `MPI::Status::Set_cancelled(bool)':
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/status_inln.h:103: undefined reference to `MPI_Status_set_cancelled'
/usr/bin/ld: liblib_dispatch.a(lib_dispatch.cpp.o): in function `MPI::Status::Set_elements(MPI::Datatype const&, int)':
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/status_inln.h:97: undefined reference to `MPI_Status_set_elements'
/usr/bin/ld: liblib_dispatch.a(lib_dispatch.cpp.o): in function `MPI::Status::Get_elements(MPI::Datatype const&) const':
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/status_inln.h:45: undefined reference to `MPI_Get_elements'
/usr/bin/ld: liblib_dispatch.a(lib_dispatch.cpp.o): in function `MPI::Status::Is_cancelled() const':
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/s [...]

2022-02-07 18:49 UTC, quantumsteve commented
@cianciosa Linking errors fixed in https://github.com/cianciosa/asgard/pull/1

2022-02-07 21:58 UTC, quantumsteve requested changes
Is there a merging issue? Some of these changes should already be in `develop`.

2022-02-07 21:58 UTC, quantumsteve commented on CMakeLists.txt
> +                  v3.0.0-preview3
```suggestion
                  v3.0.0-preview4
```

2022-02-07 21:58 UTC, quantumsteve commented on CMakeLists.txt
> +  enable_language (Fortran)
I don't think this is necessary just to link against a FORTRAN library.

2022-02-07 21:58 UTC, quantumsteve commented on CMakeLists.txt
> +      target_link_libraries (${component}-tests PRIVATE ${component} MPI::MPI_CXX PUBLIC tests_general)
Looks like one can link against both tests_general AND tests_general_main. Is this correct?

2022-02-07 21:58 UTC, quantumsteve commented on src/adapt_tests.cpp
> +  distrib_test_info.set_my_rank(0);
The #ifdef and #else section aren't needed. With `ASGARD_USE_MPI=0` initialize_distribution() returns [0,1].

2022-02-07 21:58 UTC, quantumsteve commented on testing/tests_general.hpp
> +#include "../src/fast_math.hpp"
May we update the include directory to avoid the `../`?

2022-02-08 17:25 UTC, cianciosa commented on CMakeLists.txt
> +      target_link_libraries (${component}-tests PRIVATE ${component} MPI::MPI_CXX PUBLIC tests_general)
Correct one uses the built in catch2 main and the other uses the custom main in the tests.

2022-02-08 20:04 UTC, quantumsteve commented on CMakeLists.txt
> +      target_link_libraries (${component}-tests PRIVATE ${component} MPI::MPI_CXX PUBLIC tests_general)
are lines #491 and #464 indented at the same level?

2022-02-08 20:41 UTC, quantumsteve commented on src/cblacs_grid.cpp
> +  int myid    = get_rank();
`myid` is an unused variable.

2022-02-08 21:12 UTC, quantumsteve commented on src/device/kronmult_cuda.cpp
> +#ifdef expect
Where is the `expect` macro defined?

2022-03-08 20:17 UTC, quantumsteve commented
@cianciosa Would you squash this into one commit?

2022-03-08 20:34 UTC, quantumsteve commented
I tried running `git rebase -i upstream/develop` but encountered numerous merge conflicts.

I used `git diff` and `git apply` to create this branch. Does this diff look good?
https://github.com/project-asgard/asgard/compare/develop...quantumsteve:cianciosa-mpi_deadlock

2022-03-08 21:10 UTC, cianciosa commented
It looks good to me!

On Mar 8, 2022, at 3:34 PM, Steven Hahn ***@***.******@***.***>> wrote:

develop...quantumsteve:cianciosa-mpi_deadlock<hxxps://github.com/project-asgard/asgard/compare/develop...quantumsteve:cianciosa-mpi_deadlock>

2022-03-14 20:29 UTC, quantumsteve commented
I'm rebuilding the `asgard-unit-cuda-gxx` CI job that timed out. Assuming it passes, I'll merge this PR soon.

2022-03-14 20:44 UTC, quantumsteve approved these changes

2022-03-14 20:56 UTC, merged