Add patch to openblas. Use get_tolerance function to fix precision failure
project-asgard/asgard pull request #412
Opened 2022-01-07 21:32 UTC by quantumsteve

Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

Describe what this PR changes and why.  If it closes an issue, link to it here
with [a supported keyword](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

This brings in changes suggested in https://github.com/xianyi/OpenBLAS/issues/3494 to fix a failing OpenBLAS test on processors with AVX512 support.

We had a few tests failing because the tolerance was set for double and not float. Instead of setting different values for float and double, I created a small function that returns std::numeric_limits<T>::epsilon*ulp where ulp is an integer setting units last position.

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [x] Bugfix
- [ ] New feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

## What systems has this change been tested on?

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [x] this PR is up to date with current the current state of 'develop'
- [x] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

2022-01-10 21:16 UTC, ckendrick requested changes
This is a good change to the testing tolerances and should make additional tests easier in the future.

I did notice that the `transformations-tests` is failing occasionally between runs on fusiont5. It seems like typically between every 3-6 runs. The tolerance for this test might need to be adjusted?
```
ctest --rerun-failed --output-on-failure --repeat-until-fail 20
Test project /home/u0k/asgard/build
    Start 20: transformations-test
    Test #20: transformations-test .............   Passed    6.17 sec
    Start 20: transformations-test
    Test #20: transformations-test .............   Passed    6.07 sec
    Start 20: transformations-test
    Test #20: transformations-test .............   Passed    6.29 sec
    Start 20: transformations-test
    Test #20: transformations-test .............   Passed    6.25 sec
    Start 20: transformations-test
    Test #20: transformations-test .............   Passed    6.46 sec
    Start 20: transformations-test
    Test #20: transformations-test .............   Passed    6.32 sec
    Start 20: transformations-test
    Test #20: transformations-test .............***Failed    6.43 sec

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
transformations-tests is a Catch v2.11.3 host application.
Run with -? for options

-------------------------------------------------------------------------------
wavelet_to_realspace - float
  wavelet_to_realspace_3
-------------------------------------------------------------------------------
/home/u0k/asgard/src/transformations_tests.cpp:243
...............................................................................

/home/u0k/asgard/testing/tests_general.hpp:41: FAILED:
  REQUIRE( (diff_norm / max) < (tolerance * std::sqrt(v0.size())) )
with expansion:
  0.00679436931386590004f
  <
  0.00021579186437577745

===============================================================================
test cases:  8 |  7 passed | 1 failed
assertions: 98 | 97 passed | 1 failed
```

2022-01-21 19:09 UTC, quantumsteve commented
@ckendrick What are your CMake settings? After reducing tolerances in b7ba2ed, I can't get transformations-test to fail.

2022-01-21 19:42 UTC, ckendrick commented
It looks like I was using an old/bad openblas: `spack load openblas@0.3.7%gcc@7.4.0`.

Everything is working when building openblas with asgard or using a newer version.

2022-01-21 19:42 UTC, ckendrick approved these changes

2022-01-21 19:46 UTC, merged