Create asgard namespace
project-asgard/asgard pull request #465
Opened 2022-11-11 21:36 UTC by quantumsteve

Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

Describe what this PR changes and why.  If it closes an issue, link to it here
with [a supported keyword](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

This adds the asgard namespace to all library files. 

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [ ] Bugfix
- [x] New feature
- [x] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [x] Yes
- [ ] No

## What systems has this change been tested on?

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [x] this PR is up to date with current the current state of 'develop'
- [x] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

2022-11-12 20:40 UTC, mkstoyanov requested changes
Better, actually we can have a library now.

2022-11-12 20:40 UTC, mkstoyanov commented on src/boundary_conditions.hpp
> +using unscaled_bc_parts =
This should also be inside a namespace, right?

2022-11-12 20:40 UTC, mkstoyanov commented on src/lib_dispatch.cpp
> +namespace
Should this be `namespace lib_dispatch`

What's the namespace, I didn't even think this is valid C++.

2022-11-13 20:32 UTC, quantumsteve commented on src/lib_dispatch.cpp
> +namespace
unnamed namespaces are valid C++

https://abseil.io/tips/186

2022-11-13 23:20 UTC, mkstoyanov commented on src/lib_dispatch.cpp
> +namespace
Yes, I learned something new :) 

However, why do we need an unnamed one here? Shouldn't this be part of `lib_dispatch` namespace?

2022-11-14 15:26 UTC, quantumsteve commented on src/lib_dispatch.cpp
> +namespace
The `device_handler` struct and `cublas_trans` function are only used inside lib_dispatch.cpp. Putting them inside an unnamed namespace means it's local to this translation unit and if another symbol with the same name is defined elsewhere there will not be a violation of the One Definition Rule.

2022-11-14 15:31 UTC, quantumsteve commented on src/boundary_conditions.hpp
> +using unscaled_bc_parts =
I moved `unscaled_bc_parts` into `asgard::boundary_conditions`.

2022-11-14 16:25 UTC, ckendrick approved these changes

2022-11-14 18:29 UTC, mkstoyanov commented on src/lib_dispatch.cpp
> +namespace
Ok, that makes sense.

2022-11-14 18:30 UTC, mkstoyanov approved these changes

2022-11-14 18:30 UTC, mkstoyanov commented
@quantumsteve merge when you want

2022-11-14 22:32 UTC, merged