IMEX time advance and PDE parameters
project-asgard/asgard pull request #475
Opened 2022-12-13 15:36 UTC by ckendrick

Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

This finishes the implementation of the IMEX time advance started in #463 for the vlasov PDE, and adds a way to set/use simple parameters in PDEs.

An example of setting PDE parameters can be found [here](https://github.com/ckendrick/asgard/blob/5ada4529a64ef90dda3bafc6005f2a356d4543a4/src/pde/pde_vlasov_lb_full_f.hpp#L22-L24), using a parameter inside a gfunc can be found [here](https://github.com/ckendrick/asgard/blob/5ada4529a64ef90dda3bafc6005f2a356d4543a4/src/pde/pde_vlasov_lb_full_f.hpp#L285-L290), and updating a parameter can be found [here](https://github.com/ckendrick/asgard/blob/5ada4529a64ef90dda3bafc6005f2a356d4543a4/src/time_advance.cpp#L514-L518).

IMEX time advance is added using the `-x` switch and currently works only with the `vlasov` PDE. An example using IMEX: `./asgard -p vlasov -d 3 -l "4 4" -t 0.0015 -f -x`

Closes #445.

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [ ] Bugfix
- [x] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

## What systems has this change been tested on?

Ubuntu 20.04

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [ ] this PR is up to date with current the current state of 'develop'
- [ ] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

2022-12-13 15:47 UTC, quantumsteve commented on src/time_advance.cpp
> +                                     program_opts.solver, update_system));
Nested ternary operators are hard to read. I think an if/else tree or a switch statement would be clearer.

2022-12-13 15:48 UTC, quantumsteve commented on src/time_advance.cpp
> +                                  program_opts.solver, refining));
Nested ternary operators are hard to read. I think an if/else tree or a switch statement would be clearer.

2022-12-13 15:52 UTC, quantumsteve commented on src/time_advance.cpp
> +        A(i, j) *= -dt;
I thin that for column major order, these two loops should be interchanged.

2022-12-13 16:23 UTC, quantumsteve commented on src/time_advance.cpp
> +    expect(m.get_moment_matrix().nrows() > 0);
It would be better to explicitly remove the loop from Release builds instead of assuming it'll be optimized out.

I think you can just add the `expect(...)` line to the previous loop. Otherwise, check `NDEBUG` instead of using `expect(...)`.

2022-12-13 16:41 UTC, quantumsteve commented on src/time_advance.cpp
> +  fm::axpy(f_3s, x, (P)0.5 * dt); // f0 + 0.5*dt*apply_A(f0+f_2)
```suggestion
  fm::axpy(f_3s, x, static_cast<P>(0.5) * dt); // f0 + 0.5*dt*apply_A(f0+f_2)
```

2022-12-13 16:42 UTC, quantumsteve commented on src/time_advance.cpp
> +  fm::axpy(f_3s, x, (P)0.5 * dt);
```suggestion
  fm::axpy(f_3s, x, static_cast<P>(0.5) * dt);
```

2022-12-13 17:09 UTC, quantumsteve commented on src/transformations.cpp
> +    auto p_val = legendre(roots, degree, legendre_normalization::lin);
Can/should we use the standard library for Legendre polynomials?
https://en.cppreference.com/w/cpp/numeric/special_functions/legendre

2022-12-13 17:30 UTC, quantumsteve commented on src/transformations.cpp
> +      transform_dims > 0 ? transform_dims : pde.num_dims;
Can we avoid magic values form `transform_dims`? 

`std::optional<int>` would be more explicit but still ugly. Also, pde.num_dims goes away in #474.

I think the C++17 solution would be to pass a begin and end iterator for `std::vector<dimension<P>>`. C++20 adds std::span and ranges.

2022-12-14 14:07 UTC, ckendrick commented on src/transformations.cpp
> +    auto p_val = legendre(roots, degree, legendre_normalization::lin);
I think that would be a good idea. I'll check if our implementation matches and will swap it out if it does.

2022-12-14 15:25 UTC, quantumsteve commented on src/transformations.cpp
> +    auto p_val = legendre(roots, degree, legendre_normalization::lin);
Boost has a few more functions, including one for finding zeros.
https://www.boost.org/doc/libs/1_80_0/libs/math/doc/html/math_toolkit/sf_poly/legendre.html

2022-12-15 20:21 UTC, mkstoyanov commented on src/transformations.cpp
> +    auto p_val = legendre(roots, degree, legendre_normalization::lin);
We are not using boost, if we can avoid it. The dependence is enormous, for something as simple as root-fining.

We can pull some tricks from Tasmanian and quadrature build.

2022-12-15 20:32 UTC, mkstoyanov commented on src/transformations.cpp
> +      transform_dims > 0 ? transform_dims : pde.num_dims;
If we want to make this expressive, we can turn it into a flag. In all cases (right now), we are calling this with 1 or `pde.num_dims`. We can have an enum or `constexpt` constant that will denote `transform-one` or `transform-all` 

Also the `pde.num_dims` is not going away exactly, it will be converted to different signature, but we can keep both signatures.

2022-12-21 17:36 UTC, mkstoyanov requested changes
I hope I'm not too knit picky, the majority should be easy fixes.

Let me know if you have questions, I'm available on Teams and Slack.

2022-12-21 17:36 UTC, mkstoyanov commented on src/kronmult.cpp
> +        imex_flag const &flag)
Don't call the variable `flag`, call it `imex` instead.

The type is `imex_flag` where `imex` refers to a specific algorithm while `flag` refers to the role of the variable (flag to switch to the `imex` algorithm).

When you say just `flag` that could be a switch to pretty much anything, `imex` is the part that really matters.

Alternative names are `imex_mode` or `imex_variant`, there are other possibilities, but `imex` should be part of the name.

2022-12-21 17:36 UTC, mkstoyanov commented on src/kronmult.cpp
> +        imex_flag const &flag)
When it's just a flag, why are we passing by const-reference instead of value?

2022-12-21 17:36 UTC, mkstoyanov commented on src/kronmult.hpp
> +        imex_flag const &flag = imex_flag::exp);
Taking a reference to an enum? (I figured how it compiled, but no need to pass by ref)

I don't think imex_flag::exp is a defined variable with an address, there's some compiler trickery here.

2022-12-21 17:36 UTC, mkstoyanov commented on src/main.cpp
> +        opts.use_implicit_stepping
We can leave this for now, since this code will be deprecated eventually, but the logic is messy. Effectively, we're creating a hierarchy of flags, `implicit` means implicit, while `explicit` means either explicit or imex.

Instead of boolean flags, since we have three options, we should be reading an enum flag so that:
```
auto const method = opts.stepping_method
```

2022-12-21 17:36 UTC, mkstoyanov commented on src/main.cpp
> +    auto const time_id = asgard::tools::timer.start(time_str);
This whole section overuses `auto`, some of these are floats/doubles, some are integers, some strings or const char* ... 

`auto` is good in templates when the type changes and has to be deduced based on complex relation between template parameters, or in cases where it is both clear what `auto` means and the alternative is messy to write `for(auto x : points)` or `auto ip = points.begin()` as opposed to the iterators.

2022-12-21 17:36 UTC, mkstoyanov commented on src/matlab_utilities.cpp
> +    std::transform(sample.begin(), sample.end(), distance.begin(),
We should start writing these with `for` loops.

With all the complexity that has been added to Asgard-C++ solely for the purpose of accommodating MATLAB conversions, this is the one C++-ism that should not have been included. Math-formulas always use simple indexing, and in Math context `std::transform` should be used only to parallelize or to indicate some operation that isn't a simple math formula (e.g., apply operations to data in some link-lists, or something).

2022-12-21 17:36 UTC, mkstoyanov commented on src/matlab_utilities.cpp
> +    P min_distance = MAXFLOAT;
I always feel uneasy when I have to deal with numbers close to `MAXFLOAT`, how about:
```
P min_distance = distance[0];
int min_ind = 0;
for(int j=1; j<distance.size(); j++)
...
```

Better yet, skip the allocation of distance altogether. Merge the `std::transform()` and the for-loop into one for-loop, compute the distances on the fly and do not store them.

2022-12-21 17:36 UTC, mkstoyanov commented on src/matlab_utilities.cpp
> +template fk::vector<double> interp1(fk::vector<double> sample,
I think these should accept parameters as `const &` and not copy the values.

2022-12-21 17:36 UTC, mkstoyanov commented on src/matlab_utilities_tests.cpp
> +    std::transform(grid.begin(), grid.end(), vals.begin(),
I would `for-loop` this one too.

2022-12-21 17:36 UTC, mkstoyanov commented on src/matlab_utilities_tests.cpp
> +    fk::vector<TestType> queries{1.49, 1.51, -0.1, 4.5};
Switch the order of definitions and the blank spaces. Think of the logic:
* make the `grid`
* compute the `expected`
    * allocate `vals`
    * fill vals with `cos()` of the `grid`
    * allocate and initialize `expected`
* compute the output
    * allocate and initialize the `queries`
    * compute the `output`
* compare the `expected` and the `output`

2022-12-21 17:36 UTC, mkstoyanov commented on src/pde/pde_base.hpp
> +enum class imex_flag
Don't we already have an enum that handles all stepping types? Implicit, explicit, variations of imex? We can have a `null` type or `none` or `unknown`.

That enum type can be used in the new code also.
```
enum class stepping_flag {
  unspecified,
  implicit,
  explicit,
  imex_implicit,
  imex_explicit,
};
```
I don't like using `exp` here, it leads me to thing of `std::exp` or some other exponential operation as opposed to `explicit`.

2022-12-21 17:36 UTC, mkstoyanov commented on src/pde/pde_base.hpp
> +       imex_flag const flag_in = imex_flag::exp)
We're assigning a `default` value here, to the `imex_flag`, but how meaningful is that?

Should we not assign a default `none` value, which is obvious to ignore in non-imex cases, then force the user to be specific about `imex_flag::imp` and `imex_flag::exp` when imex is used.

2022-12-21 17:36 UTC, mkstoyanov commented on src/pde/pde_base.hpp
> +class parameter
All members are public, make it a `struct` and then you get the constructor for free.

2022-12-21 17:36 UTC, mkstoyanov commented on src/pde/pde_base.hpp
> +    std::cerr << " could not find parameter with name '" << name << "'\n";
I think you want to `throw` exception here.

2022-12-21 17:36 UTC, mkstoyanov commented on src/pde/pde_base.hpp
> +#define param_manager parameter_manager<P>::get_instance()
The new code will not use global variables masquerading as proper fancy OOP

It's OK here, since the old code is all build on globals anyway, but switch the `#define` and the `template` directives. It's really confusing to have `#define` between `template` and `class` when it the `template` relates only to the class.

2022-12-21 17:36 UTC, mkstoyanov commented on src/pde/pde_base.hpp
> +      std::cerr << " already has a parameter with name '" << param.name
`throw` exception here

2022-12-21 17:36 UTC, mkstoyanov commented on src/pde/pde_base.hpp
> +      std::cerr << "Invalid PDE choice for IMEX time advance. PDE must have "
Another `throw`

2022-12-21 17:36 UTC, mkstoyanov commented on src/pde/pde_base.hpp
> +  PDE(const PDE &pde)
**NO!** 

The signature for a copy-constructor should only ever indicate a copy-constructor. Change the signature, it's OK to pass in a type-tag or a dummy variable.

My approach would be to add a type-tag inside the PDE declaration:
```
class PDE {
...
struct extract_dim0 {};
...
}
```
Then change the constructor to have the signature:
```
PDE(const PDE &pde, extract_dim0) { ... }
```
Call the constructor with:
```
PDE pde_1d = PDE(pde, PDE::extract_dim0());
```

The same idea can  be done with an `int` and then defining `constexp int extract_dim0 = 1;`

Ideally, I would like to have an explicit template type-tag, e.g., `PDE::PDE<extract_dim0>(pde)`, but that's not added until later in the C++ standard.

2022-12-21 17:36 UTC, mkstoyanov commented on src/time_advance.cpp
> +imex_advance(PDE<P> &pde, adapt::distributed_grid<P> const &adaptive_grid,
Let's all take a moment and contemplate the meaning of `const` in a context where >90% of our data is global.

2022-12-21 17:36 UTC, mkstoyanov commented on src/time_advance.cpp
> +      for (int j = 0; j < A.ncols(); ++j)
Can we just do a BLAS `scal()` operation here, there's no stride in `A` and it can be done with a single command.

We can leave the diagonal below, since we don't want to create a dummy vector with just ones, but here we can do better.

2022-12-21 17:36 UTC, mkstoyanov commented on src/time_advance.cpp
> +  P const tolerance  = std::is_same_v<float, P> ? 1e-6 : 1e-12;
Has this been tested? This tolerance is way too brutal for `GMRES`, especially without a preconditioner.

This can be achieved only if the problem is very well conditioned, e.g., the problem is small. At the very least we should have a CLI option to overwrite this, otherwise we have to scale by the problem size somehow.

2023-01-06 16:42 UTC, mkstoyanov requested changes
Everything touched has been fixed! Making progress.

2023-01-06 16:42 UTC, mkstoyanov commented on src/main.cpp
> +    auto const time_id = asgard::tools::timer.start(time_str);
This needs fixing. First `auto` hides the type of the variable `time_str` but then the type is not `str` or `string` as it is `const char*`. The you have to double-check the code to see that `time_id` is actually `std::string`

Let's not overuse `auto`
```
const char *timer_mode = 
    opts.use_implicit_stepping
            ? "implicit_time_advance"
            : (opts.use_imex_stepping ? "imex_time_advance"
                                      : "explicit_time_advance");
std::string const time_id = asgard::tools::timer.start(timer_mode);
```

2023-01-06 16:42 UTC, mkstoyanov commented on src/pde/pde_base.hpp
> +enum class imex_flag
OK let's leave it at that for now.

2023-01-06 16:42 UTC, mkstoyanov commented on src/pde/pde_base.hpp
> +  parameter(std::string name_in, g_func_type<P> const &value_in)
I don't think the constructor is needed, when it just takes the members in the same order as defined, the compiler should automatically add this constructor.

2023-01-06 16:42 UTC, mkstoyanov commented on src/pde/pde_base.hpp
> +    std::cerr << " could not find parameter with name '" << name << "'\n";
Returning a `nullptr` will lead to an error elsewhere in the code, should just `throw` here.

2023-01-06 16:42 UTC, mkstoyanov commented on src/pde/pde_base.hpp
> +      std::cerr << "Invalid PDE choice for IMEX time advance. PDE must have "
Another `throw`

C++ should never use `exit(-1);` (maybe with some really big exception, i.e., potential security concerns, regular errors should just `throw` exceptions)

2023-01-06 16:42 UTC, mkstoyanov commented on src/time_advance.cpp
> +  P const tolerance  = std::is_same_v<float, P> ? 1e-6 : 1e-12;
We can accept this in the PR, but will need testing and adjusting.

2023-01-08 18:00 UTC, ckendrick commented on src/pde/pde_base.hpp
> +  parameter(std::string name_in, g_func_type<P> const &value_in)
I could be missing something, but I am getting compiler errors when trying to remove this.

2023-01-09 13:06 UTC, mkstoyanov commented on src/pde/pde_base.hpp
> +  parameter(std::string name_in, g_func_type<P> const &value_in)
When you invoke the compiler, the inputs should be passed in a `{ }`, e.g., in the vlassov pde file:
```
    param_manager.add_parameter(parameter<P>{"n", n});
    param_manager.add_parameter(parameter<P>{"u", u});
    param_manager.add_parameter(parameter<P>{"theta", theta});
```

2023-01-10 17:19 UTC, mkstoyanov approved these changes

2023-01-10 17:20 UTC, mkstoyanov commented
If @quantumsteve doesn't have anything to add, we can go ahead and merge.

2023-01-10 17:27 UTC, quantumsteve commented
:shipit:

2023-01-10 18:14 UTC, merged