Fix term selection option
project-asgard/asgard pull request #476
Opened 2022-12-14 14:30 UTC by ckendrick

Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

This fixes the PDE individual term selection option (`--terms`) after changes in #442. A few leftover shadowed `num_terms` are changed to use `num_terms_in` when parsing the input term string.

Some term selection examples to test:
- `./asgard -p diffusion_2 --terms "1 0"`
- `./asgard -p fokkerplanck_2d_complete_case4 --terms "1 0 1 1 0 0"`

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [x] Bugfix
- [ ] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

## What systems has this change been tested on?

Ubuntu 20.04

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [x] this PR is up to date with current the current state of 'develop'
- [x] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

2022-12-14 21:12 UTC, quantumsteve commented
May we add a test to reproduce this error?

2022-12-15 20:16 UTC, mkstoyanov approved these changes
I'm not sure if we can add a test for those, it's mostly a matter of sync between CLI and expected C++ behavior. The test will have to make a call with parameters and check the output, can be done but I'm not sure if it's worth the trouble.

2022-12-21 01:47 UTC, mkstoyanov commented on src/pde/pde_base.hpp
> +    expect(terms.size() == static_cast<unsigned>(num_terms_in));
Why do we have two `num_terms_in` and `num_terms`?

It may be just my ignorance, but why is one modified by the CLI conditions? It is extremely confusing to have both.

2022-12-21 16:14 UTC, mkstoyanov requested changes
This is confusing, let's double-check since it doesn't seem we're doing the right thing in all cases.

2022-12-21 16:14 UTC, mkstoyanov commented on src/pde/pde_base.hpp
> +      for (auto i = num_terms_in - 1; i >= 0; --i)
Are you sure about this? 

In the loop, we're modifying `active_terms(i)` which comes from the `cli_input.get_active_terms()` but you're saying that we should loop from `num_terms_in` which comes from the PDE definition and is not necessarily the CLI value.

2023-01-09 19:11 UTC, mkstoyanov commented on src/pde/pde_base.hpp
> +    expect(terms.size() == static_cast<unsigned>(num_terms_in));
Keep the `num_terms` but rename the `num_terms_in` to `max_num_terms`

2023-01-10 17:17 UTC, mkstoyanov commented on src/pde/pde_base.hpp
> +                << num_active_terms << " terms, expected " << num_terms_in
Does this compile? There are several `num_terms_in` left in the code, use an automated search to find them.

2023-01-10 18:38 UTC, mkstoyanov approved these changes

2023-01-10 18:39 UTC, mkstoyanov commented
Sorry about pushing on another branch, but I couldn't look at the `exit()` statements and the name `num_terms_in` was still confusing in the method.

2023-01-10 21:58 UTC, merged