Convert from wavelet to real space for plotting
project-asgard/asgard pull request #479
Opened 2023-01-10 21:45 UTC by quantumsteve

Signed-off-by: Steven Hahn <hahnse@ornl.gov>

Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

Describe what this PR changes and why.  If it closes an issue, link to it here
with [a supported keyword](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [ ] Bugfix
- [ ] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## What systems has this change been tested on?

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [ ] this PR is up to date with current the current state of 'develop'
- [ ] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

2023-01-10 22:33 UTC, mkstoyanov requested changes
Small notes, feel free to push back if you disagree.

2023-01-10 22:33 UTC, mkstoyanov commented on src/asgard_discretization_tests.cpp
> +  auto const real_space_size = real_solution_size(dims.list);
`real_space_size` should be replaced by just `grid.size()`

Should be the right thing to put here.

2023-01-10 22:33 UTC, mkstoyanov commented on src/matlab_plot.cpp
> +    P const max = dims[d].domain_max;
I know you're simply refactoring here, but in general, I don't like to declare a variable that would be used only one time. There is no need for max, we only need to define `min` and `rng`.

Also, both `min` and `rng` are bad names, `domain_min` and `domain_range` should work well on an editor.

2023-01-10 22:33 UTC, mkstoyanov commented on src/matlab_plot.cpp
> +        create_array({1, static_cast<size_t>(node_list.size())}, node_list);
Here we can really use some handy overloads, maybe in this or maybe in the next PR.

Since we have multiple calls to `generate_nodes()` that take the same inputs from one dim, overload so we can just say `generate_nodes(dim[i])`.

Similatly, we can have an overload to `create_array()` that default to the full `node_list` if a range is not provided. That way, the code here becomes:
```
nodes_[i] = create_array(generate_nodes(dim[i]));
```

We can also shortcut the two methods into one. Since this is called multiple times with the same pattern, it will be helpful.

2023-01-11 17:16 UTC, quantumsteve commented on src/asgard_discretization_tests.cpp
> +  auto const real_space_size = real_solution_size(dims.list);
Changing this is causing the test to fail. I need to investigate further.

2023-01-11 17:44 UTC, quantumsteve commented on src/matlab_plot.cpp
> +        create_array({1, static_cast<size_t>(node_list.size())}, node_list);
The MATLAB syntax sent me down a bit of a rabbit hole, but think think it's a bit cleaner now.

2023-01-11 17:50 UTC, mkstoyanov commented on src/asgard_discretization_tests.cpp
> +  auto const real_space_size = real_solution_size(dims.list);
This is off by a factor of 2, not sure why. I'm investigating too.

2023-01-11 17:52 UTC, quantumsteve commented on src/asgard_discretization_tests.cpp
> +  auto const real_space_size = real_solution_size(dims.list);
`real_solution_size(dims.list) == 64` while `grid.size() == 32`

2023-01-11 17:57 UTC, mkstoyanov commented on src/asgard_discretization_tests.cpp
> +  auto const real_space_size = real_solution_size(dims.list);
The `grid.size()` returns the number of degrees of freedom for the sparse grid solution.

The `real_solution_size()` returns the number of degrees of freedom for the "full" or "dense" grid. The plot picture needs the dense variables, which makes sense, but the naming convention is bad.

I want to see the word "dense", e.g., "dense_space_size", it would be much clearer of what it mean.

If `real_solution_size()` is called too many times, then leave the method alone and rename just the variable. If it is a matter of fixing 5-10 lines, let's rename the method `real_solution_size()`.

A larger rename can be done in another PR.

2023-01-11 21:31 UTC, quantumsteve commented on src/asgard_discretization_tests.cpp
> +  auto const real_space_size = real_solution_size(dims.list);
I made a first attempt at renaming variables.

2023-01-11 21:38 UTC, mkstoyanov approved these changes

2023-01-11 23:29 UTC, mkstoyanov commented
Merge when ready!

2023-01-12 01:29 UTC, merged