IMEX updates and new moment functions
project-asgard/asgard pull request #481
Opened 2023-01-18 17:20 UTC by ckendrick

Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

This fixes an issue in the IMEX time advance where the system matrix was not being updated each time step. The function to create the system matrix was also updated to only include implicit terms when using IMEX.

This PR also adds moment matrix calculations for initial support with running 1x2v and 1x3v problems.

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [x] Bugfix
- [x] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

## What systems has this change been tested on?

Ubuntu 20.04

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [x] this PR is up to date with current the current state of 'develop'
- [x] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

2023-01-18 17:28 UTC, quantumsteve commented on src/matlab_plot.cpp
> +  int d = 0;
```suggestion
  int d = dims.size();
```

2023-01-18 17:29 UTC, quantumsteve commented on src/matlab_plot.cpp
> +    d += 1;
```suggestion
    ++d;
```

2023-01-18 17:31 UTC, quantumsteve commented on src/matlab_plot.cpp
> +    d += 1;
```suggestion
    ++d;
```

2023-01-18 17:32 UTC, quantumsteve commented on src/matlab_plot.cpp
> +  auto ml_array = create_array({static_cast<size_t>(data.size()), 1}, data);
```suggestion
  auto ml_array = create_array(data);
```

2023-01-18 17:40 UTC, mkstoyanov requested changes

2023-01-18 17:40 UTC, mkstoyanov commented on src/batch.cpp
> +                         const bool use_imex, imex_flag const imex)
Why do we need two `imex` flags? When we have the `explicit`, `implicit` and `unspecified` options we can use the `unspecified` option to indicate `no-imex`.

2023-01-18 17:40 UTC, mkstoyanov commented on src/moment.cpp
> +void moment<P>::createMomentReducedMatrix_3d(PDE<P> const &pde,
At a glance, `createMomentReducedMatrix_3d()` and `createMomentReducedMatrix_4d()` have lots of repeated code. There should be a way to either generalize this, or perhaps template on "num-velocity-dims" that will take values 1, 2, 3.

Then:
* `d_dim_3` will be unused for the 2D template and the optimizer should get rid of that
* `g_vec_3` could be initialized to empty vector for the 2D case and never used
* some of the constants (e.g., 2 or 3) can be initialized from the template parameters
* the inner-most loop of the three nested three loops can be put to loop over a single entry (based on the template parameter).
* Note it is Ok to have if-statements inside for-loops when the `if` depends on a parameter that is known at compile time (e.g., template parameter)

2023-02-07 13:21 UTC, ckendrick commented on src/batch.cpp
> +                         const bool use_imex, imex_flag const imex)
Both flags are needed since this code was also being used for non-IMEX things - to make sure that all terms still get included when running without IMEX, even if the PDE has a term marked `imex_explicit` or `imex_implicit`. Additionally, `program_opts` was not being passed through, so this was also a quick fix without changing everything to pass `program_opts` (although the latest changes in `develop` have made `program_opts` available).

However, since the matrix-free changes have been merged into `develop` and this branch is now rebased to include those changes, this is no longer being used anymore. I would like to still keep it for now in case we need to temporarily change back to this. I can open an issue to remove this code in the future outside of this PR.

2023-02-07 13:27 UTC, ckendrick commented on src/moment.cpp
> +void moment<P>::createMomentReducedMatrix_3d(PDE<P> const &pde,
I consolidated these functions down into one to minimize repeated code. I can open an issue to clean it up further if needed, but this code is only meant to be temporary and will be deleted after the new version. For now, it would be good to get the rest of these changes in.

2023-02-07 16:07 UTC, quantumsteve commented on src/batch.cpp
>          kron_vals.push_back(kron0);
```suggestion
        kron_vals.push_back(std::move(kron0));
```

2023-02-07 16:08 UTC, quantumsteve commented on src/batch.cpp
>          kron_vals.push_back(kron0);
line 616 has the same issue. fk::matrix copied when it should be moved.

2023-02-07 16:20 UTC, quantumsteve commented on src/batch.cpp
> +                         const bool use_imex, imex_flag const imex)
```suggestion
                         std::optional<imex_flag> const imex)
```
Would std::optional bring us down to a single additional parameter?

2023-02-07 16:39 UTC, quantumsteve commented on src/moment.cpp
> +  }
```suggestion
    if (nvdim >= 3)
    {
      g_vec_3 = this->fList[moment_idx][3];
    }
  }
```

2023-02-07 19:39 UTC, mkstoyanov commented on src/batch.cpp
> +                         const bool use_imex, imex_flag const imex)
The only place where the flag is being used is in the line:
```
if (!use_imex || (use_imex && terms[k][0].flag == imex))
```

With my suggestion, the condition will become:
```
if (imex == imex::unspecified || terms[k][0].flag == imex)
```

What am I missing here?

2023-02-13 16:15 UTC, mkstoyanov approved these changes
Great! Let's update in case there's a conflict and we can merge.

2023-02-13 16:48 UTC, quantumsteve approved these changes

2023-02-13 19:18 UTC, merged