Add Poisson solver
project-asgard/asgard pull request #483
Opened 2023-01-23 18:02 UTC by ckendrick

Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

Adds a poisson solver to `solver` and to the IMEX time advance. A two_stream PDE was also added to test.

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [ ] Bugfix
- [x] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

## What systems has this change been tested on?

Ubuntu 20.04
## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [x] this PR is up to date with current the current state of 'develop'
- [x] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

2023-02-07 19:50 UTC, mkstoyanov requested changes

2023-02-07 19:50 UTC, mkstoyanov commented on src/main.cpp
> +  // ml_plot.plot_fval(*pde, adaptive_grid.get_table(), real_space,
Why comment as opposed to deleting the lines?

2023-02-07 19:50 UTC, mkstoyanov commented on src/moment.cpp
> +              int const ind_j = i * std::pow(deg, 3) + j * std::pow(deg, 2) +
`pow` returns a double, let's be more explicit on the `static_cast` and when we want to cast back to `int`.

2023-02-07 20:40 UTC, quantumsteve commented
```
codebuild/output/src981104754/src/github.com/project-asgard/asgard/src/lib_dispatch.cpp: In instantiation of 'void asgard::lib_dispatch::pttrf(int*, P*, P*, int*, asgard::resource) [with P = double]':
--
967 | /codebuild/output/src981104754/src/github.com/project-asgard/asgard/src/lib_dispatch.cpp:1279:68:   required from here
968 | /codebuild/output/src981104754/src/github.com/project-asgard/asgard/src/lib_dispatch.cpp:1071:12: error: 'dpttrf_' was not declared in this scope; did you mean 'dpotrf_'?
969 | 1071 \|     dpttrf_(n, D, E, info);
970 | \|     ~~~~~~~^~~~~~~~~~~~~~~
971 | \|     dpotrf_
972 | /codebuild/output/src981104754/src/github.com/project-asgard/asgard/src/lib_dispatch.cpp: In instantiation of 'void asgard::lib_dispatch::pttrf(int*, P*, P*, int*, asgard::resource) [with P = float]':
973 | /codebuild/output/src981104754/src/github.com/project-asgard/asgard/src/lib_dispatch.cpp:1281:66:   required from here
974 | /codebuild/output/src981104754/src/github.com/project-asgard/asgard/src/lib_dispatch.cpp:1075:12: error: 'spttrf_' was not declared in this scope; did you mean 'spotrf_'?
975 | 1075 \|     spttrf_(n, D, E, info);
976 | \|     ~~~~~~~^~~~~~~~~~~~~~~
977 | \|     spotrf_
978 | /codebuild/output/src981104754/src/github.com/project-asgard/asgard/src/lib_dispatch.cpp: In instantiation of 'void asgard::lib_dispatch::pttrs(int*, int*, P*, P*, P*, int*, int*, asgard::resource) [with P = double]':
979 | /codebuild/output/src981104754/src/github.com/project-asgard/asgard/src/lib_dispatch.cpp:1284:62:   required from here
980 | /codebuild/output/src981104754/src/github.com/project-asgard/asgard/src/lib_dispatch.cpp:1105:12: error: 'dpttrs_' was not declared in this scope; did you mean 'dpotrs_'?
981 | 1105 \|     dpttrs_(n, nrhs, D, E, B, ldb, info);
982 | \|     ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
983 | \|     dpotrs_
984 | /codebuild/output/src981104754/src/github.com/project-asgard/asgard/src/lib_dispatch.cpp: In instantiation of 'void asgard::lib_dispatch::pttrs(int*, int*, P*, P*, P*, int*, int*, asgard::resource) [with P = float]':
985 | /codebuild/output/src981104754/src/github.com/project-asgard/asgard/src/lib_dispatch.cpp:1286:52:   required from here
986 | /codebuild/output/src981104754/src/github.com/project-asgard/asgard/src/lib_dispatch.cpp:1109:12: error: 'spttrs_' was not declared in this scope; did you mean 'spotrs_'?
987 | 1109 \|     spttrs_(n, nrhs, D, E, B, ldb, info);
988 | \|     ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
989 | \|     spotrs_
990 | make[2]: *** [CMakeFiles/asgard_obj.dir/build.make:202: CMakeFiles/asgard_obj.dir/src/lib_dispatch.cpp.o] Error 1
991 | make[2]: *** Waiting for unfinished jobs....
992 | make[1]: *** [CMakeFiles/Makefile2:509: CMakeFiles/asgard_obj.dir/all] Error 2
993 | make: *** [Makefile:146: all] Error 2


```

2023-02-21 19:10 UTC, mkstoyanov approved these changes

2023-02-21 21:01 UTC, merged