Sum of separable functions for analytical solutions
project-asgard/asgard pull request #495
Opened 2023-02-07 14:35 UTC by ckendrick

Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

This changes how analytical solutions are specified in the PDE to be a sum of separable functions rather than just a single function.

Closes #488

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [ ] Bugfix
- [x] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

## What systems has this change been tested on?

Ubuntu 20.04

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [x] this PR is up to date with current the current state of 'develop'
- [x] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

2023-02-07 19:33 UTC, mkstoyanov requested changes

2023-02-07 19:33 UTC, mkstoyanov commented on src/transformations.hpp
> +    std::vector<md_func_type<P>> const &funcs,
Instead of changing every single PDE file, why don't we add an overload to this that will accept single-instance parameters and then convert those into vectors with one entry.

2023-02-13 16:30 UTC, ckendrick commented on src/transformations.hpp
> +    std::vector<md_func_type<P>> const &funcs,
I think we would need to also overload the PDE constructor to make this work. This PR is changing the definition of `exact_vector_funcs` in the PDE class to be a vector of vectors of functions, which is how it should have been originally.

2023-02-13 16:39 UTC, mkstoyanov commented on src/transformations.hpp
> +    std::vector<md_func_type<P>> const &funcs,
You're right, we would need a few overloads, but the end-result would be much cleaner. 

The user will make a single function when one function is needed and a vector when it is needed. The overload(s) will handle both cases but simply adding a conversion layer of putting the single function into a vector and passing on.

2023-02-21 19:06 UTC, mkstoyanov submitted a review, later dismissed

2023-03-01 08:52 UTC, mkstoyanov approved these changes

2023-03-01 18:03 UTC, merged