Added penalty term to PDE operator.  Still needs to be added to BCs
project-asgard/asgard pull request #497
Opened 2023-02-08 16:27 UTC by stefan-schnake

Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

Describe what this PR changes and why.  If it closes an issue, link to it here
with [a supported keyword](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [ ] Bugfix
- [x] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [ x] No

## What systems has this change been tested on?

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [ ] this PR is up to date with current the current state of 'develop'
- [ ] code added or changed in the PR has been clang-formatted
- [x] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [x] documentation has been added (if appropriate)

2023-02-08 17:58 UTC, quantumsteve commented
@stefan-schnake I added your github id to AWS CodeBuild. All the builds should run on your next push.

2023-02-08 18:37 UTC, mkstoyanov commented on src/basis.cpp
> +wavelet_transform<P, resrc>::wavelet_transform(int const max_level_in,
You don't want this to be controlled by the command line options?

2023-02-08 18:40 UTC, mkstoyanov commented on src/coefficients.cpp
> +      else if (pterm.coeff_type == coefficient_type::penalty)
Get rid of the code and leave just a comment:
```
// in the case when pterm.coeff_type == coefficient_type::penalty
// the output is zeros (no volume term)
```

2023-02-08 18:40 UTC, mkstoyanov commented on src/coefficients.cpp
> +      // (values at the left and right of each element for all k).
Get rid of the dot in the end of the line

2023-02-08 18:43 UTC, mkstoyanov commented on src/coefficients.cpp
> +      // In this case:  {f} = p_R/2, [f] = p_R, [v] = -p_L
Maybe a knit-pick, but `[f]` is standard notation, but is `{f}` standard and how do we differentiate from `I_{i-1}`?

2023-02-08 18:51 UTC, mkstoyanov commented
@stefan-schnake I don't like the if-statements inside for-loops, but fixing this with templates is not obvious. The original code uses such if-statement, which is also not ideal. Probably needs a refactor, but doesn't have to happen in this PR.

The other comments are minor.

2023-02-08 18:53 UTC, quantumsteve requested changes

2023-02-08 18:53 UTC, quantumsteve commented on src/coefficients.cpp
> +      }
```suggestion
P const central_coeff = pterm.coeff_type == coefficient_type::penalty ? 0.0 : 1.0;
```

2023-02-08 18:53 UTC, quantumsteve commented on src/coefficients.cpp
> +      }
```suggestion
        // output is zeros (no volume term)
```

2023-02-08 18:53 UTC, quantumsteve commented on src/coefficients.cpp
> +      }
I suspect the optimizer will eliminate this branch.

2023-02-08 18:54 UTC, quantumsteve commented on src/basis.cpp
> +wavelet_transform<P, resrc>::wavelet_transform(int const max_level_in,
@mkstoyanov `max_level_in` comes from program_opts. Like we did with `PDE`, we added wrapper for the "old" API.

2023-02-08 18:58 UTC, mkstoyanov commented on src/coefficients.cpp
> +      }
It will, but it is still ugly to look at, a comment is enough without the code.

2023-02-08 19:00 UTC, mkstoyanov commented on src/coefficients.cpp
> +      }
I want to make it clear that we are referring to the penalty case, I think the comment should be more verbose.

2023-02-14 21:14 UTC, stefan-schnake commented on src/coefficients.cpp
> +      // (values at the left and right of each element for all k).
Done

2023-02-14 21:17 UTC, stefan-schnake commented on src/coefficients.cpp
> +      // In this case:  {f} = p_R/2, [f] = p_R, [v] = -p_L
I replaced [f] with [[f]] and {f} with {{f}}.   The new notation is commonly used in DG for jumps and averages.

2023-02-14 21:23 UTC, mkstoyanov commented on src/coefficients.cpp
> +      // (values at the left and right of each element for all k).
Are you sure? It's showing as a dot

2023-02-14 21:26 UTC, stefan-schnake commented on src/coefficients.cpp
> +      // (values at the left and right of each element for all k).
I have not pushed the change yet.  I don't know the order of operations on these commenting tools, lol

2023-02-14 21:37 UTC, mkstoyanov commented on src/coefficients.cpp
> +      // (values at the left and right of each element for all k).
Yeah, you have to kind of keep a separate list. When you comment, I immediately get an e-mail and when I read "done" I expect "done". This can quickly get confusingly out of hand.

What you can do instead is react, with a thumbs up before you make the fixes and push them.

After push, comment `done` and leave the comment open, so the reviewer can see it and remember what was this all about. The reviewer can (should) close it and update the review or just merge the PR.

2023-02-15 02:00 UTC, mkstoyanov approved these changes

2023-02-15 02:02 UTC, mkstoyanov commented
Just have to fix the formatting, it's easy once you have it set.

If @quantumsteve can't help you, I will show you how to automate it on Friday.

2023-02-15 15:19 UTC, quantumsteve commented on src/pde/pde_base.hpp
> +  void operator=(parameter_manager<P> const &)    = delete;
```suggestion
  void operator=(parameter_manager<P> const &)  = delete;
```

2023-02-15 21:38 UTC, mkstoyanov commented
Hey @quantumsteve, let me know when you get sick and tired of clang-format and decide to remove it or at lest relax some of the more outrageous rules (e.g., 80 character lines) :smile:

2023-02-16 17:10 UTC, quantumsteve commented
@mkstoyanov I'd approve a change to the 80-character line limit, and could happily consider other potential improvements. At the same time I don't want to go back to when formatting was a significant part of code review.

2023-02-21 21:01 UTC, quantumsteve approved these changes

2023-02-22 01:22 UTC, merged