dv_func: use nullptr instead of null_gfunc
project-asgard/asgard pull request #504
Opened 2023-02-21 19:02 UTC by quantumsteve

Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

Describe what this PR changes and why.  If it closes an issue, link to it here
with [a supported keyword](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

We need some way to differentiate `partial_term<precision>::null_gfunc` from another function. The easiest option is to allow 

This is part of #493.

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [ ] Bugfix
- [x] New feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

## What systems has this change been tested on?

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [x] this PR is up to date with current the current state of 'develop'
- [x] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

2023-02-22 20:21 UTC, mkstoyanov requested changes
Maybe I'm missing the larger picture, is this meant to be part of a bigger change?

2023-02-22 20:21 UTC, mkstoyanov commented on src/boundary_conditions.cpp
> +  if (!g_func)
I'm failing to see the idea here? Why replace null gfunc with `partial_term<P>::null_gfunc` which returns `1.0`, I though we wanted to replace `null_gfunc` with checks for `nullptr`.

2023-02-22 20:21 UTC, mkstoyanov commented on src/boundary_conditions.cpp
> +  expect(g_func);
This can never fail since `g_func` was set in the line above.

2023-02-22 20:21 UTC, mkstoyanov commented on src/boundary_conditions.cpp
> +      g = partial_term<P>::null_gfunc;
Another expect `g` and setting `g` to `null_gfunc`

2023-02-22 20:32 UTC, quantumsteve commented on src/coefficients.cpp
> +          if (partial_terms[k].dv_func || partial_terms[k].g_func)
@mkstoyanov Here's where I'm checking if `partial_terms[k].dv_func` or `partial_terms[k].g_func` are defined and skipping the call to `fm::gesv` if either are.

2023-02-22 22:39 UTC, quantumsteve commented on src/boundary_conditions.cpp
> +  if (!g_func)
I've now fully removed `partial_term<P>::null_gfunc` from ASGarD.

2023-02-22 22:39 UTC, quantumsteve commented on src/boundary_conditions.cpp
> +  expect(g_func);
removed

2023-02-22 22:40 UTC, quantumsteve commented on src/boundary_conditions.cpp
> +      g = partial_term<P>::null_gfunc;
I've now fully removed partial_term<P>::null_gfunc from ASGarD.

2023-02-22 23:09 UTC, mkstoyanov submitted a review, later dismissed

2023-02-23 00:19 UTC, mkstoyanov approved these changes

2023-02-23 00:26 UTC, merged