Add collisional landau pde
project-asgard/asgard pull request #511
Opened 2023-03-06 17:31 UTC by ckendrick

Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

- Adds the collisional landau damping PDE
- Expands on adding additional data (E field, moments) and metadata (nodes for each dimension, levels, degree, pde info) to the HDF5 output files. The electric field is now stored as a member variable in the PDE class as a result.
- Saves GMRES iteration counts (inner, outer) and error to HDF5 files.
- Adds more performance timers to the IMEX advance and across the code. These are mainly meant to be temporary to show areas for optimization later.
- Fixes a bug in the `vlasov_lb_full_f` pde where the wrong imex flag was used.

This should be merged after #496. 

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [x] Bugfix
- [x] New feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

## What systems has this change been tested on?

Ubuntu 20.04

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [x] this PR is up to date with current the current state of 'develop'
- [x] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

2023-03-07 16:26 UTC, quantumsteve commented on src/time_advance.cpp
> +    auto mom0_real = pde.moments[0].create_realspace_moment(
`moment::create_realspace_moment` returns a const reference but using `auto` creates a copy.

2023-03-07 16:29 UTC, quantumsteve commented on src/time_advance.cpp
>      param_manager.get_parameter("n")->value = [mom0_real](P const x_v,
Since we're making another copy in this lambda capture, should create_realspace_moment return by value and we do a move capture here?

2023-03-28 21:57 UTC, mkstoyanov commented on src/time_advance.cpp
> +    auto mom0_real = pde.moments[0].create_realspace_moment(
Overall the code uses `auto` rather excessively, even for thing like `int` and `double`.

`auto` is OK when used appropriately and in moderation, but it is relevant for the coders to know when something is a matrix, vector, pointer or reference. It also helps the compiler catch problems.

2023-03-28 21:59 UTC, mkstoyanov commented on src/time_advance.cpp
>      param_manager.get_parameter("n")->value = [mom0_real](P const x_v,
If we change the earlier code to return a reference, then we should capture by reference here.

2023-03-28 22:00 UTC, mkstoyanov commented on src/time_advance.cpp
>      param_manager.get_parameter("n")->value = [mom0_real](P const x_v,
This is a pattern in many places.

2023-03-29 18:37 UTC, mkstoyanov requested changes

2023-03-29 18:37 UTC, mkstoyanov commented on src/time_advance.cpp
> +      [&mom0_real = mom0_real](P const x_v, P const t = 0) -> P {
This creates the illusion of a shadow, just use `[&](P const x_v)` there's no need to say `[&mom0_real = mom0_real]`

It's repeated in several places.

2023-03-29 18:37 UTC, mkstoyanov commented on src/pde/pde_collisional_landau.hpp
> +    std::transform(
I really think we should stop using `transform` in these, a user has to know about iterators, lambdas and capture to understand the code. Isn't it much easier:
```
for(int i=0; i<x.size(); i++){
    fx[i] = coefficient * std::exp(-0.5 * (1.0 / theta_in) * std::pow(x[i], 2));
}
```

2023-03-29 18:37 UTC, mkstoyanov commented on src/pde/pde_collisional_landau.hpp
> +    std::transform(
Don't have to change it now, but it's probably better for switch the use for the future.

2023-03-29 18:37 UTC, mkstoyanov commented on src/pde/pde_collisional_landau.hpp
> +  static P MaxAbsE(P const &x, P const t = 0)
Is this one used?

2023-03-29 18:37 UTC, mkstoyanov commented on src/pde/pde_collisional_landau.hpp
> +    return (6.0 - (-6.0)) / std::pow(2, 3);
Comment says ` (Lmax - Lmin) / 2 ^ LevX * CFL` but the expression is missing the CFL. I think we should update the comment, replace `std::pow(2, 3)` by `8`, and maybe comment that `2^LevX = 8`.

2023-03-29 18:37 UTC, mkstoyanov commented on src/pde/pde_collisional_landau.hpp
> +    return (x < 0.0) ? x : 0.0;
Is it better to say `return std::min(x, 0.0);`

Not sure, your call.

2023-03-29 19:00 UTC, quantumsteve commented on src/pde/pde_collisional_landau.hpp
> +    return (x < 0.0) ? x : 0.0;
std::min requires `x` and `0.0` to be the same type. Something like the suggestion below should work.
```suggestion
    return std::min(x, P{0.0});
```

2023-03-29 19:02 UTC, ckendrick commented on src/pde/pde_collisional_landau.hpp
> +    return (x < 0.0) ? x : 0.0;
This is already done in the next PR: https://github.com/project-asgard/asgard/pull/512/commits/1d913b57a8c08cf8634f6d90586932eb898be361

2023-03-29 19:03 UTC, ckendrick commented on src/pde/pde_collisional_landau.hpp
> +  static P MaxAbsE(P const &x, P const t = 0)
It is used in the poisson update in the imex advance: https://github.com/project-asgard/asgard/blob/develop/src/time_advance.cpp#L509

2023-03-29 19:07 UTC, mkstoyanov commented on src/pde/pde_collisional_landau.hpp
> +    return (x < 0.0) ? x : 0.0;
We should not have let these linger for so long.

2023-03-29 19:08 UTC, mkstoyanov commented on src/pde/pde_collisional_landau.hpp
> +  static P MaxAbsE(P const &x, P const t = 0)
The parameter with string ID `MaxAbsE` is used in several places, but I cannot find a place where this method is called.

2023-03-29 19:43 UTC, ckendrick commented on src/pde/pde_collisional_landau.hpp
> +    return (6.0 - (-6.0)) / std::pow(2, 3);
The comment above this says this will be scaled by the CFL from the command line.
I will update the comment and `pow`. This function is never used at the moment.

2023-03-29 19:48 UTC, ckendrick commented on src/pde/pde_collisional_landau.hpp
> +  static P MaxAbsE(P const &x, P const t = 0)
The string ID gets mapped to this function [here](https://github.com/ckendrick/asgard/blob/collisional_landau_io/src/pde/pde_collisional_landau.hpp#L28). The function is wrapped in a gfunc for a partial term [here](https://github.com/ckendrick/asgard/blob/collisional_landau_io/src/pde/pde_collisional_landau.hpp#L290-L295). In the time advance we use the string ID to update the function which then gets used next time the coefficients are generated.

2023-03-29 20:10 UTC, mkstoyanov commented on src/pde/pde_collisional_landau.hpp
> +  static P MaxAbsE(P const &x, P const t = 0)
Yes, I missed that. Don't want to waste time, but this brings couple of questions:

* if the `MaxAbsE` parameter is never updated, then there's no point to have it as a `parameter` and it can be hard-coded in `MaxAbsE_func`
* if it is updated, then this is just an initial value and we can use a lambda expression in initialization, as opposed to making these static functions that will be used in only one iteration

2023-03-29 20:15 UTC, ckendrick commented on src/pde/pde_collisional_landau.hpp
> +  static P MaxAbsE(P const &x, P const t = 0)
It does get updated every time step, but yes, this function is just used to set the initial value (same for all the other `parameter` functions defined in the PDE). I agree we can do something better for initialization.

2023-03-31 13:19 UTC, mkstoyanov requested changes
Actually, my comments are minor, so it's OK to override this and merge.

So long as we keep the show going.

2023-03-31 13:19 UTC, mkstoyanov commented on src/coefficients.cpp
> +  tools::timer.start("gen_coefficients");
Speaking of performance, do we have an option that will turn these into no-op?

Not a big deal, but still something.

2023-03-31 13:19 UTC, mkstoyanov commented on src/solver.cpp
> +                       int const inner_iters) -> gmres_info<P> {
Why not override the `operator <<` for the `gmres_info` struct, then we can have this output anywhere that we may need it.

Over the long run, we want ASGard to be mostly silent and we want to give the user the ability to fine-grain the CLI output. Also, `std::cout` is not exactly MPI friendly.

2023-03-31 13:19 UTC, mkstoyanov commented on src/pde/pde_collisional_landau.hpp
> +  static P MaxAbsE(P const &x, P const t = 0)
Are we going to convert the initializations to lambdas or are we skipping it for this PR?

2023-03-31 15:20 UTC, ckendrick commented on src/pde/pde_collisional_landau.hpp
> +  static P MaxAbsE(P const &x, P const t = 0)
If it is ok with you, it might be best to skip for this PR. I will open an issue to fix this, but for now I think it is best to get this in

2023-03-31 15:22 UTC, ckendrick commented on src/coefficients.cpp
> +  tools::timer.start("gen_coefficients");
That is a good question. As far as I know, I don't believe there is currently a way to do that. We could pull this into a compile flag that disables it, similar to how we handle `expect` statements: https://github.com/project-asgard/asgard/blob/01016aa01129e560a14093b557e2b7f2c4c17ab0/src/tools.hpp#L15-L19

I can open an issue for this.

2023-03-31 15:29 UTC, ckendrick commented on src/solver.cpp
> +                       int const inner_iters) -> gmres_info<P> {
That is a good point, I will do that in a separate PR. 
I agree `std::cout` needs to either be replaced with `node_out()` or just get removed, and we can report back in `main` when needed now that we are returning all the information.
I believe this GMRES implementation was more of an exploratory work, and was not written with MPI in mind. It may be worth revisiting this entire routine for MPI.

2023-03-31 16:17 UTC, mkstoyanov commented on src/coefficients.cpp
> +  tools::timer.start("gen_coefficients");
Yes, let's open an issue. You can assign it to me.

2023-03-31 16:19 UTC, mkstoyanov commented on src/solver.cpp
> +                       int const inner_iters) -> gmres_info<P> {
Putting MPI in GMRES will be a challenge, but at least we won't be making it any harder with hard-coded `std::cout`.

Another PR!

2023-03-31 16:19 UTC, mkstoyanov approved these changes

2023-03-31 16:20 UTC, mkstoyanov commented
@ckendrick unless @quantumsteve object, go ahead and merge.

2023-03-31 16:20 UTC, quantumsteve approved these changes

2023-03-31 16:21 UTC, merged