added option for mixed sg-full grid
project-asgard/asgard pull request #513
Opened 2023-03-20 21:30 UTC by mkstoyanov

Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

Describe what this PR changes and why.  If it closes an issue, link to it here
with [a supported keyword](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## What type(s) of changes does this code introduce?
Added option to mix sparse grid and full grid by breaking the dimensions into two groups and using sparse grid within each group and dense between the two groups.

- [ ] Bugfix
- [x] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

## What systems has this change been tested on?

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [x] this PR is up to date with current the current state of 'develop'
- [x] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [x] documentation has been added (if appropriate)

2023-03-21 19:03 UTC, quantumsteve commented on src/program_options.cpp
> +          "Dimension group size for first spars grid in the mixed sparse-dense "
```suggestion
          "Dimension group size for first sparse grid in the mixed sparse-dense "
```

2023-03-23 13:26 UTC, quantumsteve requested changes
Let's create a default value that uses `parser::NO_USER_VALUE` and use that in place of `-1`.

2023-03-23 13:26 UTC, quantumsteve commented on src/adapt_tests.cpp
> +  auto const mixed_grid_group = -1;
```suggestion
  auto const mixed_grid_group = parser::DEFAULT_MIXED_GRID_GROUP;
```

2023-03-23 13:26 UTC, quantumsteve commented on src/adapt_tests.cpp
> +  auto const mixed_grid_group = -1;
```suggestion
  auto const mixed_grid_group = parser::DEFAULT_MIXED_GRID_GROUP;
```

2023-03-23 13:26 UTC, quantumsteve commented on src/adapt_tests.cpp
> +  auto const mixed_grid_group = -1;
```suggestion
  auto const mixed_grid_group = parser::DEFAULT_MIXED_GRID_GROUP;
```

2023-03-23 13:26 UTC, quantumsteve commented on src/adapt_tests.cpp
> +  auto const mixed_grid_group = -1;
```suggestion
  auto const mixed_grid_group = parser::DEFAULT_MIXED_GRID_GROUP;
```

2023-03-23 13:26 UTC, quantumsteve commented on src/adapt_tests.cpp
> +  auto const mixed_grid_group = -1;
```suggestion
  auto const mixed_grid_group = parser::DEFAULT_MIXED_GRID_GROUP;
```

2023-03-23 13:26 UTC, quantumsteve commented on src/kronmult_tests.cpp
> +                parser::DEFAULT_USE_FG, parser::DEFAULT_MAX_LEVEL, -1,
```suggestion
                parser::DEFAULT_USE_FG, parser::DEFAULT_MAX_LEVEL, parser::DEFAULT_MIXED_GRID_GROUP,
```

2023-03-23 13:26 UTC, quantumsteve commented on src/moment_tests.cpp
> +                     parser::DEFAULT_MAX_LEVEL, -1, num_steps, use_implicit,
```suggestion
                     parser::DEFAULT_MAX_LEVEL, parser::DEFAULT_MIXED_GRID_GROUP, num_steps, use_implicit,
```

2023-03-23 13:26 UTC, quantumsteve commented on src/moment_tests.cpp
> +                     parser::DEFAULT_MAX_LEVEL, -1, num_steps, use_implicit,
```suggestion
                     parser::DEFAULT_MAX_LEVEL, parser::DEFAULT_MIXED_GRID_GROUP, num_steps, use_implicit,
```

2023-03-23 13:26 UTC, quantumsteve commented on src/program_options.cpp
> +          "integer < num dimensions")["-mgg"]["--mixed_grid_group"](
The short option may only be one character
https://github.com/project-asgard/asgard/pull/510#discussion_r1126690429

2023-03-23 13:26 UTC, quantumsteve commented on src/program_options.hpp
> +      int const mixed_grid_group_in        = -1,
```suggestion
      int const mixed_grid_group_in        = DEFAULT_MIXED_GRID_GROUP,
```
around line 185, add 
```
static auto constexpr DEFAULT_MIXED_GRID_GROUP = NO_USER_VALUE
```

2023-03-23 13:26 UTC, quantumsteve commented on src/program_options.hpp
> +  int mixed_grid_group = -1;
```suggestion
  int mixed_grid_group = DEFAULT_MIXED_GRID_GROUP;
```

2023-03-23 13:26 UTC, quantumsteve commented on src/solver_tests.cpp
> +                parser::DEFAULT_USE_FG, parser::DEFAULT_MAX_LEVEL, -1,
```suggestion
                parser::DEFAULT_USE_FG, parser::DEFAULT_MAX_LEVEL, parser::DEFAULT_MIXED_GRID_GROUP,
```

2023-03-23 13:26 UTC, quantumsteve commented on src/time_advance_tests.cpp
> +        cfl, full_grid, parser::DEFAULT_MAX_LEVEL, -1, num_steps);
```suggestion
        cfl, full_grid, parser::DEFAULT_MAX_LEVEL, parser::DEFAULT_MIXED_GRID_GROUP, num_steps);
```
repeat change for other instances of `-1` in this file.

2023-03-24 00:51 UTC, mkstoyanov commented
I rewrote the parser, now we can make changes entry by entry. I also redid a bunch of the use cases.

Still ugly, but should be at least an improvement.

2023-03-24 02:20 UTC, quantumsteve commented on src/program_options.hpp
> +  enum parser_option_entry
I think this can be an `enum class`

2023-03-24 02:21 UTC, quantumsteve approved these changes
Other than the comment about making an `enum` an `enum class`, LGTM.

2023-03-24 14:06 UTC, mkstoyanov commented on src/program_options.hpp
> +  enum parser_option_entry
This is already inside a class and has to be addressed with `parser_mod::cli`, adding `enum class` will only add another layer of indirection: `parser_mod::parser_option_entry::cli` or moving the `enum` outside will the class will pollute the namespace with yet one more name.

2023-03-24 14:20 UTC, quantumsteve commented on src/program_options.hpp
> +  enum parser_option_entry
My goal was just to provide a bit more type-safety. Not worth adding adding at the expense of another level of indirection.

2023-03-24 14:28 UTC, merged