Remove old kronmult library. Fall back to CPU implementation.
project-asgard/asgard pull request #537
Opened 2023-04-27 02:14 UTC by quantumsteve

Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

Describe what this PR changes and why.  If it closes an issue, link to it here
with [a supported keyword](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

This removes the older, slower kronmult library. In the (rare?) case that a GPU kernel is not available it falls back to a CPU kernel.

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [ ] Bugfix
- [ ] New feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] Documentation content changes
- [x] Other (please describe): remove rarely used library  

### Does this introduce a breaking change?

- [x] Yes
- [ ] No

In rare cases an input that ran on the GPU may now fall back to the CPU.

## What systems has this change been tested on?

my laptop, Ubuntu 20.04

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [x] this PR is up to date with current the current state of 'develop'
- [x] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

2023-04-27 11:23 UTC, mkstoyanov commented on src/device/kronmult_cuda.cpp
> +  if (kronmult::is_implemented::gpu(num_dims, n))
I was using the old implementation as a fallback for unimplemented `n` I think we should just remove the `is_implemented` struct in `asgard_kronmult.hpp` and here we should just call `execute_gpu()`

The `execute_gpu()` will throw and error if called with incorrect  size.

If you want to use the CPU as a fallback you run into the problem that the data is already loaded on the GPU and will have to be moved back. I think it's OK to throw and in this PR or another we can have a runtime option (command line) to skip the GPU.

What do you think?

2023-04-27 11:25 UTC, mkstoyanov commented
Somewhere in ASGarD we are also reporting `workspace` size. We should remove that one too, as it is confusing. (I didn't see it removed in the PR)

2023-04-27 15:45 UTC, quantumsteve commented
> Somewhere in ASGarD we are also reporting `workspace` size. We should remove that one too, as it is confusing. (I didn't see it removed in the PR)

I removed the factor of 2. The `element_x` array still uses the workspace size. If we can remove that array, it should be in a separate PR.

2023-04-27 15:46 UTC, quantumsteve commented on src/device/kronmult_cuda.cpp
> +  if (kronmult::is_implemented::gpu(num_dims, n))
:facepalm: The code now checks and throws and exception.

2023-04-28 01:19 UTC, mkstoyanov requested changes

2023-04-28 01:19 UTC, mkstoyanov commented on src/device/kronmult_cuda.cpp
> +    throw std::runtime_error("Kronmult GPU kernel not implemented for degree " +
I wasn't clear before, `execute_gpu()` already does the throw. This block should have just the call to execute and the device synch.

The only reason why `is_implemented` was there was to send the unimplemented cases to the old kronmult so the tests wouldn't be failing while I was building the cases.

2023-04-28 01:19 UTC, mkstoyanov commented on src/kronmult_tests.cpp
> +    auto const degree            = 2;
Why the change to the test?

2023-04-28 01:19 UTC, mkstoyanov commented on src/solver_tests.cpp
> +    auto const degree            = 2;
Same here, why?

2023-04-28 01:21 UTC, mkstoyanov commented
So, ignoring the non-RAII memory management in `kronmult_tests.cpp`, do you know why they were reading the workspace back to the host?

2023-04-28 01:25 UTC, quantumsteve commented on src/kronmult_tests.cpp
> +    auto const degree            = 2;
An exception was being thrown (no n=1 gpu implementation?)

2023-04-28 02:17 UTC, mkstoyanov commented on src/kronmult_tests.cpp
> +    auto const degree            = 2;
`asgard_kronmult.cpp` has a d=6 n=1 case implemented (line 391) and there is a test in `asgard_kronmult_tests.cpp` on line 143. What's missing is the `asgard_kronmult.hpp` available in the set (number 106).

The whole `is_implemented` was an ugly hack and should go away (see the earlier comment). That should also fix the test.

2023-04-28 14:58 UTC, quantumsteve commented on src/device/kronmult_cuda.cpp
> +    throw std::runtime_error("Kronmult GPU kernel not implemented for degree " +
removed

2023-04-28 14:58 UTC, quantumsteve commented on src/kronmult_tests.cpp
> +    auto const degree            = 2;
`is_implemented` has been removed

2023-04-28 18:01 UTC, quantumsteve commented
> So, ignoring the non-RAII memory management in `kronmult_tests.cpp`, do you know why they were reading the workspace back to the host?

It looks like someone wanted to use an existing lambda expression instead of writing a CUDA kernel :man_shrugging:

2023-04-29 00:49 UTC, mkstoyanov approved these changes

2023-04-29 00:51 UTC, mkstoyanov commented
I want the old kronmult tests gone too, but you can leave the pleasure for me for when I come back.

2023-04-29 02:17 UTC, merged