Adjust loop order, simd pragma
project-asgard/asgard pull request #539
Opened 2023-05-08 21:20 UTC by quantumsteve

Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

Describe what this PR changes and why.  If it closes an issue, link to it here
with [a supported keyword](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

- Adding `-march=native` to our suggested CXXFLAGS which allows for SIMD instructions beyond SSE2
- Reordering loops to maximize when memory is accessed sequentially (I suspect the compiler can/is also reordering loops)
  - I adjusted `j` ignoring `lda` in hope that we can rearrange those matrices in a future PR.  
- Using `#pragma omp simd` generates [FMA3 instructions](https://en.wikipedia.org/wiki/FMA_instruction_set).
- Fixing precision errors cause by adding `-march=native`

this branch
```
svh@PC102795:~/Documents/asgard/build$ OMP_PROC_BIND=close OMP_NUM_THREADS=20 ./asgard-kronmult-benchmark 2 4 4096 12288 1000
benchmarking:
dimensions: 2  n: 4  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 6.556 seconds.
single precision: 180.3850 Gflops / second.
double precision: 112.0134 Gflops / second.
svh@PC102795:~/Documents/asgard/build$ OMP_PROC_BIND=close OMP_NUM_THREADS=20 ./asgard-kronmult-benchmark 3 4 4096 12288 1000
benchmarking:
dimensions: 3  n: 4  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 8.522 seconds.
single precision: 145.1275 Gflops / second.
double precision: 92.5695 Gflops / second.
svh@PC102795:~/Documents/asgard/build$ OMP_PROC_BIND=close OMP_NUM_THREADS=20 ./asgard-kronmult-benchmark 4 4 4096 12288 1000
benchmarking:
dimensions: 4  n: 4  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 10.329 seconds.
single precision: 224.7669 Gflops / second.
double precision: 152.4232 Gflops / second.
svh@PC102795:~/Documents/asgard/build$ OMP_PROC_BIND=close OMP_NUM_THREADS=20 ./asgard-kronmult-benchmark 2 2 4096 12288 1000
benchmarking:
dimensions: 2  n: 2  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 6.558 seconds.
single precision: 45.6006 Gflops / second.
double precision: 19.2957 Gflops / second.
svh@PC102795:~/Documents/asgard/build$ OMP_PROC_BIND=close OMP_NUM_THREADS=20 ./asgard-kronmult-benchmark 3 2 4096 12288 1000
benchmarking:
dimensions: 3  n: 2  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 8.484 seconds.
single precision: 127.6913 Gflops / second.
double precision: 64.9877 Gflops / second.
svh@PC102795:~/Documents/asgard/build$ OMP_PROC_BIND=close OMP_NUM_THREADS=20 ./asgard-kronmult-benchmark 4 2 4096 12288 1000
benchmarking:
dimensions: 4  n: 2  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 10.284 seconds.
single precision: 130.9308 Gflops / second.
double precision: 118.2861 Gflops / second.
svh@PC102795:~/Documents/asgard/build$ OMP_PROC_BIND=close OMP_NUM_THREADS=20 ./asgard-kronmult-benchmark 6 2 4096 12288 1000
benchmarking:
dimensions: 6  n: 2  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 13.124 seconds.
single precision: 75.4268 Gflops / second.
double precision: 63.8377 Gflops / second.
```

develop
```
$ OMP_PROC_BIND=close OMP_NUM_THREADS=20 ./asgard-kronmult-benchmark 2 4 4096 12288 1000
benchmarking:
dimensions: 2  n: 4  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 6.837 seconds.
single precision: 61.9943 Gflops / second.
double precision: 78.9516 Gflops / second.
svh@PC102795:~/Documents/asgard/build$ OMP_PROC_BIND=close OMP_NUM_THREADS=20 ./asgard-kronmult-benchmark 3 4 4096 12288 1000
benchmarking:
dimensions: 3  n: 4  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 9.206 seconds.
single precision: 107.7183 Gflops / second.
double precision: 55.1977 Gflops / second.
svh@PC102795:~/Documents/asgard/build$ OMP_PROC_BIND=close OMP_NUM_THREADS=20 ./asgard-kronmult-benchmark 4 4 4096 12288 1000
benchmarking:
dimensions: 4  n: 4  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 10.953 seconds.
single precision: 185.6154 Gflops / second.
double precision: 108.5053 Gflops / second.
svh@PC102795:~/Documents/asgard/build$ OMP_PROC_BIND=close OMP_NUM_THREADS=20 ./asgard-kronmult-benchmark 2 2 4096 12288 1000
benchmarking:
dimensions: 2  n: 2  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 6.695 seconds.
single precision: 80.1699 Gflops / second.
double precision: 25.4522 Gflops / second.
svh@PC102795:~/Documents/asgard/build$ OMP_PROC_BIND=close OMP_NUM_THREADS=20 ./asgard-kronmult-benchmark 3 2 4096 12288 1000
benchmarking:
dimensions: 3  n: 2  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 9.074 seconds.
single precision: 73.9265 Gflops / second.
double precision: 48.2701 Gflops / second.
svh@PC102795:~/Documents/asgard/build$ OMP_PROC_BIND=close OMP_NUM_THREADS=20 ./asgard-kronmult-benchmark 4 2 4096 12288 1000
benchmarking:
dimensions: 4  n: 2  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 10.418 seconds.
single precision: 72.4156 Gflops / second.
double precision: 59.6082 Gflops / second.
svh@PC102795:~/Documents/asgard/build$ OMP_PROC_BIND=close OMP_NUM_THREADS=20 ./asgard-kronmult-benchmark 6 2 4096 12288 1000
benchmarking:
dimensions: 6  n: 2  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 14.111 seconds.
single precision: 110.1744 Gflops / second.
double precision: 52.2424 Gflops / second.
```

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [ ] Bugfix
- [ ] New feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

## What systems has this change been tested on?

My workstation, Ubuntu 22.04

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [x] this PR is up to date with current the current state of 'develop'
- [x] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

2023-05-09 14:55 UTC, mkstoyanov commented on CMakeLists.txt
> +  set (RECOMMENDED_CXXFLAGS "-march=native -Wall -Wextra -Wpedantic -Wshadow")
This increases compilation time and is pointless if using the GPU.

Let's talk about this at the meeting today, without `native` you still get the 128-bit extensions by default and even that will boost performance.

2023-05-09 15:00 UTC, mkstoyanov commented on src/device/asgard_kronmult_cpu.cpp
> +#pragma omp simd
The `omp simd` directive can be applied to multiple levels of the loop using `#pragma omp simd collapse(2)` For higher levels you can use more than `2`.

At `n=2` the loop has two entries so 128-bit + FMA, if you merge both loops it will have `2x2` entries or an opportunity for 256-bit AVX. Even more in higher dimensions.

2023-05-09 15:09 UTC, mkstoyanov commented
Impressive overall and definitely the direction we should be chasing, but why did performance drop for 2D `n=2` and 6D `n=2`. I don't see anything special in those cases, but maybe I'm missing some loop that didn't get reordered. Or is it that at `n=2` are can only use 128-bit registers unless we use the `omp simd collapse()` option.

2023-05-09 15:12 UTC, mkstoyanov commented on src/device/asgard_kronmult_cpu.cpp
> +#pragma omp simd
We should absolutely use `omp simd collapse()` for these 6 loops, even at `n=2` in 6D this will allow for AVX512 + FMA to be used effectively.

2023-05-09 17:18 UTC, quantumsteve commented
```
svh@PC102795:~/Documents/asgard/build$ OMP_PROC_BIND=close OMP_NUM_THREADS=20 ./asgard-kronmult-benchmark 2 4 4096 12288 1000
benchmarking:
dimensions: 2  n: 4  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 6.655 seconds.
single precision: 198.7491 Gflops / second.
double precision: 162.3806 Gflops / second.
svh@PC102795:~/Documents/asgard/build$ OMP_PROC_BIND=close OMP_NUM_THREADS=20 ./asgard-kronmult-benchmark 3 4 4096 12288 1000
benchmarking:
dimensions: 3  n: 4  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 8.998 seconds.
single precision: 156.8651 Gflops / second.
double precision: 93.2934 Gflops / second.
svh@PC102795:~/Documents/asgard/build$ OMP_PROC_BIND=close OMP_NUM_THREADS=20 ./asgard-kronmult-benchmark 4 4 4096 12288 1000
benchmarking:
dimensions: 4  n: 4  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 10.911 seconds.
single precision: 218.4391 Gflops / second.
double precision: 150.0835 Gflops / second.
svh@PC102795:~/Documents/asgard/build$ OMP_PROC_BIND=close OMP_NUM_THREADS=20 ./asgard-kronmult-benchmark 2 2 4096 12288 1000
benchmarking:
dimensions: 2  n: 2  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 6.615 seconds.
single precision: 75.1920 Gflops / second.
double precision: 42.6765 Gflops / second.
svh@PC102795:~/Documents/asgard/build$ OMP_PROC_BIND=close OMP_NUM_THREADS=20 ./asgard-kronmult-benchmark 3 2 4096 12288 1000
benchmarking:
dimensions: 3  n: 2  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 8.974 seconds.
single precision: 123.0728 Gflops / second.
double precision: 51.1630 Gflops / second.
svh@PC102795:~/Documents/asgard/build$ OMP_PROC_BIND=close OMP_NUM_THREADS=20 ./asgard-kronmult-benchmark 4 2 4096 12288 1000
benchmarking:
dimensions: 4  n: 2  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 10.903 seconds.
single precision: 116.7005 Gflops / second.
double precision: 129.2627 Gflops / second.
svh@PC102795:~/Documents/asgard/build$ OMP_PROC_BIND=close OMP_NUM_THREADS=20 ./asgard-kronmult-benchmark 6 2 4096 12288 1000
benchmarking:
dimensions: 6  n: 2  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 14.227 seconds.
single precision: 74.7066 Gflops / second.
double precision: 66.9693 Gflops / second.
```

2023-05-09 17:23 UTC, mkstoyanov commented on src/device/asgard_kronmult_cpu.cpp
> +#pragma omp simd collapse(4)
Just to clarify here, if you collapse the `j` loop here, you don't see any improvements?

2023-05-09 17:26 UTC, quantumsteve commented on src/device/asgard_kronmult_cpu.cpp
> +#pragma omp simd collapse(4)
I have not tried yet.

2023-05-09 17:30 UTC, mkstoyanov commented
And this looks even better. At 6D the CPU is running out of L1 cache per-core. Right now, I'll call 6D a GPU problem and not waste time with it (also the CPU is from 2012).

2023-05-09 18:02 UTC, quantumsteve commented
> And this looks even better. At 6D the CPU is running out of L1 cache per-core. Right now, I'll call 6D a GPU problem and not waste time with it (also the CPU is from 2016).
> 
> PS: I was wrong, the cpu is from 2016 ... Intel naming conventions.

Yep, my workstation is approaching 6 years old and I need to start looking into a replacement.

2023-05-09 18:09 UTC, quantumsteve commented
Here's with `omp simd collapse(n)` at the base of each loop
```
svh@PC102795:~/Documents/asgard/build$ OMP_PROC_BIND=close OMP_NUM_THREADS=20 ./asgard-kronmult-benchmark 2 4 4096 12288 1000
benchmarking:
dimensions: 2  n: 4  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 6.613 seconds.
single precision: 174.4503 Gflops / second.
double precision: 164.4951 Gflops / second.
svh@PC102795:~/Documents/asgard/build$ OMP_PROC_BIND=close OMP_NUM_THREADS=20 ./asgard-kronmult-benchmark 3 4 4096 12288 1000
benchmarking:
dimensions: 3  n: 4  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 8.999 seconds.
single precision: 157.9064 Gflops / second.
double precision: 91.7543 Gflops / second.
svh@PC102795:~/Documents/asgard/build$ OMP_PROC_BIND=close OMP_NUM_THREADS=20 ./asgard-kronmult-benchmark 4 4 4096 12288 1000
benchmarking:
dimensions: 4  n: 4  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 10.963 seconds.
single precision: 218.9123 Gflops / second.
double precision: 150.5454 Gflops / second.
svh@PC102795:~/Documents/asgard/build$ OMP_PROC_BIND=close OMP_NUM_THREADS=20 ./asgard-kronmult-benchmark 2 2 4096 12288 1000
benchmarking:
dimensions: 2  n: 2  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 6.652 seconds.
single precision: 82.6803 Gflops / second.
double precision: 51.2119 Gflops / second.
svh@PC102795:~/Documents/asgard/build$ OMP_PROC_BIND=close OMP_NUM_THREADS=20 ./asgard-kronmult-benchmark 3 2 4096 12288 1000
benchmarking:
dimensions: 3  n: 2  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 8.979 seconds.
single precision: 124.5961 Gflops / second.
double precision: 101.3814 Gflops / second.
svh@PC102795:~/Documents/asgard/build$ OMP_PROC_BIND=close OMP_NUM_THREADS=20 ./asgard-kronmult-benchmark 4 2 4096 12288 1000
benchmarking:
dimensions: 4  n: 2  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 10.875 seconds.
single precision: 113.7137 Gflops / second.
double precision: 129.9536 Gflops / second.
svh@PC102795:~/Documents/asgard/build$ OMP_PROC_BIND=close OMP_NUM_THREADS=20 ./asgard-kronmult-benchmark 6 2 4096 12288 1000
benchmarking:
dimensions: 6  n: 2  num_y: 4096  operator_size: 12288  num_matrices: 1000
benchmark setup time: 14.224 seconds.
single precision: 75.9581 Gflops / second.
double precision: 65.3597 Gflops / second.
```

2023-05-09 18:23 UTC, mkstoyanov commented
At `n=4` you're already using avx 256 which is the best you have on the CPU, but the `n=2` cases got some boost as they were stuck to 128. This is good, we should keep the `collapse(n)`

2023-05-09 19:52 UTC, mkstoyanov commented on CMakeLists.txt
> +  set (RECOMMENDED_CXXFLAGS "-march=native -Wall -Wextra -Wpedantic -Wshadow")
Let's do `-march=native -mtune=native` but only if CUDA is not enabled.

2023-05-10 12:15 UTC, mkstoyanov requested changes
The CMake change makes no sense, removing flags to only then add them again?

2023-05-10 12:15 UTC, mkstoyanov commented on CMakeLists.txt
> +  set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}" CACHE STRING "compiler flags" FORCE)
NO!

This is all this should be:
```
set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wextra -Wpedantic -Wshadow")
if (NOT ASGARD_USE_CUDA)
  set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=native -mtune=native")
endif()
```

2023-05-10 14:39 UTC, mkstoyanov approved these changes

2023-05-10 15:20 UTC, ckendrick approved these changes
Looks good - getting about 250 Gflops for the first benchmark on a Ryzen 5950X.

2023-05-10 15:26 UTC, merged