Kronmult struct
project-asgard/asgard pull request #541
Opened 2023-05-14 22:23 UTC by mkstoyanov

Another monstrous push, but this fixes most of the glaring kronmult issues:
* matrices are now stored without lda (lda is n)
    * there is a copy right now but it can be changed without kronmult changes in the future
* there is persistent kronmult-matrix object that avoids repeatedly sending the same data over
* the location of the matrices is stored in an index array, no more pointers
* X and Y are referenced by index, as opposed to a pointer
    * one matrix can be applied to multiple X and Y without reindexing/repointering
* the time stepping schemes now use persistent matrices

2023-05-16 15:07 UTC, quantumsteve commented on src/asgard_kronmult_matrix.cpp
> +            << get_MB<int>(iA.size()) + get_MB<precision>(vA.size()) << "\n";
Why is one type `int` and the other type `precision`?

2023-05-16 15:10 UTC, quantumsteve commented on src/asgard_kronmult_matrix.cpp
> +        pA = std::fill_n(pA, pde.get_coefficients(t, d).size(), 0);
```suggestion
        pA = std::fill_n(pA, pde.get_coefficients(t, d).size(), precision{0});
```

2023-05-16 15:11 UTC, mkstoyanov commented on src/asgard_kronmult_matrix.cpp
> +            << get_MB<int>(iA.size()) + get_MB<precision>(vA.size()) << "\n";
Because `iA` stands for indexes of the `A` matrices and consists of `int` while `vA` are the values of the `A` matrices and consists of floating point data (of the given precision).

2023-05-16 15:33 UTC, quantumsteve commented on src/device/asgard_kronmult_cpu.cpp
> +          T const *A0 = &(vA[iA[ma++]]);
```suggestion
          T const * const A0 = &(vA[iA[ma++]]);
```

2023-05-16 15:34 UTC, quantumsteve commented on src/device/asgard_kronmult_cpu.cpp
> +          T const *A1 = &(vA[iA[ma++]]);
```suggestion
          T const * const A1 = &(vA[iA[ma++]]);
```

2023-05-16 15:37 UTC, quantumsteve commented on src/device/asgard_kronmult_cpu.cpp
> +          T const *A2  = &(vA[iA[ma++]]);
```suggestion
          T const * const A2  = &(vA[iA[ma++]]);
```
and so forth...

2023-05-16 15:50 UTC, quantumsteve commented on src/device/asgard_kronmult_cpu.cpp
> +  if (beta == 0)
How safe are these floating point comparisons? Do we use the general case anywhere?

2023-05-16 15:53 UTC, quantumsteve commented on src/device/asgard_kronmult_cpu_general.hpp
> +            T const *A = &(vA[iA[ma++]]);
```suggestion
            T const * const A = &(vA[iA[ma++]]);
```
and similar throughout this file

2023-05-16 16:04 UTC, quantumsteve commented on src/device/asgard_kronmult_cyclex.hpp
> +          atomicAdd(&y[yoffset + threadIdx.x + team_size], yinc1);
Is there any advantage to combining the two if conditions with an `or` vs two identical calls to `atomicAdd(...)`?

2023-05-16 16:06 UTC, quantumsteve commented on src/elements.hpp
> +  fk::vector<int> active_table_d_;
should this still have the `d` (device?) postfix?

2023-05-16 16:08 UTC, quantumsteve commented on src/time_advance.cpp
> +  // auto const &table    = adaptive_grid.get_table();
commented out code?

2023-05-16 16:08 UTC, quantumsteve commented on src/time_advance.cpp
> +    //    max_iter, tolerance, imex_flag::imex_implicit);
commented out code?

2023-05-16 16:09 UTC, quantumsteve commented on src/time_advance.cpp
> +    // pde.gmres_outputs[1] = solver::simple_gmres(
commented out code?

2023-05-16 16:09 UTC, quantumsteve commented on src/time_advance.cpp
> +    //    max_iter, tolerance, imex_flag::imex_implicit, static_cast<P>(0.5));
commented out code?

2023-05-16 16:21 UTC, mkstoyanov commented on src/device/asgard_kronmult_cpu.cpp
> +          T const *A0 = &(vA[iA[ma++]]);
Removed the `A2, A1, A0` variables and left one variable `A` that changes as needed.

2023-05-16 16:25 UTC, mkstoyanov commented on src/device/asgard_kronmult_cpu.cpp
> +  if (beta == 0)
If there is any rounding in beta, I want to switch to the general case, i.e., if we set `beta` as in `apply(..., 0, y)` then we can zero out `y`. But if we have a `beta` that comes from other computations and is very close to `0`, then I want to use that `beta` otherwise I may introduce rounding when not needed.

As for the usage, right now we are only using `0` and `1`, but I want to change that in the future. We are doing too much repeated work and moving data back and forth, I want to have the generality to incorporate `alpha` and `beta` which may save us on calling an explicit scale method.

2023-05-16 16:28 UTC, mkstoyanov commented on src/device/asgard_kronmult_cyclex.hpp
> +          atomicAdd(&y[yoffset + threadIdx.x + team_size], yinc1);
One is `if constexpr` and the other one is runtime `if`. I want to make sure that if the `constexpr` statement hold, then I never call the runtime if which is particularly bad on the GPU.

If I replace the whole thing with a single runtime `if` I would be at the mercy of the optimizer to analyze the if-statement and realize what can be done at runtime and compile time. Maybe it's OK, but I don't want to count on it.

2023-05-16 16:29 UTC, mkstoyanov commented on src/elements.hpp
> +  fk::vector<int> active_table_d_;
I should look at removing this, but there is sometimes logic that mandates a copy and the use of different variables.

Good catch!

2023-05-16 16:41 UTC, mkstoyanov commented on src/elements.hpp
> +  fk::vector<int> active_table_d_;
Fixed!

2023-05-16 16:42 UTC, mkstoyanov commented on src/time_advance.cpp
> +    //    max_iter, tolerance, imex_flag::imex_implicit);
Removed

2023-05-16 17:17 UTC, quantumsteve approved these changes, later dismissed

2023-05-17 00:49 UTC, mkstoyanov commented
@ckendrick can you check now, perhaps this fixed it

2023-05-17 02:06 UTC, ckendrick requested changes
The latest changes have fixed the issue with the Landau problem.

Everything looks good, but I'm getting tons of `-Wunused-but-set-parameter` warnings (compiled with `-DASGARD_RECOMMENDED_DEFAULTS=ON`):
```
/home/u0k/asgard/src/device/asgard_kronmult_cpu.cpp: In instantiation of ‘void asgard::kronmult::cpu_dense(int, int, int, const int*, const T*, T, const T*, T, T*) [with T = double; int dimensions = 1; int n = 2; asgard::kronmult::scalar_case alpha_case = asgard::kronmult::scalar_case::neg_one; asgard::kronmult::scalar_case beta_case = asgard::kronmult::scalar_case::zero]’:
/home/u0k/asgard/src/device/asgard_kronmult_cpu.cpp:498:66:   required from ‘void asgard::kronmult::cpu_dense(int, int, int, const int*, const T*, T, const T*, T, T*) [with T = double; int d = 1; int n = 2]’
/home/u0k/asgard/src/device/asgard_kronmult_cpu.cpp:615:25:   required from ‘void asgard::kronmult::cpu_dense(int, int, int, int, int, const int*, const T*, T, const T*, T, T*) [with T = double]’
/home/u0k/asgard/src/device/asgard_kronmult_cpu.cpp:770:41:   required from here
/home/u0k/asgard/src/device/asgard_kronmult_cpu.cpp:83:54: warning: parameter ‘alpha’ set but not used [-Wunused-but-set-parameter]
   83 |                int const iA[], T const vA[], T const alpha, T const x[],
      |                                              ~~~~~~~~^~~~~
/home/u0k/asgard/src/device/asgard_kronmult_cpu.cpp:84:24: warning: parameter ‘beta’ set but not used [-Wunused-but-set-parameter]
   84 |                T const beta, T y[])
```
Is it possible to fix this warning?

2023-05-17 11:21 UTC, mkstoyanov commented
I think I can work around it, but it is a non-warning. `alpha` is used in conjunction with a template parameter and for some values it is indeed ignored. The variable should not be considered `unused` unless it is unused in all cases but the compiler doesn't check all cases is warning preemptively. We can probably just add `ignore(alpha);` and it will be fine.

2023-05-17 12:05 UTC, mkstoyanov commented
Actually, there are no warnings if you use a newer compiler. I think I got all cases but @ckendrick will have to double-check.

2023-05-17 12:55 UTC, ckendrick commented on src/device/asgard_kronmult_cpu.cpp
Here is one more spot to suppress the warning.
```suggestion
  (void)alpha;
  (void)beta;
```

2023-05-17 13:27 UTC, ckendrick approved these changes

2023-05-17 15:54 UTC, merged