Kronmult limited memory
project-asgard/asgard pull request #572
Opened 2023-06-16 01:00 UTC by mkstoyanov

Kronmult now automatically splits the problem into chunks to avoid overflow of the 32-bit integer. This is done on the CPU and GPU, sparse and dense cases. This will not limit the total amount of GPU memory being used, but it will allow handling larger problems, should the limitation be the index size as opposed to the memory size.

There is also a CMake option to enable the limit for GPU memory, but the method is currently too slow. Doing a proper out-of-core algorithm requires overlapping communication and computation the kronmult module, which in turn requires dabbling with pinned memory. Even then, for smaller dimensions and degree, the cost of data movement is much higher than the gains from fast GPU.

Improvements will follow in further PRs.

2023-06-22 20:18 UTC, quantumsteve commented on CMakeLists.txt
> +option (ASGARD_USE_GPU_MEM_LIMIT "Allow the ability to limit the GPU memory used by kronmult (can hurt performance)" OFF)
What's the best way to add this to CI? Create a new CI build with `ASGARD_USE_GPU_MEM_LIMIT=ON`?

2023-06-22 20:29 UTC, mkstoyanov commented on CMakeLists.txt
> +option (ASGARD_USE_GPU_MEM_LIMIT "Allow the ability to limit the GPU memory used by kronmult (can hurt performance)" OFF)
Yes, it must use CUDA and `-DASGARD_USE_GPU_MEM_LIMIT=ON`

By default, we should test with off.

2023-06-23 18:15 UTC, mkstoyanov commented
@quantumsteve BTW we should move on this PR before we start merging the rest of the two-stream and Cole's work. That's because this PR makes the workaround for the 32-bit indexing limitation and potential GPU memory limit.

The limit itself is not so important, currently it imposes a huge performance penalty and more improvements will be needed over time. But the 32-bit indexing is important to fix.

2023-06-26 21:49 UTC, quantumsteve requested changes
I just updated `AWS CodeBuild us-east-1 (asgard-unit-cuda)` to set `-DSGARD_USE_GPU_MEM_LIMIT=1`. I reran the job and it passes :tada:

Just a couple small changes to avoid unused variable warnings in Release builds. 

`cmake_dependent_option` is a nice way to handle options that depend on other options being set.

2023-06-26 21:49 UTC, quantumsteve commented on CMakeLists.txt
> +if (ASGARD_USE_GPU_MEM_LIMIT AND NOT ASGARD_USE_CUDA)
`cmake_dependent_option` can makes these checks.

2023-06-26 21:49 UTC, quantumsteve commented on src/asgard_grid_1d.hpp
> +    return -1;
Is this expected to occur?

2023-06-26 21:49 UTC, quantumsteve commented on src/asgard_kronmult_matrix.hpp
> +        assert(stats == cudaSuccess);
```suggestion
        expect(stats == cudaSuccess);
```

2023-06-26 21:49 UTC, quantumsteve commented on src/asgard_kronmult_matrix.hpp
> +            assert(stats == cudaSuccess);
```suggestion
            expect(stats == cudaSuccess);
```

2023-06-26 21:49 UTC, quantumsteve commented on src/asgard_kronmult_matrix.hpp
> +        assert(stats == cudaSuccess);
I think we need a dedicated check for compiler warnings with CUDA enabled.

2023-06-26 21:49 UTC, quantumsteve commented on src/asgard_kronmult_matrix.hpp
> +      if (iA.size() > 0)
NOT for this PR, but `fk::vector` and `fk::matrix` would benefit from an `empty()` member function.

2023-06-26 21:49 UTC, quantumsteve commented on src/asgard_kronmult_matrix.hpp
> +    flops_ *= int64_t(tensor_size_) * kron_size_;
```suggestion
    flops_ *= int64_t{tensor_size_} * kron_size_;
```

2023-06-27 14:43 UTC, mkstoyanov commented on src/asgard_grid_1d.hpp
> +    return -1;
If two cells are connected, this will return the location of the non-zero within the sparse 1D matrix. If the cells are not connected, this will return invalid index `-1`. Usage is:
```
int idx = rule1d.get_offset(row, col);
if (idx == -1)
  // process disconnected cells
else
  // process connected cells
```

2023-06-27 14:45 UTC, mkstoyanov commented on src/asgard_kronmult_matrix.hpp
> +      if (iA.size() > 0)
Agree!

2023-06-27 14:46 UTC, mkstoyanov commented on src/asgard_kronmult_matrix.hpp
> +        assert(stats == cudaSuccess);
You mean runtime check?

2023-06-27 15:08 UTC, mkstoyanov commented on CMakeLists.txt
> +if (ASGARD_USE_GPU_MEM_LIMIT AND NOT ASGARD_USE_CUDA)
`cmake_dependent_option` does not raise error, it only hides option (probably just in the GUI).

Switched to the `cmake_dependent_option` but the if-statement must remain.

2023-06-27 18:44 UTC, quantumsteve commented on CMakeLists.txt
> +if (ASGARD_USE_GPU_MEM_LIMIT AND NOT ASGARD_USE_CUDA)
:disappointed: Wonder if it's a CMake bug...

2023-06-27 18:46 UTC, quantumsteve commented on src/asgard_kronmult_matrix.hpp
> +        assert(stats == cudaSuccess);
The `expect` macro should expand to (void)stats; so that stats doesn't look like an unused variable.

2023-06-27 19:02 UTC, quantumsteve approved these changes

2023-06-27 19:05 UTC, merged