Add matrix-free GMRES solver test
project-asgard/asgard pull request #581
Opened 2023-07-11 16:52 UTC by quantumsteve

Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

Describe what this PR changes and why.  If it closes an issue, link to it here
with [a supported keyword](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

This adds a matrix-free gmres solver test for use as we move the vectors `x` and `b` to the GPU and avoid unnecessary copies.

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [ ] Bugfix
- [ ] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [x] Other (please describe): testing improvement

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

## What systems has this change been tested on?

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [x] this PR is up to date with current the current state of 'develop'
- [x] code added or changed in the PR has been clang-formatted
- [x] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

2023-07-13 02:14 UTC, mkstoyanov commented
Kronmult doesn’t do gpu to gpu work yet, everything in and out is on the cpu. It’s easy to make, but it’s not there yet. This may be jumping the gun a bit.

Also, lib-dispatch no longer needs the definition of constants one or n.

2023-07-13 03:19 UTC, quantumsteve commented
> Kronmult doesn’t do gpu to gpu work yet, everything in and out is on the cpu. It’s easy to make, but it’s not there yet. This may be jumping the gun a bit.

ColeGarD  seems to do gpu to gpu work. 
https://github.com/ckendrick/asgard/blob/273ce79264497fcde1077fd1ac655f789fcd97d9/src/asgard_kronmult_matrix.hpp#L309

2023-07-18 21:54 UTC, mkstoyanov requested changes

2023-07-18 21:54 UTC, mkstoyanov commented on src/asgard_kronmult_matrix.hpp
> +  template<resource input_resrc  = resource::host,
Make one template parameters, mix-and-match gets messy.
```
template<resource resrc  = resource::host>
```

2023-07-18 21:54 UTC, mkstoyanov commented on src/asgard_kronmult_matrix.hpp
> +    if constexpr (input_resrc == resource::host)
My expectation here is that this will work fine:
```
  void apply(precision alpha, precision const x[], precision beta,
             precision y[]) 
{
if constexpr (resrc == resource::host){
#ifdef ASGARD_USE_CUDA
      if (beta != 0)
        fk::copy_to_device(ydev.data(), y, ydev.size());
      fk::copy_to_device(xdev.data(), x, xdev.size());
      apply<resource::device>(alpha, xdev.data(), beta, ydev.data());
      fk::copy_to_host(y, ydev.data(), ydev.size());
#else 
    ... CPU kronmult code ...
#endif
} else {
#ifdef ASGARD_USE_CUDA
    ... CPU kronmult code ...
#else 
    static_assert(resrc == resource::host, "kronmult cannot work on device if CUDA is not enabled ...");
#endif
}
}

```

2023-07-18 21:54 UTC, mkstoyanov commented on src/solver.cpp
> +#endif
Throw some sort of error or static assert if this is called on the device without CUDA

2023-07-18 21:54 UTC, mkstoyanov commented on src/solver.cpp
> +#endif
There is a bunch of these

2023-07-18 21:54 UTC, mkstoyanov commented on src/solver.cpp
> +        fk::vector<P, mem_type::const_view, resrc> const basis_vect(
This is very inefficient, I must have missed it in the original PR. We can change it later, but new-basis should be just a view of the i+1-st column of basis, and the for-loop should be replaced with `gemv` operations.

Look here: (it's not ideal, but it is better)
https://github.com/mkstoyanov/hala/blob/develop/hex/solvers/hala_solvers_gmres.hpp

2023-07-18 21:54 UTC, mkstoyanov commented on src/solver.cpp
> +      fm::gemv(m, s_view.clone_onto_device(), x, false, P{1.0}, P{1.0});
The signature of the fast-math methods is messed up .... for another PR.

2023-07-19 19:50 UTC, quantumsteve commented on src/solver.cpp
> +        fk::vector<P, mem_type::const_view, resrc> const basis_vect(
I made some progress changing from dot products to gemv. I'd like to keep additional changes to separate pull requests.

2023-07-19 19:54 UTC, quantumsteve commented on src/solver.cpp
> +#endif
done

2023-07-19 19:58 UTC, quantumsteve commented on src/asgard_kronmult_matrix.hpp
> +    if constexpr (input_resrc == resource::host)
Think I found a solution using lambdas that required minimal changes to apply

2023-07-19 20:44 UTC, mkstoyanov commented on src/asgard_kronmult_matrix.hpp
> +                              num_cols_, num_terms_, list_iA[i].data(),
In out-of-core mode (e.g., if we limit the memory), the entries of `list_iA` sit on the CPU.

Perhaps we should wait for the GPU-to-GPU PR first and not break use-cases.

2023-08-03 19:20 UTC, mkstoyanov approved these changes

2023-08-03 19:41 UTC, merged