Add option --max_adapt_level
project-asgard/asgard pull request #588
Opened 2023-07-18 15:26 UTC by quantumsteve

Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

Describe what this PR changes and why.  If it closes an issue, link to it here
with [a supported keyword](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

This adds the option `--max_adapt_level` which provided finer control than the current `-max_level`

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [ ] Bugfix
- [x] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

## What systems has this change been tested on?

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [x] this PR is up to date with current the current state of 'develop'
- [x] code added or changed in the PR has been clang-formatted
- [x] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

2023-07-18 15:49 UTC, stefan-schnake requested changes

2023-07-18 15:49 UTC, stefan-schnake commented on src/elements.cpp
> +      daughter_ids.push_back(map_to_id(daughter_coords, level, num_dims));
This line needs to be reverted.  `opts.max_level` defines the indicies for the hierarchy across all dimensions.  If you change this here, then a lot needs to be changed to compensate (for no gain).

2023-07-18 15:49 UTC, stefan-schnake commented on src/elements.cpp
> +        daughter_ids.push_back(map_to_id(daughter_coords, level, num_dims));
Same as Line 232

2023-07-18 15:49 UTC, stefan-schnake commented on src/program_options_tests.cpp
> +  //--adapt
Add a test with `max_adapt_level` with different values for each dimension.

2023-07-18 15:49 UTC, stefan-schnake commented on src/pde/pde_base.hpp
> +      return levels.empty()
Is this just reordering the logic?

2023-07-18 15:50 UTC, ckendrick commented on src/elements.cpp
> +      daughter_ids.push_back(map_to_id(daughter_coords, level, num_dims));
I think this and the similar change below should still use `opts.max_level` here since that maximum level is used in the hash table. We want to always use the highest level when doing these `map_to_id` calls.

If this is run with level 4 6 6 6, we want this to be 6 instead of the current dimension level. We need to double check with @stefan-schnake though.

2023-07-18 15:56 UTC, quantumsteve commented on src/pde/pde_base.hpp
> +      return levels.empty()
Yes, I switched `level.size() > 0` to `levels.empty()` and swapped true and false branches.

2023-07-18 17:00 UTC, quantumsteve commented on src/program_options_tests.cpp
> +  //--adapt
done in `time_advance_tests.cpp`

2023-07-18 17:01 UTC, quantumsteve commented on src/elements.cpp
> +      daughter_ids.push_back(map_to_id(daughter_coords, level, num_dims));
changed

2023-07-18 17:01 UTC, quantumsteve commented on src/elements.cpp
> +        daughter_ids.push_back(map_to_id(daughter_coords, level, num_dims));
updated

2023-07-18 17:02 UTC, quantumsteve commented on src/elements.cpp
> +      daughter_ids.push_back(map_to_id(daughter_coords, level, num_dims));
changed back to `opts.max_level`

2023-07-18 17:31 UTC, ckendrick requested changes

2023-07-18 17:31 UTC, ckendrick commented on src/program_options.cpp
> +    }
Is this if statement duplicated?

2023-07-18 17:34 UTC, mkstoyanov commented
What exactly is the difference between `max_adapt_level` and `max_level`? Finer control is not clear to me.

2023-07-18 17:34 UTC, quantumsteve commented on src/program_options.cpp
> +    }
:man_facepalming:

2023-07-18 17:35 UTC, quantumsteve commented
> What exactly is the difference between `max_adapt_level` and `max_level`? Finer control is not clear to me.

See https://github.com/project-asgard/asgard/issues/583

2023-07-18 18:14 UTC, stefan-schnake commented
> What exactly is the difference between max_adapt_level and max_level? Finer control is not clear to me.

An original assumption of this code is when adaptively is enabled, you should let the adaptivity determine what the proper level is in each dimension.  `max_level` was used to preload the coefficients matrices (which were time independent), define the hierarchy, and was expected to be set very high.

However, with the problems that we are doing now, that involve different timescales in the x vs v directions, having a uniform max_level is not practical.  Often the algorithm will adapt too far, violate the CFL, and then blow up.

Because `max_level` is used to define the hierarchy, changing it could break a lot of things.  I'm fine if we remove the option to change `max_level` from the command line.

2023-07-18 18:21 UTC, mkstoyanov commented
So you want anisotropic max-level (which is a better word than adapt-max-level since all cases refer to adaptivity).

We should either use a time-step that satisfies the CFL for all levels or have a way to adapt the time-step based on the CFL. How do we do that now? Don't we have something that computes CFL?

2023-07-18 23:39 UTC, stefan-schnake commented
> So you want anisotropic max-level (which is a better word than adapt-max-level since all cases refer to adaptivity).

Yes

> We should either use a time-step that satisfies the CFL for all levels or have a way to adapt the time-step based on the CFL. How do we do that now?

There is an ability to set a CFL based of one of the dimensions, but there is no way to set a final time command line input so it's pretty useless.

2023-07-19 20:45 UTC, mkstoyanov approved these changes

2023-07-20 11:21 UTC, ckendrick commented on src/program_options.cpp
> +      clara::detail::Opt(aniso_adapt_levels_str, "")["--aniso_adapt_levels"](
Can we keep the user-facing option as `--max_adapt_levels` but keep the help text as-is (anisotropic hierarchical levels)? 
I feel like `--max_adapt_levels` is more clear for the user given we have options for `--max_level` and `--adapt`. The user might look for something like max adapt level instead of having to know it is `--aniso_adapt_levels`.

2023-07-20 18:45 UTC, mkstoyanov commented on src/program_options.cpp
> +      clara::detail::Opt(aniso_adapt_levels_str, "")["--aniso_adapt_levels"](
The issue is that both `max_level` and `max_adapt_levels` are list of numbers, one for each dimension. Think of the following:
```
--max_adapt_levels "3 4 4" --max_level "4 3 4"
```
How confusing is that?

If we want to keep `max_adapt_levels`, we should change the other one to accept a single number. That way it is clear that one option refers to all levels, while the other provides per-level granularity.

2023-07-20 19:14 UTC, ckendrick commented on src/program_options.cpp
> +      clara::detail::Opt(aniso_adapt_levels_str, "")["--aniso_adapt_levels"](
`--max_level` is only a single number. Currently `--max_level 6` is interpreted as `6 6 6` when adapting.

`--max_adapt_levels` will let us override that per-dimension by doing something like `--max_adapt_levels "3 4 6" --max_level 6`

2023-07-20 20:31 UTC, mkstoyanov commented on src/program_options.cpp
> +      clara::detail::Opt(aniso_adapt_levels_str, "")["--aniso_adapt_levels"](
Wow, I guess you can pass in just a single number. I've been passing in lists and it works just fine.

Then it's Ok to have the option.

2023-07-20 20:32 UTC, mkstoyanov approved these changes, later dismissed

2023-07-20 21:00 UTC, ckendrick commented on src/program_options.cpp
> +      clara::detail::Opt(aniso_adapt_levels_str, "")["--aniso_adapt_levels"](
Hmm.. that seems like a CLI parsing bug if it is accepting a list for `--max_level`. It is defined as an int in the `parser` class: https://github.com/project-asgard/asgard/blob/170da165cb60b2cc344cf9ebc8ccd5546d065649/src/program_options.hpp#L352

2023-07-20 21:08 UTC, mkstoyanov commented on src/program_options.cpp
> +      clara::detail::Opt(aniso_adapt_levels_str, "")["--aniso_adapt_levels"](
Try it, it's perfectly happy to accept a list, just like the `-l` option. Anyway, that's why I was confused on why you would want two lists.

2023-07-21 13:09 UTC, ckendrick commented on src/program_options.cpp
> +      clara::detail::Opt(aniso_adapt_levels_str, "")["--aniso_adapt_levels"](
You're right, it does accept a list! This is unintentional with the current implementation. It looks like it is using only the first element to set the value. I guess the clara parser is reducing this list to an integer automatically? This is definitely an edge case not caught in the current CLI parsing validation.

If @quantumsteve can rename `--aniso_adapt_levels` to `--max_adapt_levels` then this PR looks good to me.

2023-07-21 15:59 UTC, mkstoyanov approved these changes

2023-07-21 16:08 UTC, ckendrick approved these changes

2023-07-21 16:56 UTC, merged