Add file checkpoint restart
project-asgard/asgard pull request #597
Opened 2023-07-26 17:58 UTC by ckendrick

Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

Adds initial implementation of a `--restart` CLI option that accepts an HDF5 file allowing simulations to be resumed.

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [ ] Bugfix
- [x] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

## What systems has this change been tested on?

Ubuntu 20.04

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [x] this PR is up to date with current the current state of 'develop'
- [x] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

2023-07-26 19:07 UTC, stefan-schnake commented on src/elements.cpp
> +  std::cout << "  - original elements: " << original_ids.size() << "\n";
What's the purpose of displaying this?  If we're adapting, then these two numbers could be different.

2023-07-26 19:25 UTC, ckendrick commented on src/elements.cpp
> +  std::cout << "  - original elements: " << original_ids.size() << "\n";
That's true, this was more just to display feedback for info/debugging purposes if the numbers were different but not expected to be. This is before more metadata is saved (such as whether FG or ASG was used in the original run). If the user ran `--restart` but forgot to add `--adapt` or `-f`, then these could be different or the same.

We could definitely remove this completely if that's better, or rework to have better logic for different cases.

2023-07-26 19:49 UTC, mkstoyanov requested changes

2023-07-26 19:49 UTC, mkstoyanov commented on src/adapt.hpp
> +    plan_.clear();
Clear followed by insert? Don't we have move assignment for this data structutre:
```
plan_ = get_plan(get_num_ranks(), table_);
```

2023-07-26 20:05 UTC, cianciosa commented on src/adapt.hpp
> +    plan_.clear();
This may be related to this comment.

https://github.com/project-asgard/asgard/blob/b8a9b9b950200fd2f3047ff87387059f0bfa5b72/src/adapt.cpp#L362C1-L362C1

2023-07-26 20:15 UTC, ckendrick commented on src/adapt.hpp
> +    plan_.clear();
Yes @cianciosa is correct, I don't know if we have found a workaround for that issue yet or not.

2023-07-26 20:20 UTC, stefan-schnake commented on src/elements.cpp
> +  std::cout << "  - original elements: " << original_ids.size() << "\n";
I would remove the original elements # but keep the other.

2023-07-26 22:27 UTC, mkstoyanov commented on src/adapt.hpp
> +    plan_.clear();
Just tried on clang 14 and it works fine. Give it a try, there's no reason why this wouldn't work.

2023-07-27 19:43 UTC, ckendrick commented on src/adapt.hpp
> +    plan_.clear();
I swapped this to use `std::move` following the changes added by #600.

2023-07-27 19:52 UTC, quantumsteve commented on src/elements.cpp
> +    id_to_coords_[id].resize(coords.size()) = coords;
```suggestion
    id_to_coords_[id] = std::move(coords);
```

2023-07-27 20:06 UTC, quantumsteve commented on src/adapt.hpp
> +    plan_ = std::move(get_plan(get_num_ranks(), table_));
```suggestion
    plan_ = get_plan(get_num_ranks(), table_);
```

std::move should have no effect.

2023-07-27 20:07 UTC, quantumsteve commented on src/elements.cpp
> +  active_table_.resize(dev_table_builder.size()) = dev_table_builder;
```suggestion
  active_table_ = std::move(dev_table_builder);
```

2023-07-27 20:09 UTC, quantumsteve commented on src/io.hpp
> +void read_restart_metadata(parser *user_vals, std::string restart_file)
```suggestion
void read_restart_metadata(parser *user_vals, std::string const & restart_file)
```

2023-07-27 20:10 UTC, quantumsteve commented on src/io.hpp
> +  std::string levels = "";
```suggestion
  std::string levels;
```

2023-07-27 20:13 UTC, quantumsteve commented on src/io.hpp
> +void read_restart_metadata(parser *user_vals, std::string restart_file)
Since `user_vals` is never NULL, use a reference.

2023-07-27 20:13 UTC, quantumsteve commented on src/io.hpp
> +  parser_mod::set(*user_vals, parser_mod::max_level, max_level);
```suggestion
  parser_mod::set(user_vals, parser_mod::pde_str, pde_string);
  parser_mod::set(user_vals, parser_mod::degree, degree);
  parser_mod::set(user_vals, parser_mod::dt, dt);
  parser_mod::set(user_vals, parser_mod::starting_levels_str, levels);
  parser_mod::set(user_vals, parser_mod::max_level, max_level);
```

2023-07-27 20:17 UTC, quantumsteve commented on src/io.hpp
> +  int step_index = (int)(time / dt);
```suggestion
  int step_index = static_cast<int>(time / dt);
```

2023-07-27 20:18 UTC, quantumsteve commented on src/pde/pde_base.hpp
> +  fk::vector<P> E_source;
Are these connected to checkpoint restart?

2023-07-27 20:20 UTC, quantumsteve commented on src/program_options.cpp
> +bool parser::do_restart() const { return restart_file != NO_USER_VALUE_STR; }
(not for this PR) it looks like clara supports std::optional.

2023-07-27 20:21 UTC, quantumsteve commented on src/time_advance.cpp
> +    pde.E_field  = poisson_E;
Should changes to time_advance be part of this PR?

2023-07-27 20:42 UTC, quantumsteve requested changes
see comments

2023-07-27 20:46 UTC, ckendrick commented on src/elements.cpp
> +    id_to_coords_[id].resize(coords.size()) = coords;
`coords` is still used below this line so `move` here causes an issue: https://github.com/project-asgard/asgard/blob/ce77cfe4aee97a1dce1b7dcf79507c0c8d117bd7/src/elements.cpp#L357

This method needs to be re-written since it has the same `concat`/realloc issue as the regular element table creation in #598.

This could also be removed once we change how the element table is stored since this is taking the flattened indices saved to file and expanding them back into the [lev0, lev1 ..., levn, cell0, cell1, ..., celln] format.

2023-07-27 20:49 UTC, quantumsteve commented on src/elements.cpp
> +    id_to_coords_[id].resize(coords.size()) = coords;
Can you swap lines 354 and 357. `fk::vector::concat` only takes const reference.

2023-07-27 20:52 UTC, ckendrick commented on src/pde/pde_base.hpp
> +  fk::vector<P> E_source;
I don't believe these are explicitly required for restarting since they get recreated in IMEX, but this should be confirmed. These were mostly added for info purposes to plot. Not sure if they are still needed or required though.

2023-07-27 20:53 UTC, ckendrick commented on src/program_options.cpp
> +bool parser::do_restart() const { return restart_file != NO_USER_VALUE_STR; }
That is good to know. I think a lot of CLI options could make use of that.

2023-07-27 20:56 UTC, stefan-schnake commented on src/pde/pde_base.hpp
> +  fk::vector<P> E_source;
They are not required as IMEX rebuilds all of the moment data and derivative objects.

2023-07-27 21:03 UTC, ckendrick commented on src/pde/pde_base.hpp
> +  fk::vector<P> E_source;
Should these get removed entirely or are they still useful to store?

2023-07-28 01:13 UTC, stefan-schnake commented on src/pde/pde_base.hpp
> +  fk::vector<P> E_source;
They're only useful in a debugging capacity.   Otherwise we don't need them

2023-07-28 18:20 UTC, quantumsteve commented
We should have a test running `n` timesteps and another that restarts sometime before then. Do you want to do that in a separate PR?

2023-07-28 18:22 UTC, mkstoyanov approved these changes

2023-07-28 18:23 UTC, quantumsteve approved these changes

2023-07-28 18:31 UTC, mkstoyanov commented
> We should have a test running `n` timesteps and another that restarts sometime before then. Do you want to do that in a separate PR?

I don't want to have hanging PRs and hold things back (divergence is a problem). Let's merge now and we can keep improving over time. (adding missing tests should be very high priority)

2023-07-28 18:35 UTC, quantumsteve commented
> > We should have a test running `n` timesteps and another that restarts sometime before then. Do you want to do that in a separate PR?
> 
> I don't want to have hanging PRs and hold things back (divergence is a problem). Let's merge now and we can keep improving over time. (adding missing tests should be very high priority)

I agree.

2023-07-28 19:08 UTC, merged