Add initial sparse class for sparse moment matrices
project-asgard/asgard pull request #599
Opened 2023-07-27 00:24 UTC by ckendrick

Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

This adds a `sparse` class for basic storage of sparse matrices in CSR format. The class currently makes use of the existing vector/matrix classes for reuse of storage/functionality and compatibility with existing code. Functionality is limited and should be extended more in future PRs.

Currently this is only being used in the `moment` class to store the moment matrices for use in IMEX. This is necessary for PDEs beyond 1x1v. `gesv` routines wrapping cuSOLVER are added to `fast_math` and `lib_dispatch` to calculate moments in IMEX. A very basic CPU implementation is also added for support with non-CUDA builds but is not optimized. Test coverage is limited and needs to be extended as well.

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [ ] Bugfix
- [x] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

## What systems has this change been tested on?

Ubuntu 20.04

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [x] this PR is up to date with current the current state of 'develop'
- [x] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

2023-07-27 00:56 UTC, stefan-schnake commented on src/sparse.hpp
> +    P constexpr tol = 1.0e-10;
Why is this bumped up so high over machine epsilon?

2023-07-27 01:00 UTC, stefan-schnake commented on src/sparse.hpp
> +  // template<mem_type m_ = mem, typename = enable_for_owner<m_>,
Delete

2023-07-27 11:52 UTC, mkstoyanov commented on src/lib_dispatch.cpp
> +void sparse_gemv(char const *trans, int *rows, int *cols, int *nnz,
WHY ARE THESE BEING PASSES IN AS POINTERS?

trans, rows, cols, nnz, etc, should be passed in by value

2023-07-27 11:54 UTC, mkstoyanov commented on src/lib_dispatch.cpp
> +                 const int *offsets, const int *columns, const P *A, P *alpha,
Better names here are `row_offsets, `col_indexes` and `vals` (for A).

2023-07-27 12:33 UTC, mkstoyanov requested changes

2023-07-27 12:33 UTC, mkstoyanov commented on src/lib_dispatch.cpp
> +      int num_in_row = offsets[i + 1] - offsets[i];
You're needlessly offsetting back and forth and you forgot alpha and beta:
```
for(int r=0; r<rows; i++)
{
  y[r] *= beta;
  for(int c=offsets[i]; c < offsets[i+1]; c++)
  {
    y[i] += alpha * A[c] * x[columns[c]];
  }
}
```

2023-07-27 12:33 UTC, mkstoyanov commented on src/lib_dispatch.cpp
> +      int num_in_row = offsets[i + 1] - offsets[i];
Also, the current implementation is not using `columns` and therefore it is wrong.

2023-07-27 12:33 UTC, mkstoyanov commented on src/moment.cpp
> +  // this->sparse_mat =
Delete

2023-07-27 12:33 UTC, mkstoyanov commented on src/sparse.hpp
> +// forward declarations
Why? You are declaring the class right after the forward declare.

2023-07-27 12:33 UTC, mkstoyanov commented on src/sparse.hpp
> +template<typename P, mem_type mem, resource resrc>
Getting a view of a sparse matrix is incredibly messy. Why do we need this capability and how are we even going to do it without a copy, given that cuSparse doesn't really support it.

Skip the `mem_type` unless we really need it (and we can discuss if it is needed).

2023-07-27 12:33 UTC, mkstoyanov commented on src/sparse.hpp
> +  int nz_;
Confusing, what's the difference between `nnz_` and `nz_`?

2023-07-27 12:33 UTC, mkstoyanov commented on src/sparse.hpp
> +  int64_t sp_size() const { return int64_t{values_.size()}; }
How is this different from `nnz()`?

2023-07-27 12:33 UTC, mkstoyanov commented on src/sparse.hpp
> +      int num_in_row = row_offsets_[row + 1] - row_offsets_[row];
Adding and subtracting the row-indexes here, see my earlier comment for the sparse mat-vec multiply.

2023-07-27 12:33 UTC, mkstoyanov commented on src/sparse.hpp
> +  sparse()
Lets initialize the constants too, so that rows/cols/nnz are set to zero too.

2023-07-27 12:33 UTC, mkstoyanov commented on src/sparse.hpp
> +  explicit sparse(int nrows, int ncols, int nnz,
For the owner case, we need to add a constructor that accepts `r-val-refs` for all the vectors.

2023-07-27 12:33 UTC, mkstoyanov commented on src/sparse.hpp
> +    P constexpr tol = 1.0e-10;
The tolerance should depend on the precision, should it not? Also, what's the right number here? Maybe we need to discuss.

2023-07-27 12:33 UTC, mkstoyanov commented on src/sparse.hpp
> +    values.reserve(nrows_);
Can we run a quick loop and figure out the number of non-zeros first?

This reserves too little, `col_indices_tmp` are not reserved either. Then we can avoid relocation in `push` and the copy to `fk::vector`.

2023-07-27 12:33 UTC, mkstoyanov commented on src/sparse.hpp
> +    row_offsets_ = fk::vector<int, mem, resrc>(other.get_offsets());
Double initialization of `row_offsets_`, we can initialize directly with the ints above.

2023-07-27 12:33 UTC, mkstoyanov commented on src/sparse.hpp
> +    return sparse<P, mem_type::owner, resource::device>(
This creates additional copy for the vectors. Can be avoided with a constructor accepting `r-val-refs`, then we don't need the temporary variables.

2023-07-27 12:33 UTC, mkstoyanov commented on src/sparse.hpp
> +        if (exists(i, j))
Is this the only place where `exists()` is used? It is not needed if you only loop over the values with indexes, there is no need to brute force the check over all entries.

2023-07-27 12:33 UTC, mkstoyanov commented on src/sparse.hpp
> +            std::cout << std::setw(12) << std::setprecision(4)
Do this once, outside of the loops.

2023-07-27 12:33 UTC, mkstoyanov commented on src/fast_math.hpp
> +  int const rows_A = trans_A ? A.ncols() : A.nrows();
This isn't `rows_A`, this is `rows_opA` or `expected_y_size`.

2023-07-27 12:33 UTC, mkstoyanov commented on src/fast_math.hpp
> +  P alpha_          = alpha;
This is painful, see comment later on.

2023-07-27 12:33 UTC, mkstoyanov commented on src/sparse.hpp
> +  P data;
It's `value` or `val`, not `data`.

2023-07-27 12:33 UTC, mkstoyanov commented on src/sparse.hpp
> +  int nz_;
OK, figured it out, but there's no point in keeping both of them. We need `nnz_`, although it is also the size of the `col_indices_` so there's no real reason to keep it, and `nz_` is not needed. We can compute it as `rows()*cols() - nnz()` in the unlikely case that we may actually need it.

2023-07-27 13:39 UTC, stefan-schnake commented on src/sparse.hpp
> +    P constexpr tol = 1.0e-10;
Yes it should depend on precision.   Also I believe `1e-10` is fine as the coefficients for the moments are 0 for any level > 0.

2023-07-28 18:24 UTC, mkstoyanov commented on src/sparse.hpp
> +  void print(std::string const label = "") const
The string `label` is not used.

2023-07-28 18:28 UTC, mkstoyanov commented on src/time_advance.cpp
> +    fk::vector<P, mem_type::owner, resource::device> mom0(dense_size);
This is the kind of code that won't compile on the CPU. Before we made some of the recent changes, if CUDA was not enabled then `device` defaulted to the CPU, but that can be misleading. With the new changes, `device` cannot be used without CUDA.

Have a variable defined with pre-processor macros:
```
#ifdef ASGARD_USE_CUDA
constexpr resouce imex_resc = resouce::device;
#else 
constexpr resouce imex_resc = resouce::host;
#endif
```

The code may need a few more of these, but that's the way to go.

2023-08-01 15:21 UTC, ckendrick commented on src/sparse.hpp
> +            std::cout << std::setw(12) << std::setprecision(4)
Doing this messes up how the row, col indices get printed. I left this as-is for the moment and we can come back to it. This is only ever used for debugging, so this is minor.

2023-08-01 15:21 UTC, ckendrick commented on src/sparse.hpp
> +        if (exists(i, j))
Currently, yes. However `exists()` is used in future PRs. I did update the print function so that it no longer brute force checks every matrix element.

2023-08-01 18:05 UTC, mkstoyanov requested changes

2023-08-01 18:05 UTC, mkstoyanov commented on src/time_advance_tests.cpp
> +TEMPLATE_TEST_CASE("IMEX time advance - landau", "[imex]", double)
I'm guessing this is related to the tolerance issue, but we cannot do that. This code will prevent ASGARD from compiling using only single precision.

2023-08-01 18:05 UTC, mkstoyanov commented on src/lib_dispatch.cpp
> +      expect(status == 0);
This should check against `CUSPARSE_STATUS_SUCCESS`

2023-08-01 18:05 UTC, mkstoyanov commented on src/lib_dispatch.cpp
> +      expect(success == 0);
:) `success == 0` when usually we take `0` to mean `false`

I believe the thing to use here is `success == CUDA_STATUS_SUCCESS`

2023-08-01 18:05 UTC, mkstoyanov commented on src/lib_dispatch.cpp
> +      cusparseSpMatDescr_t mat;
The transients `mat`, `vecX` and `vecY` are actually pointers and have to be deleted.

2023-08-01 18:06 UTC, mkstoyanov commented on src/lib_dispatch.cpp
> +      void *sp_buffer = NULL;
If we are using the same matrix over and over again, we can put `sp_buffer` and the `mat` descriptor into the main sparse-matrix class to avoid extra allocations.

We can do that in another PR, no need to delay this one for that change.

2023-08-01 18:20 UTC, ckendrick commented on src/lib_dispatch.cpp
> +      void *sp_buffer = NULL;
I definitely agree. This is future work for the `sparse` class. It would be good to store this matrix descriptor in the class when the `resource = device`.

2023-08-01 18:31 UTC, ckendrick commented on src/time_advance_tests.cpp
> +TEMPLATE_TEST_CASE("IMEX time advance - landau", "[imex]", double)
This was because `sparse_gemv` was hardcoded for `double` only: https://github.com/project-asgard/asgard/blob/945ded51e48a8a69b1a4e6768f221d8614f033bd/src/lib_dispatch.cpp#L1297-L1300.

I updated `sparse_gemv` to work with both and restored this test back to using `test_precs`.

2023-08-01 19:10 UTC, mkstoyanov approved these changes

2023-08-01 19:20 UTC, merged