Add relaxation 1x1v PDE
project-asgard/asgard pull request #605
Opened 2023-08-02 19:11 UTC by ckendrick

Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

This adds a simple relaxation 1x1v PDE.

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [ ] Bugfix
- [x] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

## What systems has this change been tested on?

Ubuntu 20.04

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [x] this PR is up to date with current the current state of 'develop'
- [x] code added or changed in the PR has been clang-formatted
- [x] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

2023-08-02 19:31 UTC, mkstoyanov requested changes

2023-08-02 19:31 UTC, mkstoyanov commented on src/time_advance_tests.cpp
> +        asgard::fk::vector<TestType> squared(diff);
You're allocating two unnecessary vectors and creating one extra copy. How about this code:
```
TestType L2 = TestType{0};
for(int i=0; i<f_val.size(); i++)
{
  TestType diff = f_val[i] - analytic_solution[i];
  L2 += diff * diff;
}
L2 = std::sqrt(L2);
```

2023-08-02 19:31 UTC, mkstoyanov commented on src/time_advance_tests.cpp
> +          L2 / asgard::inf_norm(analytic_solution) * 100;
It's always confusing to me, are we multiplying the `inf_norm` by 100 or the result by 100 (or dividing by 100).

Either use `( )` or pull the 100 in front.

2023-08-02 19:31 UTC, mkstoyanov commented on src/pde/pde_relaxation_1x1v.hpp
> +    std::transform(
Don't use transform, try to make your code look like a math formula, it's the most expressive way to do math.
```
const P scaled_coeff = coefficient * std::exp(-(0.5 / theta);
for(int i=0; i<x.size(); i++)
{
  fx[i] =  scaled_coeff * std::pow(x[i] - 0.5, 2));
}
```

2023-08-02 19:48 UTC, ckendrick commented
@mkstoyanov Thanks for the comments, I agree and will update the code. Most of that was copy/pasted directly from [main.cpp](https://github.com/project-asgard/asgard/blob/fc019dddef0f1420c8497d0a12544c5098d7197f/src/main.cpp#L276-L307). Do we want to update that code in this PR, or do that as a follow-up PR?

2023-08-02 19:58 UTC, mkstoyanov commented
The overuse of `std::transform` is a persistent problem throughout the code. I think we should stop using it (unless it really makes sense) and the code will slowly change.

In the case of allocating too much when computing L2 norms, it should be changed but the PR doesn't matter. Maybe better to make a separate one.

2023-08-03 02:36 UTC, stefan-schnake commented on src/time_advance_tests.cpp
> +          TestType{100.0} * (L2 / asgard::inf_norm(analytic_solution));
If we're going to do this correctly we should take the L2 norm of the analytic solution (not the current L^\infty norm)

2023-08-03 02:36 UTC, stefan-schnake commented on testing/tests_general.hpp
> +
We should have a generic L2 norm function and just pass in the error between the two solutions.

2023-08-03 11:31 UTC, mkstoyanov commented on testing/tests_general.hpp
> +
BLAS has discrete L-2 norm, which we can use. Computing actual integrals is more involved and we have to write the method ourselves.

I also want to do this without computing the difference between two vectors first, I want to get two vectors and compute the difference on-the-fly.

2023-08-03 12:18 UTC, stefan-schnake commented on testing/tests_general.hpp
> +
Sorry my comment was in the wrong place.  I was referring to discrete norms.  Having a dedicated function that computes the error is fine, but we need a fast (discrete) L2 norm as well.  Currently the adaptivity algorithm uses L^\infty instead of L2 -- I want that to be changed in the future.

2023-08-04 14:24 UTC, mkstoyanov commented on src/pde/pde_relaxation_1x1v.hpp
> +      f[i] = std::pow(x[i], 2);
```suggestion
      f[i] = x[i] * x[i];
```

2023-08-04 14:26 UTC, mkstoyanov commented on src/pde/pde_relaxation_1x1v.hpp
> +      fx[i] = coefficient * std::exp(-(0.5 / theta) * std::pow(x[i] - u1, 2));
```suggestion
      fx[i] = coefficient * std::exp(-(0.5 / theta) * (x[i] - u1) * (x[i] - u1);
```

2023-08-04 14:28 UTC, mkstoyanov commented on src/pde/pde_relaxation_1x1v.hpp
> +      fx[i] = coefficient * std::exp(-(0.5 / theta) * std::pow(x[i] - ux, 2));
```suggestion
      fx[i] = coefficient * std::exp(-(0.5 / theta) * (x[i] - ux) * (x[i] - ux));
```

2023-08-04 15:36 UTC, stefan-schnake requested changes

2023-08-04 15:36 UTC, stefan-schnake commented on src/pde/pde_relaxation_1x1v.hpp
> +      fx[i] = coefficient * std::exp(-(0.5 / theta) * std::pow(x[i] - ux, 2));
Modify the (x-ux)^2 as per @mkstoyanov's recommendations.

2023-08-04 15:38 UTC, stefan-schnake commented on src/pde/pde_relaxation_1x1v.hpp
> +      fx[i] = coefficient * std::exp(-(0.5 / theta) * std::pow(x[i] - u1, 2));
Also change u1 to ux for consistency

2023-08-04 18:16 UTC, mkstoyanov approved these changes

2023-08-04 19:29 UTC, stefan-schnake approved these changes

2023-08-04 19:32 UTC, merged