Refactor IMEX moment calculation and add moments for 1x2v
project-asgard/asgard pull request #606
Opened 2023-08-03 13:37 UTC by ckendrick

Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

This refactors the moment calculation in IMEX to be a single lambda function `calculate_moments` rather than having two copies of the same code in IMEX.

This also adds initial support for calculating moments for 1x2v PDEs.

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [ ] Bugfix
- [x] New feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

## What systems has this change been tested on?

Ubuntu 20.04

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [x] this PR is up to date with current the current state of 'develop'
- [x] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

2023-08-03 15:04 UTC, stefan-schnake requested changes

2023-08-03 15:04 UTC, stefan-schnake commented on src/quadrature.cpp
> +  // int const num_points =
What's the reason for this change?

2023-08-03 15:04 UTC, stefan-schnake commented on src/time_advance.cpp
> +        fk::vector<P, mem_type::owner, imex_resrc> mom0(dense_size);
Insert comment `//  \int f dv`

2023-08-03 15:04 UTC, stefan-schnake commented on src/time_advance.cpp
> +        param_manager.get_parameter("n")->value = [&](P const x_v,
Insert `// n = \int f dv`

2023-08-03 15:04 UTC, stefan-schnake commented on src/time_advance.cpp
> +        fk::vector<P, mem_type::owner, imex_resrc> mom1(dense_size);
`// \int f v_x dv`

2023-08-03 15:04 UTC, stefan-schnake commented on src/time_advance.cpp
> +        param_manager.get_parameter("u")->value = [&](P const x_v,
`// u_x = \int f v_x  dv / n`

2023-08-03 15:04 UTC, stefan-schnake commented on src/time_advance.cpp
> +          // moment 2 = moment1v2 = \int f v_{2} dv
`// \int f v_y dv`

2023-08-03 15:04 UTC, stefan-schnake commented on src/time_advance.cpp
> +          // u2 = \int_v f v_1 dv / n(x)
`// u_y =  \int f v_y dv / n`

2023-08-03 15:04 UTC, stefan-schnake commented on src/time_advance.cpp
> +          // moment 3 = moment2v1
`// \int f v_x^2 dv`

2023-08-03 15:04 UTC, stefan-schnake commented on src/time_advance.cpp
> +          // moment 4 = moment2v2
`// \int f v_y^2 dv`

2023-08-03 15:04 UTC, stefan-schnake commented on src/time_advance.cpp
> +          // theta = \frac{ \int f(v_1^2 + v_2^2) dv }{ 2n(x)} - 0.5 * (u_1^2(x)
Replace `*_1` and `*_2` with `*_x` and `*_y` respectively

2023-08-03 15:04 UTC, stefan-schnake commented on src/time_advance.cpp
> +          // theta = \frac{ \int f(v_1^2 + v_2^2) dv }{ 2n(x)} - 0.5 * (u_1^2(x)
Also remove the `(x)`

2023-08-03 15:04 UTC, stefan-schnake commented on src/time_advance.cpp
> +          // theta moment for 1x1v case
`// \theta = \int f v_x^2 dv / n - u_x^2`

2023-08-03 15:04 UTC, stefan-schnake commented on src/time_advance.cpp
> +    // fx = fx_host.clone_onto_device();
Delete

2023-08-03 15:04 UTC, stefan-schnake commented on src/time_advance.cpp
> +    fm::axpy(f_2s, x, dt); // x here is f(1)
We really need to rename the variable names for the stages.  It's a nightmare right now and will not extend easily to higher order IMEX schemes.

2023-08-03 15:30 UTC, mkstoyanov commented on src/pde/pde_relaxation_1x1v.hpp
> +    return (6.0 - (-6.0)) / std::pow(2, 3);
I'm not sure what rule allows this to compile, but given that `pow` is defined only for floating point numbers and that `2` and `3` are ints, I have no clue what precision this is using.

Should be `std::pow(P{2}, P{3})`

2023-08-03 15:52 UTC, ckendrick commented on src/pde/pde_relaxation_1x1v.hpp
> +    return (6.0 - (-6.0)) / std::pow(2, 3);
I agree, these changes are from the other PR though. I'll update it there. That branch is merged into this one for now to make sure these changes pass the test added by that PR until it gets merged in.

2023-08-03 15:56 UTC, ckendrick commented on src/quadrature.cpp
> +  // int const num_points =
This was the temporary fix for getting problems with high nu values to work properly. This hard codes the number of points to be degree, instead of 10. I think this fix can be done a different way inside IMEX but that hasn't been done yet.

2023-08-03 16:06 UTC, mkstoyanov requested changes

2023-08-03 16:06 UTC, mkstoyanov commented on src/time_advance.cpp
> +  fk::vector<P, mem_type::owner, imex_resrc> x_orig_dev;
`x_orig_dev` is not needed.

First you make a copy of `x_orig`, then you hold on the copy and not use it, then only on line 796 you copy `x_orig_dev` back into `x`. Instead, you can use `x_orig` which is kept persistent throughout the call.

2023-08-03 16:06 UTC, mkstoyanov commented on src/time_advance.cpp
> +    fx_host = x.clone_onto_host();
`imex_resrc` is not a template parameter, so we have to choose between `if-constexpr` statements and per-processor macros `#ifdef ASGARD_USE_CUDA`

Here `fx_host` is defined (and allocated) on line 500, but it is not used until this point and it will only ever be used when CUDA is enabled. So, we should replace the `if-constexpr` with a `#ifdef` and define `fx_host` here.

2023-08-03 16:06 UTC, mkstoyanov commented on src/time_advance.cpp
> +  if constexpr (imex_resrc == resource::device)
`imex_resrc` is not a template parameter, so we have to choose between `if-constexpr` statements and per-processor macros `#ifdef ASGARD_USE_CUDA`

```
#ifdef ASGARD_USE_CUDA
  fk::vector<P, mem_type::owner, imex_resrc> x = x_orig.clone_onto_device();
#else 
  fk::vector<P, mem_type::owner, imex_resrc> x = x_orig;
#endif
```

PS: `x_orig_dev` is not needed, see my other comment.

2023-08-03 16:06 UTC, mkstoyanov commented on testing/tests_general.hpp
> +P calculate_l2(asgard::fk::vector<P> const &sol,
* `l2` is a bit misleading, is it discrete or continuous?
* what's l2-between
* what happens if you switch `sol` and `analytic` (nothing), but why are they called with different names?
```
/**
  * \brief Calculate the discrete l-2 norm of the different between two vectors.
  */
P nrm2_dist(asgard::fk::vector<P> const &x, asgard::fk::vector<P> const &y)
{
  ...
}
```
The `nrm2` uses the BLAS convention and `dist` indicates that it's the distance between two vectors, as opposed to acting on a single vector.

2023-08-03 16:57 UTC, stefan-schnake commented on src/quadrature.cpp
> +  // int const num_points =
What does `use_degree_points` default to and how is it changed?  Seems odd to hardcode the functionality to switch is already in place.

2023-08-04 12:54 UTC, ckendrick commented on src/pde/pde_relaxation_1x1v.hpp
> +    return (6.0 - (-6.0)) / std::pow(2, 3);
Just for reference, it looks like if `std::pow` is given ints, then the arguments are statically casted to double. See the notes section here (second bullet point): https://en.cppreference.com/w/cpp/numeric/math/pow#Notes

2023-08-04 13:02 UTC, ckendrick commented on testing/tests_general.hpp
> +P calculate_l2(asgard::fk::vector<P> const &sol,
These changes are added in the relaxation 1x1v PR.

2023-08-04 14:39 UTC, mkstoyanov commented on src/pde/pde_relaxation_1x1v.hpp
> +    return (6.0 - (-6.0)) / std::pow(2, 3);
Good point about `pow` but there is still an issue, if it is not obvious. Small details like that can potentially mess things up when switching between precisions.

2023-08-08 17:29 UTC, ckendrick commented on src/time_advance.cpp
> +  fk::vector<P, mem_type::owner, imex_resrc> x_orig_dev;
I agree `x_orig_dev` is not needed, although if I replace the `fm::copy(x_orig_dev, x)` call with `fm::copy(x_orig, x)`, there are template issues since `x_orig` from the function signature has no resource template defined.

I think future work is to change IMEX (and probably all time advance routines) to have a template parameter for the resource types, so this would allow this to be removed.

2023-08-08 19:49 UTC, mkstoyanov approved these changes

2023-08-08 19:54 UTC, stefan-schnake approved these changes

2023-08-08 19:54 UTC, merged