Fix number of quadrature points for real space
project-asgard/asgard pull request #610
Opened 2023-08-08 18:34 UTC by ckendrick

Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

The functions for handling real space transformations were originally hardcoded to use only `degree` number of quadrature points. This causes issues when calculating real space moment vectors in IMEX and leads to errors (for example, instabilities for large nu >= 100 used in problems like collisional landau) since those moments are not evaluated directly at the quadrature nodes.

This changes these functions to allow more quadrature nodes to be used and changes IMEX to use the same number of quadrature points that are being used to generate coefficients.  This reproduces the energy conservation when we use peg the number of quadrature points to `degree`.

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [x] Bugfix
- [ ] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

## What systems has this change been tested on?

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [x] this PR is up to date with current the current state of 'develop'
- [x] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

2023-08-30 19:22 UTC, quantumsteve commented on src/io.hpp
> +  auto const quad_dense_size = std::accumulate(
```suggestion
  int const quad_dense_size = std::accumulate(
```

2023-08-30 19:23 UTC, quantumsteve commented on src/moment.cpp
> +      10 * std::pow(2, pde_1d.get_dimensions()[0].get_level());
```suggestion
      10 * fm::two_raised_to(pde_1d.get_dimensions()[0].get_level());
```

2023-08-30 19:24 UTC, quantumsteve commented on src/moment.cpp
> +      10 * std::pow(2, pde_1d.get_dimensions()[0].get_level());
```suggestion
      10 * fm::two_raisd_To (pde_1d.get_dimensions()[0].get_level());
```

2023-08-30 19:25 UTC, quantumsteve commented on src/moment.cpp
> +  this->realspace = fk::vector<P>(realspace_size);
should this be a call to fk::vector<P>::resize(...)?

2023-08-30 19:28 UTC, quantumsteve commented on src/time_advance.cpp
> +                           pde.poisson_off_diag, phi, poisson_E, 10 - 1,
Where does `10` come from?

2023-08-30 19:29 UTC, quantumsteve commented on src/transformations.cpp
> +  int const n      = pow(2, level);
```suggestion
  int const n      = fm::two_raised_to(level);
```

2023-08-30 19:31 UTC, quantumsteve commented on src/transformations.hpp
> +inline int dense_dim_size(int const &degree, int const &level)
```suggestion
inline int dense_dim_size(int const degree, int const level)
```
`int` is smaller than a pointer

2023-08-30 19:32 UTC, quantumsteve commented on src/transformations_tests.cpp
> +      gen_realspace_transform(pde, transformer, true);
Should we also test `false`?

2023-08-30 19:32 UTC, quantumsteve requested changes
See comments

2023-08-31 05:23 UTC, mkstoyanov commented on src/transformations_tests.cpp
> +      gen_realspace_transform(pde, transformer, true);
I don't like the `true/false` input. Can we make it into an expressive `enum`

2023-08-31 17:55 UTC, mkstoyanov commented on src/moment.cpp
> +  this->realspace = fk::vector<P>(realspace_size);
I think resize will also copy the old data (or whatever portion of the old data it can copy). This will not do any copy.

Cole can correct me, if I'm wrong.

2023-08-31 21:20 UTC, ckendrick commented on src/moment.cpp
> +  this->realspace = fk::vector<P>(realspace_size);
This used to be a call to `fk::vector<P>::resize(...)`, but was changed in trying to debug the issue found in #625 (the out-of-bounds issue got amplified by this PR since it extended the number of elements accessed beyond the vector size).

I think this is fine to change back to `resize`, but I believe Miro is correct - `resize` seems to reallocate and then copy the old data.
In this particular case, the data in the `realspace` vector is always overwritten by the next call to `wavelet_to_realspace`, so we don't need to copy the previous data. We should keep whichever is faster, but I'm guessing the resize is probably slower.

2023-09-02 16:58 UTC, mkstoyanov commented on src/io.hpp
> +  int const quad_dense_size = std::accumulate(
```
int quad_dense_size = 1;
auto const &dims = pde_1d.get_dimensions();
for(int i=0; i<dims.size(); i++)
{
  quad_dense_size *= asgard::dense_dim_size(10, dims[i].get_level());
}
```

2023-09-15 14:24 UTC, ckendrick commented on src/transformations_tests.cpp
> +      gen_realspace_transform(pde, transformer, true);
I updated the `true/false` to `quadrature_mode::use_degree`/`quadrature_mode::use_fixed`.

2023-09-20 19:12 UTC, mkstoyanov approved these changes

2023-09-20 20:47 UTC, quantumsteve approved these changes

2023-09-20 20:49 UTC, merged