Add moment calculations for 1x3v PDEs
project-asgard/asgard pull request #611
Opened 2023-08-08 21:18 UTC by ckendrick

Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

This adds moment calculations for 1x3v PDEs to the IMEX time advance function.

Refactoring `calculate_moments()` inside IMEX is planned and will be done in follow-up work which will combine the different cases for each dimension into a single function.

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [ ] Bugfix
- [x] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

## What systems has this change been tested on?

Ubuntu 20.04

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [x] this PR is up to date with current the current state of 'develop'
- [x] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

2023-08-08 22:59 UTC, stefan-schnake requested changes

2023-08-08 22:59 UTC, stefan-schnake commented on src/time_advance.cpp
> +        else if (pde.num_dims == 4 && pde.moments.size() > 3)
```suggestion
        else if (pde.num_dims == 4 && pde.moments.size() > 6)
```

2023-08-08 22:59 UTC, stefan-schnake commented on src/time_advance.cpp
> +            // \int f v_{mom} dv
```suggestion
            // \int f v_x dv
```

2023-08-08 22:59 UTC, stefan-schnake commented on src/time_advance.cpp
> +                       (std::pow(u1, 2) + std::pow(u2, 2) + std::pow(u3, 2));
```suggestion
                       (u1*u1 + u2*u2 + u3*u3);
```
I don't trust `std::pow`.

2023-08-08 22:59 UTC, stefan-schnake commented on src/solver.cpp
> +      }
I like this as an output, but it can get annoying.  Is there a `quilt' option like the matlab version had?

2023-08-09 13:02 UTC, ckendrick commented on src/solver.cpp
> +      }
I agree, I don't believe there is a quiet option implemented yet unfortunately. For now, I could decrease the frequency this prints (instead of every 5 inner iterations).

We should probably create an issue to make a "quiet" option as there is a lot of other print statements which might also be nice to disable for particular runs.

2023-08-09 13:19 UTC, stefan-schnake commented on src/solver.cpp
> +      }
We could also set it to run every restart/3 iterations?  That way it's a fixed number per outer iteration.

2023-08-09 14:27 UTC, mkstoyanov approved these changes

2023-08-09 15:09 UTC, stefan-schnake approved these changes

2023-08-09 15:38 UTC, merged