Update restart for max_adapt_levels
project-asgard/asgard pull request #621
Opened 2023-08-23 15:27 UTC by ckendrick

Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

This saves the `--max_adapt_levels` option to file and loads it on restart. Updates the file restart method to handle adaptivity better and check for FG/SG mismatch.

This also changes the initial element table allocation size to be more reasonable when using sparse grids instead of always trying to reserve the FG DOF.

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [x] Bugfix
- [x] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

## What systems has this change been tested on?

Ubuntu 20.04

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [x] this PR is up to date with current the current state of 'develop'
- [x] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

2023-08-23 16:07 UTC, mkstoyanov commented on src/io.hpp
> +    throw std::runtime_error("Mismatch of grid type between CLI and restart "
Are we sure about this? I mean, whatever grid we read from the file that's what we should use. The only question should be whether we turn adaptivity on/off and even in that case we should use whatever is in the CLI.

The grid that we specify in the CLI should only apply to the initial grid of the problem. What do you guys think?

2023-08-23 16:18 UTC, stefan-schnake commented on src/io.hpp
> +    throw std::runtime_error("Mismatch of grid type between CLI and restart "
> The grid that we specify in the CLI should only apply to the initial grid of the problem

I agree.

2023-08-23 16:59 UTC, stefan-schnake requested changes

2023-08-23 16:59 UTC, stefan-schnake commented on src/elements.cpp
When restarting, the dofs are known ahead of time.  Can we use this information here?

2023-08-23 18:00 UTC, ckendrick commented on src/io.hpp
> +    throw std::runtime_error("Mismatch of grid type between CLI and restart "
Yes, you are right - we only use the grid that is loaded from the file. However, the code does create the grid based on the CLI first, and [then re-creates it if restarting from file](https://github.com/project-asgard/asgard/blob/5715625b08cee81247ce94bcbdfccafad42ece07/src/main.cpp#L213-L224).

This is was meant more as a sanity check to let the user know if the grid options they provide are ignored. For example, if they added a `-f` when loading an adaptive grid, that the `-f` option on the CLI is not used. 

The current behavior is to just silently ignore (minus creating the full grid initially before it gets overwritten by the restart) - we can remove this check if that is the preferred behavior.

2023-08-23 18:18 UTC, mkstoyanov commented on src/io.hpp
> +    throw std::runtime_error("Mismatch of grid type between CLI and restart "
Remove the check and show a warning, but only if the user explicitly specifies a grid and it is not the one in the file. For example, the default is sparse-grid so if the user just says reload and the file contains a full-grid, then there should be no warning. If the user explicitly says `-f` and the grid is not full, then we can give a warning about ignored CLI parameters.

2023-08-23 21:07 UTC, stefan-schnake submitted a review, later dismissed

2023-08-23 21:17 UTC, quantumsteve commented on src/io.hpp
> +  std::cout << "  - adaptivity = " << (do_adapt ? "true" : "false") << "\n";
```suggestion
  std::cout << "  - adaptivity = " << (do_adapt ? "true" : "false") << '\n';
```

2023-08-23 21:18 UTC, quantumsteve commented on src/io.hpp
> +    }
this leaves an unnecessary space at the end.

2023-08-23 21:18 UTC, quantumsteve commented on src/io.hpp
> +              << ", max_adapt_levels = " << max_adapt_str << "\n";
```suggestion
              << ", max_adapt_levels = " << max_adapt_str << '\n';
```

2023-08-25 17:26 UTC, stefan-schnake approved these changes

2023-08-28 19:21 UTC, merged