Move matrix and vector to separate files
project-asgard/asgard pull request #622
Opened 2023-08-23 16:38 UTC by quantumsteve

Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

Describe what this PR changes and why.  If it closes an issue, link to it here
with [a supported keyword](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

This splits the file tensors.hpp into 4 files: matrix.hpp, matrix.tpp, vector.hpp, vector.tpp.

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [ ] Bugfix
- [ ] New feature
- [x] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

## What systems has this change been tested on?

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [x] this PR is up to date with current the current state of 'develop'
- [x] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

2023-08-23 17:01 UTC, mkstoyanov requested changes
Also, check with @ckendrick to make sure this won't mess up with his changes when rebasing.

2023-08-23 17:01 UTC, mkstoyanov commented on src/vector.tpp
> +#include <algorithm>
LOL, new extension .tpp

This is a mistake, right?

2023-08-23 17:01 UTC, mkstoyanov commented on src/asgard_dimension.hpp
> +#include "vector.hpp"
Can we namespace the vector and matrix files.

I had in mind a small change to Cmake to allow modules to be called vector and matrix together with the test files, but the actual source files to be prefixed with asgard. Namely, I don't want to type asgard when I want to call kronmult_matrix-test, but still have the asgard prefix for the names of the source files.

2023-08-23 17:01 UTC, mkstoyanov commented on src/vector.tpp
> +#include <algorithm>
There is also matrix.tpp

2023-08-23 17:13 UTC, quantumsteve commented on src/vector.tpp
> +#include <algorithm>
What extension would you prefer? In the past I've used `.tcc` but `.ipp` (boost's convention) and `.tpp` fit within our current clang-format rules.

https://stackoverflow.com/questions/44774036/why-use-a-tpp-file-when-implementing-templated-functions-and-classes-defined-i

2023-08-23 17:39 UTC, mkstoyanov commented on src/vector.tpp
> +#include <algorithm>
Sorry, I was making a joke, I didn't realize that you actually did that on purpose and there is a convention.

Although, I am still baffled by the point in it. Why split the files when you can have just one .hpp file and have all templates defined in line. Then I don't have to jump back and forth between definition and implementation, especially when many methods are just onelinesrs.

2023-08-23 17:42 UTC, mkstoyanov commented on src/vector.tpp
> +  P zero = 0.0;
Can we inline all those variables in the call to lib dispatch? We don't need a separate variables for one and zero anymore

2023-08-23 17:44 UTC, mkstoyanov commented on src/vector.tpp
> +bool fk::vector<P, mem, resrc>::operator==(vector<P, omem> const &other) const
Are we using this, we have a compare method in testing that allows for custom tolerance, I don't think we should have this as a member

2023-08-23 18:08 UTC, mkstoyanov commented on src/vector.tpp
> +bool fk::vector<P, mem, resrc>::operator==(vector<P, omem> const &other) const
Ugh, it is in a million places in testing. Leave it be.

2023-08-23 20:35 UTC, quantumsteve commented on src/vector.tpp
> +#include <algorithm>
It can give more control over instantiation (though not in the way I'm currently including vector.tpp and matrix.tpp). 

https://softwareengineering.stackexchange.com/questions/373916/c-preferred-method-of-dealing-with-implementation-for-large-templates/375323#375323

Since the definition and implementation was already split in tensors.hpp, I wanted the filenames to show that and personally I find it easier to find a different file than scroll hundreds of lines down to the implementation.

2023-08-23 20:59 UTC, mkstoyanov commented on src/vector.tpp
> +#include <algorithm>
I never liked the old split in `tensors.hpp` it just meant going up and down to see what's going on. Having two files is better than one split file, but I still prefer the single inline file.

We should be considering this not from a general philosophical, but with respect to the specific use-case. The matrix and vector classes have many methods, but most of those are a few short lines, e.g., some expect clauses and one-two commands. Splitting the files does not make things "cleaner", it just means we have to switch to another file to see the short implementation, which may just as well be appended to the declaration. We don't really get any reduction in compile time, i.e., the methods are small and should be visible globally so they can be properly inlined. I don't see any benefit in splitting the files, compared to inlining.

Our options are the following:
* old way of splitting the declaration and implementation in the same file, which I think is the worst case scenario
* current way of splitting into two files, looking into a separate file is better than scrolling the same file
* inlining the implementation into the file, same way that STL does it, which means we need only to scroll for a few lines (everything is compact)

My vote goes for the last one, it is more work for you to make the PR, but I think it is the right way to do this. If there was a huge benefit from splitting vector and matrix type of classes, then STL would have done it for `std::vector` and `std::span`.

On a general philosophical note, if I have a class that contains methods with complex logic (many many lines), I prefer to express the logic in a functional manner in another file, then the class method becomes just a simple call to an external function passing in the relevant member-data. This is easier to reuse and generalize across algorithms, maybe it's just a feature of math-libraries, but it works pretty well. If I really have to write long/hard logic and I want to limit compile times, then I split the class into `.cpp` and `.hpp` (we don't want that for matrix and vector).

I'm not saying `.tpp` files have no use-case, I cannot make such a clam. I can only claim that it is fringe compared to what we do and it doesn't really help for the vector and matrix classes.

2023-08-24 14:07 UTC, quantumsteve commented on src/vector.tpp
> +#include <algorithm>
I removed `matrix.tpp` and `vector.tpp`

2023-08-25 05:53 UTC, mkstoyanov approved these changes
The declaration and implementation are still broken up and hard to read. If it is too much to change for this PR, we can go ahead and move with the merge.

2023-08-25 12:20 UTC, ckendrick commented
Can we pause merging this temporarily? I don't think this will cause a lot of rebasing issues for other PRs, but I would like to check real quick before this is merged in.

2023-08-28 12:31 UTC, ckendrick approved these changes
This should be fine to merge now.

2023-08-28 13:18 UTC, merged