Add riemann 1x2v PDE
project-asgard/asgard pull request #630
Opened 2023-09-08 14:54 UTC by ckendrick

Please review the [developer documentation](https://github.com/project-asgard/asgard/wiki/developing)
on the wiki of this project that contains help and requirements.

## Proposed changes

Adds the 1x2v version of the Riemann PDE.

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [ ] Bugfix
- [x] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

## What systems has this change been tested on?

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [x] this PR is up to date with current the current state of 'develop'
- [x] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

2023-09-08 15:22 UTC, stefan-schnake requested changes

2023-09-08 15:22 UTC, stefan-schnake commented on src/pde/pde_riemann_1x2v.hpp
> +    // param_manager.add_parameter(parameter<P>{"u3", u3});
Delete

2023-09-08 15:22 UTC, stefan-schnake commented on src/pde/pde_riemann_1x2v.hpp
> +      -0.6, 0.6, 8, default_degree,
Default to level 7

2023-09-08 15:25 UTC, stefan-schnake requested changes

2023-09-08 15:25 UTC, stefan-schnake commented on src/pde/pde_riemann_1x2v.hpp
> +                                            terms_im_7, terms_im_8};
I think for clarity these should be made into terms 4,5,6

2023-09-11 13:12 UTC, stefan-schnake submitted a review, later dismissed

2023-09-11 13:42 UTC, stefan-schnake submitted a review, later dismissed

2023-09-11 14:17 UTC, quantumsteve commented on src/pde/pde_riemann_1x2v.hpp
> +    return (x > 0.0) ? x : 0.0;
```suggestion
    return std::max(P{0.}, x);
```

2023-09-11 14:17 UTC, quantumsteve commented on src/pde/pde_riemann_1x2v.hpp
> +    return (x < 0.0) ? x : 0.0;
```suggestion
    return std::min(P{0.}, x);
```

2023-09-11 14:43 UTC, quantumsteve commented on src/pde/pde_riemann_1x2v.hpp
> +    P const second = (x >= -0.3 && x <= 0.3) ? (1.0 / 8.0) : 0.0;
```suggestion
    P const second = std::abs(x) <= 0.3 ? (1.0 / 8.0) : 0.0;
```

2023-09-11 14:43 UTC, quantumsteve commented on src/pde/pde_riemann_1x2v.hpp
> +    P const second = (x >= -0.3 && x <= 0.3) ? (4.0 / 5.0) : 0.0;
```suggestion
    P const second = std::abs(x) < 0.3 ? (4.0 / 5.0) : 0.0;
```

2023-09-11 16:02 UTC, quantumsteve approved these changes

2023-09-11 16:04 UTC, merged