No cost timer
project-asgard/asgard pull request #644
Opened 2023-09-29 14:35 UTC by mkstoyanov

This relates to #521 

Switching many of the calls to timer start/stop with raii style of structs (start is called by the constructor and stop is called by the destructor). The CMake option (comes later) will replace the struct with a no-opt one.

2023-10-03 18:19 UTC, quantumsteve commented on src/tools.hpp
> +struct time_event
Would you add a unit test in `tools_tests.cpp`?

2023-10-03 18:20 UTC, quantumsteve commented on src/tools.hpp
> +  time_event(std::string event_name)
```suggestion
  time_event(std::string const &event_name)
```

2023-10-03 18:20 UTC, quantumsteve commented on src/tools.hpp
> +  time_event(std::string event_name, int op_flops)
```suggestion
  time_event(std::string const &event_name, int op_flops)
```

2023-10-03 18:22 UTC, mkstoyanov commented on src/tools.hpp
> +  time_event(std::string event_name)
The `event_name` is usually short string and I want to use it inline and move out of it.

Isn't passing by non-const value better for that purpose?

2023-10-03 18:26 UTC, quantumsteve commented on src/time_advance.cpp
> +    performance.flops = operator_matrices[matrix_entry::regular].flops();
Copying flops like this looks error-prone. (don't need to change in this PR).

2023-10-03 18:46 UTC, quantumsteve commented on src/tools.hpp
> +  time_event(std::string event_name)
Assuming SSO and time_event's implementation in the header, I think passing by value or reference will give very similar runtime. In the worst case scenario (size() greater than fits inside `std::string`) passing by const reference would be preferred.

Another alternative would be `std::string_view`, but that would require an overload to `simple_timer::start(...)` and changing the comparator in `id_to_start_` to allow heterogeneous comparison lookup.

2023-10-03 21:04 UTC, mkstoyanov commented on src/time_advance.cpp
> +    performance.flops = operator_matrices[matrix_entry::regular].flops();
You're right, I missed that.

2023-10-03 21:05 UTC, mkstoyanov commented on src/tools.hpp
> +struct time_event
Just did.

2023-10-04 13:03 UTC, quantumsteve submitted a review, later dismissed

2023-10-04 17:14 UTC, mkstoyanov commented on src/tools.hpp
> +  time_event(std::string event_name)
You're right, the implementation of the `simple_timer` makes the point mute.

I'm not changing `simple_timer` in this PR.

2023-10-04 19:05 UTC, quantumsteve commented on src/tools_tests.cpp
> +    if (std::is_same_v<TestType, simple_timer_tag>)
```suggestion
    if constexpr (std::is_same_v<TestType, simple_timer_tag>)
```

2023-10-04 19:11 UTC, quantumsteve commented on src/tools.hpp
> +      : event_name_(timer.start(event_name)), flops(op_flops)
Is the cast from `int` to `double` intentional?

2023-10-04 19:13 UTC, quantumsteve requested changes
Just a comment about making if statement (explicitly) constexpr and asking about a cast between types.

2023-10-04 19:18 UTC, mkstoyanov commented on src/tools.hpp
> +      : event_name_(timer.start(event_name)), flops(op_flops)
No, it wasn't. Good catch.

2023-10-04 19:50 UTC, quantumsteve approved these changes

2023-10-04 20:11 UTC, merged